---
sidebar: sidebar 
permalink: cli-upgrade-esxi.html 
keywords: administer, administering, cli, esxi, upgrade, esxi 7.0 
summary: Si vous exécutez ONTAP Select sur VMware ESXi, vous pouvez mettre à niveau le logiciel ESXi depuis une version antérieure prise en charge vers ESXi 7.0 ou version ultérieure. Avant de procéder à la mise à niveau, vous devez comprendre le processus et sélectionner la procédure de mise à niveau appropriée. 
---
= Mettez à niveau votre solution ONTAP Select vers VMware ESXi 7.0 ou une version ultérieure.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Si vous exécutez ONTAP Select sur VMware ESXi, vous pouvez mettre à niveau le logiciel ESXi depuis une version antérieure prise en charge vers ESXi 7.0 ou version ultérieure. Avant de procéder à la mise à niveau, vous devez comprendre le processus et sélectionner la procédure de mise à niveau appropriée.



== Préparez-vous à mettre à niveau VMware ESXi

Préparez et sélectionnez la procédure de mise à niveau appropriée à votre environnement avant de mettre à niveau le logiciel ESXi sur les hyperviseurs hébergeant un cluster ONTAP Select .

.Étapes
. *Familiarisez-vous avec la procédure de mise à niveau de VMware ESXi*
+
La mise à niveau du logiciel ESXi est un processus décrit et pris en charge par VMware. Le processus de mise à niveau de l'hyperviseur fait partie de la procédure de mise à niveau plus vaste lors de l'utilisation de ONTAP Select. Pour plus d'informations, reportez-vous à la documentation VMware.

. *Sélectionnez une procédure de mise à niveau*
+
Plusieurs procédures de mise à niveau sont disponibles. Vous devez sélectionner la procédure applicable en fonction des critères suivants :

+
** La taille de cluster ONTAP Select est prise en charge par les clusters à un ou plusieurs nœuds.
** Utilisation de ONTAP Select Deploy
+
La mise à niveau est possible avec ou sans l'utilitaire Deploy.

+

TIP: Vous devez sélectionner une procédure de mise à niveau qui utilise l'utilitaire d'administration de déploiement.

+
Effectuer une mise à niveau ESXi à l'aide de l'utilitaire d'administration Deploy est l'option la plus générale et la plus résiliente. Toutefois, il peut arriver que la fonction Deploy soit indisponible ou ne puisse pas être utilisée. Par exemple, la mise à niveau vers ESXi 7.0 n'est pas prise en charge avec les versions antérieures d' ONTAP Select et de l'utilitaire d'administration Deploy.

+
Si vous utilisez ces versions précédentes et tentez une mise à niveau, la machine virtuelle ONTAP Select peut rester dans un état où elle ne peut pas être démarrée. Dans ce cas, vous devez sélectionner une procédure de mise à niveau qui n'utilise pas le déploiement. Reportez-vous à la section link:https://mysupport.netapp.com/site/bugs-online/product/ONTAPSELECT/BURT/1172198["1172198"^] pour en savoir plus.



. *Mettez à niveau l'utilitaire d'administration Deploy*
+
Avant d'effectuer une procédure de mise à niveau à l'aide de l'utilitaire Deploy, vous devrez peut-être mettre à niveau votre instance Deploy. En général, il est conseillé de mettre à niveau vers la version la plus récente de Deploy. L'utilitaire Deploy doit prendre en charge la version d' ONTAP Select que vous utilisez.  Se référer àlink:reference_release_notes.html["Notes de version ONTAP Select"] pour plus d'informations.

. *Une fois la procédure de mise à jour terminée*
+
Si vous sélectionnez une procédure de mise à niveau utilisant l'utilitaire de déploiement, vous devez effectuer une opération de mise à jour du cluster à l'aide de Deploy après la mise à niveau de tous les nœuds. Consultez la section actualisation de la configuration du cluster de déploiement pour plus d'informations.





== Mettez à niveau un cluster à un seul nœud en utilisant le déploiement

Vous pouvez utiliser l'utilitaire d'administration Deploy dans le cadre de la procédure de mise à niveau de l'hyperviseur VMware ESXi hébergeant un cluster à nœud unique ONTAP Select.

.Étapes
. Connectez-vous à l'interface de ligne de commande de l'utilitaire de déploiement à l'aide de SSH avec le compte d'administrateur.
. Déplacer le nœud vers l'état hors ligne :
+
[source, cli]
----
node stop --cluster-name <cluster_name> --node-name <node_name>
----
. Mettez à niveau l'hôte hyperviseur sur lequel ONTAP Select s'exécute vers ESXi 7.0 ou version ultérieure en suivant la procédure fournie par VMware.
. Déplacer le nœud vers l'état en ligne :
+
[source, cli]
----
node start --cluster-name <cluster_name> --node-name <node_name>
----
. Une fois le nœud mis en service, vérifiez que le cluster fonctionne correctement.
+
Exemple:

+
....
ESX-1N::> cluster show
Node           Health  Eligibility
-------------- ------- ------------
sdot-d200-011d true    true
....


.Une fois que vous avez terminé
Vous devez effectuer une opération de mise à jour du cluster à l'aide de l'utilitaire d'administration Deploy.



== Mettez à niveau un cluster à plusieurs nœuds à l'aide du déploiement

Vous pouvez utiliser l'utilitaire d'administration Deploy dans le cadre de la procédure de mise à niveau des hyperviseurs VMware ESXi hébergeant un cluster multinœud ONTAP Select.

.Description de la tâche
Vous devez effectuer cette procédure de mise à niveau pour chaque nœud du cluster, un nœud à la fois. Si le cluster contient quatre nœuds ou plus, vous devez mettre à niveau les nœuds de chaque paire haute disponibilité de façon séquentielle avant de passer à la paire haute disponibilité suivante.

.Étapes
. Connectez-vous à l'interface de ligne de commande de l'utilitaire de déploiement à l'aide de SSH avec le compte d'administrateur.
. Déplacer le nœud vers l'état hors ligne :
+
[source, cli]
----
node stop --cluster-name <cluster_name> --node-name <node_name>
----
. Mettez à niveau l'hôte hyperviseur sur lequel ONTAP Select s'exécute vers ESXi 7.0 ou version ultérieure en suivant la procédure fournie par VMware.
+
Pour plus d'informations, reportez-vous à la section préparation de la mise à niveau de VMware ESXi.

. Déplacer le nœud vers l'état en ligne :
+
[source, cli]
----
node start --cluster-name <cluster_name> --node-name <node_name>
----
. Une fois le nœud mis en service, vérifiez que le basculement du stockage est activé et que le cluster fonctionne correctement.
+
.Afficher un exemple
[%collapsible]
====
[listing]
----
ESX-2N_I2_N11N12::> storage failover show
Takeover
Node Partner Possible State Description
-------------- -------------- -------- ---------------------------
sdot-d200-011d sdot-d200-012d true Connected to sdot-d200-012d
sdot-d200-012d sdot-d200-011d true Connected to sdot-d200-011d
2 entries were displayed.
ESX-2N_I2_N11N12::> cluster show
Node Health Eligibility
--------------------- ------- ------------
sdot-d200-011d true true
sdot-d200-012d true true
2 entries were displayed.
----
====


.Une fois que vous avez terminé
Vous devez effectuer la procédure de mise à niveau de chaque hôte utilisé dans le cluster ONTAP Select. Une fois que tous les hôtes ESXi sont mis à niveau, vous devez exécuter une opération de mise à jour du cluster à l'aide de l'utilitaire d'administration de déploiement.



== Mettez à niveau un cluster à un seul nœud sans le déployer

Vous pouvez mettre à niveau l'hyperviseur VMware ESXi qui héberge un cluster à un seul nœud ONTAP Select sans recourir à l'utilitaire d'administration Deploy.

.Étapes
. Connectez-vous à l'interface de ligne de commande ONTAP et arrêtez le nœud.
. Avec VMware vSphere, vérifiez que la machine virtuelle ONTAP Select est hors tension.
. Mettez à niveau l'hôte hyperviseur sur lequel ONTAP Select s'exécute vers ESXi 7.0 ou version ultérieure en suivant la procédure fournie par VMware.
+
Pour plus d'informations, reportez-vous à la section préparation de la mise à niveau de VMware ESXi.

. À l'aide de VMware vSphere, accédez à vCenter et effectuez les opérations suivantes :
+
.. Ajoutez un lecteur de disquette à la machine virtuelle ONTAP Select.
.. Mise sous tension de la machine virtuelle ONTAP Select
.. Connectez-vous à l'interface de ligne de commande de ONTAP à l'aide de SSH avec le compte d'administrateur.


. Une fois le nœud mis en service, vérifiez que le cluster fonctionne correctement.
+
Exemple:

+
....
ESX-1N::> cluster show
Node           Health  Eligibility
-------------- ------- ------------
sdot-d200-011d true    true
....


.Une fois que vous avez terminé
Vous devez effectuer une opération de mise à jour du cluster à l'aide de l'utilitaire d'administration Deploy.



== Mettez à niveau un cluster multinœud sans le déployer

Vous pouvez mettre à niveau les hyperviseurs VMware ESXi hébergeant un cluster multinœud ONTAP Select sans utiliser l'utilitaire d'administration Deploy.

.Description de la tâche
Vous devez effectuer cette procédure de mise à niveau pour chaque nœud du cluster, un nœud à la fois. Si le cluster contient quatre nœuds ou plus, vous devez mettre à niveau les nœuds de chaque paire haute disponibilité de façon séquentielle avant de passer à la paire haute disponibilité suivante.

.Étapes
. Connectez-vous à l'interface de ligne de commande ONTAP et arrêtez le nœud.
. Avec VMware vSphere, vérifiez que la machine virtuelle ONTAP Select est hors tension.
. Mettez à niveau l'hôte hyperviseur sur lequel ONTAP Select s'exécute vers ESXi 7.0 ou version ultérieure en suivant la procédure fournie par VMware.
. À l'aide de VMware vSphere, accédez à vCenter et effectuez les opérations suivantes :
+
.. Ajoutez un lecteur de disquette à la machine virtuelle ONTAP Select.
.. Mise sous tension de la machine virtuelle ONTAP Select
.. Connectez-vous à l'interface de ligne de commande de ONTAP à l'aide de SSH avec le compte d'administrateur.


. Une fois le nœud mis en service, vérifiez que le basculement du stockage est activé et que le cluster fonctionne correctement.
+
.Afficher un exemple
[%collapsible]
====
[listing]
----
ESX-2N_I2_N11N12::> storage failover show
Takeover
Node Partner Possible State Description
-------------- -------------- -------- ---------------------------
sdot-d200-011d sdot-d200-012d true Connected to sdot-d200-012d
sdot-d200-012d sdot-d200-011d true Connected to sdot-d200-011d
2 entries were displayed.
ESX-2N_I2_N11N12::> cluster show
Node Health Eligibility
--------------------- ------- ------------
sdot-d200-011d true true
sdot-d200-012d true true
2 entries were displayed.
----
====


.Une fois que vous avez terminé
Vous devez effectuer la procédure de mise à niveau de chaque hôte utilisé dans le cluster ONTAP Select.
