---
sidebar: sidebar 
permalink: concept_adm_upgrading_nodes.html 
keywords: administer, administering, web, upgrading nodes 
summary: 'Une fois que vous avez déployé un cluster ONTAP Select, vous pouvez mettre à niveau l"image ONTAP de chaque nœud en fonction des besoins à l"aide de la procédure standard de mise à niveau du logiciel ONTAP.' 
---
= Mettez à niveau les nœuds ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Une fois le déploiement d'un cluster ONTAP Select déployé, vous pouvez mettre à niveau l'image ONTAP sur chaque nœud du cluster si nécessaire.


CAUTION: Vous ne pouvez pas utiliser l'utilitaire d'administration Deploy pour effectuer la mise à niveau de nœuds ONTAP Select existants. L'utilitaire Deploy peut uniquement être utilisé pour créer de nouveaux clusters ONTAP Select.



== Procédure générale

Procédez comme suit pour mettre à niveau un nœud ONTAP Select existant.

.Étapes
. Accédez à la page link:https://mysupport.netapp.com/site/downloads/["NetApp Support Site téléchargements"^].
. Faites défiler vers le bas et sélectionnez *ONTAP Select Image*.
. Sélectionnez la version souhaitée de l'image d'installation.
. Consultez le contrat de licence de l'utilisateur final (CLUF) et sélectionnez *accepter et continuer*.
. Sélectionnez et téléchargez le package *ONTAP Select Image Upgrade* approprié. Répondez à toutes les invites si nécessaire.
+
Consultez la link:reference_release_notes.html["notes de version"] pour obtenir des informations supplémentaires et connaître les procédures requises avant de mettre à niveau un nœud ONTAP Select.

. Mettez à niveau le nœud ONTAP Select en suivant les procédures standard de mise à niveau de ONTAP avec le fichier de mise à niveau ONTAP Select. Pour plus d'informations sur les chemins de mise à niveau pris en charge, reportez-vous au link:https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html["Chemins de mise à niveau ONTAP pris en charge"^].




== Restaurez un nœud ONTAP Select

Vous ne pouvez pas rétablir une version antérieure à celle sur laquelle un nœud ONTAP Select a été installé à l'origine. Par exemple :

ONTAP Select 9.16.1 est installé par défaut.:: Vous pouvez mettre à niveau le nœud vers la version 9.17.1, puis revenir à la version 9.16.1 si nécessaire.
ONTAP Select 9.17.1 est installé par défaut.:: Le retour à une version antérieure est impossible car aucune version précédente n'était installée.




== Utilisez le pilote réseau VMXNET3

VMXNET3 est le pilote réseau par défaut inclus dans les nouveaux déploiements de clusters sur VMware ESXi. Si vous mettez à niveau un nœud ONTAP Select existant exécutant ONTAP Select 9.4 ou une version antérieure, le pilote réseau n'est pas automatiquement mis à niveau. Vous devez effectuer une mise à niveau manuelle vers VMXNET3. Vous devez contacter le support NetApp pour obtenir de l'aide concernant la mise à niveau.

.Informations associées
link:https://docs.netapp.com/us-en/ontap/upgrade/index.html["Présentation de la mise à niveau ONTAP"^]
