---
sidebar: sidebar 
permalink: concept_lic_cp_operation.html 
keywords: license, licensing, capacity pools, operation details 
summary: Le modèle de licence des pools de capacité est différent du modèle des niveaux de capacité. Au lieu de dédier la capacité de stockage à chaque nœud individuel, la capacité de stockage est allouée à un pool et partagée entre plusieurs nœuds. Des composants et des processus supplémentaires ont été créés pour prendre en charge le modèle de pools de capacité. 
---
= Détails opérationnels
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le modèle de licence des pools de capacité est différent du modèle des niveaux de capacité. Au lieu de dédier la capacité de stockage à chaque nœud individuel, la capacité de stockage est allouée à un pool et partagée entre plusieurs nœuds. Des composants et des processus supplémentaires ont été créés pour prendre en charge le modèle de pools de capacité.



== Gestionnaire de licences

Le Gestionnaire de licences s'exécute comme un processus distinct au sein de chaque instance de l'utilitaire d'administration de déploiement. Certaines des fonctions fournies par LM incluent :

* Générez un numéro de série à vingt chiffres unique pour chaque nœud en fonction du numéro de série de la licence du pool de capacité
* Créez des locations de capacité à partir des pools de capacité partagée, en fonction des demandes des nœuds ONTAP Select
* Génération de rapports sur l'utilisation du pool via l'interface utilisateur de déploiement




== Caractéristiques du bail

Le stockage alloué pour chaque agrégat de données d'un nœud utilisant une licence de pool de capacité doit avoir un bail associé. Le nœud demande un bail de stockage et, si la capacité est disponible, le Gestionnaire de licences répond par un bail. Chaque bail comporte les attributs explicites ou implicites suivants :

* Gestionnaire de licences chaque nœud ONTAP Select est associé à une instance du Gestionnaire de licences
* Chaque nœud ONTAP Select est associé à un pool de capacité
* Allocation de stockage une valeur de capacité spécifique est attribuée au bail
* La date et l'heure d'expiration des contrats de location ont une durée comprise entre une heure et sept jours, selon la configuration de l'utilisateur.




== ID de verrouillage de licence

Chaque instance du Gestionnaire de licences, et donc chaque instance d'utilitaire de déploiement correspondante, est identifiée par un numéro unique de 128 bits. Ce numéro est associé au numéro de série de la licence de pool de capacité à neuf chiffres pour verrouiller le pool à une instance de Gestionnaire de licences spécifique (qui est effectivement une instance de déploiement). Vous devez fournir les deux valeurs au niveau du site de support NetApp dans le cadre de la génération du fichier de licence NetApp (NLF).

Vous pouvez déterminer l'ID de verrouillage de licence de votre instance de déploiement à l'aide de l'interface utilisateur Web de la manière suivante :

* Page de démarrage cette page s'affiche lorsque vous vous connectez pour la première fois au déploiement. Vous pouvez également afficher la page en cliquant sur la liste déroulante en haut à droite de la page et en sélectionnant mise en route. Le LLID s'affiche dans la section Ajouter des licences.
* Administration cliquez sur l’onglet *Administration* en haut de la page, puis cliquez sur *systèmes* et *Paramètres*.




== Opérations de location de base

Un nœud ONTAP Select doit trouver ou demander une location de capacité valide à chaque fois qu'un agrégat de données est créé, étendu ou modifié. Un bail obtenu à partir d'une demande antérieure toujours valide peut être utilisé, ou un nouveau bail peut être demandé si nécessaire. Le nœud ONTAP Select prend les étapes suivantes pour déterminer la location d'un pool de capacité :

. Si un bail existant est situé au niveau du nœud, il est utilisé tant que tous les éléments suivants sont vrais :
+
** Le bail n'a pas expiré
** La demande de stockage de l'agrégat ne dépasse pas la capacité de location


. Si un bail existant ne peut pas être localisé, le nœud demande un nouveau bail auprès du Gestionnaire de licences.




== Renvoyer la capacité de stockage vers un pool de capacité

La capacité de stockage est allouée à partir d'un pool de capacité selon les besoins et chaque nouvelle demande peut réduire le stockage disponible dans le pool. La capacité de stockage est renvoyée dans le pool dans plusieurs situations, notamment :

* La location d'un agrégat de données expire et n'est pas renouvelée par le nœud
* L'agrégat de données est supprimé



NOTE: Si une machine virtuelle ONTAP Select est supprimée, les baux actifs restent en vigueur jusqu'à leur expiration. Dans ce cas, la capacité est renvoyée dans le pool.
