---
sidebar: sidebar 
permalink: concept_stor_eff_support.html 
keywords: ontap select, storage efficiency support 
summary: 'ONTAP Select fournit des options d"efficacité du stockage similaires aux options d"efficacité du stockage présentes sur les baies FAS et AFF.' 
---
= Prise en charge de l'efficacité du stockage
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select fournit des options d'efficacité du stockage similaires aux options d'efficacité du stockage présentes sur les baies FAS et AFF.

Les déploiements ONTAP Select de NAS virtuel (vNAS) avec VSAN 100 % Flash ou les baies Flash génériques doivent suivre les bonnes pratiques pour ONTAP Select avec stockage DAS non SSD.

La personnalisation du système AFF est automatiquement activée sur les nouvelles installations, à condition que vous ayez un stockage DAS avec des disques SSD et une licence Premium.

Les fonctionnalités de se à la volée suivantes sont automatiquement activées lors de l'installation.

* Détection en ligne de zéro motif
* Déduplication à la volée des volumes
* Déduplication en arrière-plan des volumes
* Compression à la volée évolutive
* Compaction des données à la volée
* Déduplication à la volée dans l'agrégat
* Déduplication en arrière-plan de l'agrégat


Pour vérifier que ONTAP Select a activé toutes les règles d'efficacité du stockage par défaut, exécutez la commande suivante sur un nouveau volume :

[listing]
----
<system name>::> set diag
Warning: These diagnostic commands are for use by NetApp personnel only.
Do you want to continue? {y|n}: y
twonode95IP15::*> sis config
Vserver:                                SVM1
Volume:                                 _export1_NFS_volume
Schedule                                -
Policy:                                 auto
Compression:                            true
Inline Compression:                     true
Compression Type:                       adaptive
Application IO Si                       8K
Compression Algorithm:                  lzopro
Inline Dedupe:                          true
Data Compaction:                        true
Cross Volume Inline Deduplication:      true
Cross Volume Background Deduplication:  true
----

NOTE: Pour les mises à niveau ONTAP Select à partir de la version 9.4, vous devez installer ONTAP Select 9.4 sur un stockage SSD DAS avec une licence Premium. De plus, la case à cocher *Activer l'efficacité du stockage* doit être cochée lors de l'installation initiale du cluster avec ONTAP Deploy. Pour activer la mise à niveau post-ONTAP de type AFF lorsque les conditions précédentes ne sont pas respectées, il est nécessaire de créer manuellement un argument de démarrage et de redémarrer un nœud. Contactez le support technique pour plus de détails.

Le tableau ci-dessous récapitule les différentes options d'efficacité du stockage disponibles, activées par défaut ou non par défaut mais recommandées, en fonction de la version ONTAP Select et du type de support.

[cols="6"]
|===
| Fonctionnalités ONTAP Select | 9.6 / 9.5 Premium ou Premium XL^4^ (SSD DAS) | 9.4^1^ / 9.3^2^ Premium (SSD DAS) | 9.6 / 9.5 / 9.4^1^ / 9.3^2^ toutes les licences (disque dur DAS) | 9.6 toutes les licences (vNAS) | 9.5 / 9.4^1^ / 9.3^2^ Premium ou Standard (vNAS)^3^ 


| Détection nulle en ligne | Oui (par défaut) | Oui, activé par l'utilisateur et par volume | Oui, activé par l'utilisateur et par volume | Oui, activé par l'utilisateur et par volume | Non pris en charge 


| Déduplication à la volée des volumes | Oui (par défaut) | Oui (recommandé) activé par l'utilisateur sur la base du volume | Non disponible | Non pris en charge | Non pris en charge 


| Compression 32 K en ligne (compression secondaire) | Oui, activée par l'utilisateur sur la base d'un volume. | Oui, activé par l'utilisateur et par volume | Oui, activé par l'utilisateur et par volume | Non pris en charge | Non pris en charge 


| Compression à la volée 8 Ko (compression adaptative) | Oui (par défaut) | Oui (recommandé) activé par l'utilisateur sur la base du volume | Oui, activée par l'utilisateur sur la base d'un volume | Non pris en charge | Non pris en charge 


| Compression en arrière-plan | Non pris en charge | Non pris en charge | Oui, activée par l'utilisateur sur la base d'un volume | Oui, activé par l'utilisateur et par volume | Non pris en charge 


| Lecteur de compression | Oui. | Oui, activé par l'utilisateur et par volume | Oui. | Oui, activé par l'utilisateur et par volume | Non pris en charge 


| Compaction des données à la volée | Oui (par défaut) | Oui (recommandé) activé par l'utilisateur sur la base du volume | Oui, activée par l'utilisateur sur la base d'un volume | Non pris en charge | Non pris en charge 


| Scanner de compactage | Oui. | Oui, activé par l'utilisateur et par volume | Oui. | Non pris en charge | Non pris en charge 


| Déduplication à la volée dans l'agrégat | Oui (par défaut) | Oui (recommandé) pour chaque volume avec garantie d'espace = aucune) | S/O | Non pris en charge | Non pris en charge 


| Déduplication en arrière-plan des volumes | Oui (par défaut) | Oui (recommandé) | Oui, activée par l'utilisateur sur la base d'un volume | Oui, activé par l'utilisateur et par volume | Non pris en charge 


| Déduplication en arrière-plan de l'agrégat | Oui (par défaut) | Oui (recommandé) pour chaque volume avec garantie d'espace = aucune) | S/O | Non pris en charge | Non pris en charge 
|===
[Small]#^1^ONTAP Select 9.4 sur des SSD DAS (nécessite une licence Premium) permet la déduplication des données existantes dans un agrégat à l'aide de scanners de volumes interglobaux en arrière-plan au niveau de l'agrégat. Cette opération unique est effectuée manuellement pour les volumes créés avant 9.4.# [Small]#^2^ONTAP Select 9.3 sur des SSD DAS (nécessite une licence Premium) prend en charge la déduplication en arrière-plan au niveau de l'agrégat. Cependant, cette fonctionnalité doit être activée après la création de l'agrégat.# [Small]#^3^ONTAP Select 9.5 vNAS par défaut ne prend pas en charge les stratégies d'efficacité du stockage. Consultez la section vNAS pour obtenir plus de détails sur l'enregistrement de données sur instance unique (SIDL).# [Small]#^4^ONTAP Select 9.6 prend en charge une nouvelle licence (Premium XL) et une nouvelle taille de machine virtuelle (grande). Toutefois, la machine virtuelle grande taille n'est prise en charge que pour les configurations DAS utilisant RAID logiciel. Les configurations RAID et vNAS matérielles ne sont pas prises en charge avec la machine virtuelle ONTAP Select grande dans la version actuelle.#

Après la mise à niveau vers ONTAP Select 9.5 ou une version ultérieure, attendez que le système `system node upgrade-revert show` commande pour indiquer que la mise à niveau est terminée avant de vérifier les valeurs d'efficacité du stockage pour les volumes existants.

Sur un système mis à niveau vers ONTAP Select 9.5 ou version ultérieure, un nouveau volume créé sur un agrégat existant ou un nouvel agrégat a le même comportement que le volume créé lors d'un nouveau déploiement. Les volumes existants soumis à la mise à niveau du code ONTAP Select possèdent la plupart des mêmes règles d'efficacité du stockage que ceux d'un nouveau volume, avec quelques variantes :

Scénario 1:: Si aucune stratégie d'efficacité du stockage n'était activée sur un volume avant la mise à niveau, alors :
+
--
* Des volumes avec `space guarantee = volume` ne mettez pas la compaction des données à la volée, la déduplication à la volée dans les agrégats ou la déduplication en arrière-plan dans l'agrégat. Ces options peuvent être activées après la mise à niveau.
* Des volumes avec `space guarantee = none` la compression en arrière-plan n'est pas activée. Cette option peut être activée après la mise à niveau.
* La règle d'efficacité du stockage sur les volumes existants est définie sur automatique après la mise à niveau.


--
Scénario 2:: Si les fonctionnalités d'efficacité du stockage sont déjà activées sur un volume avant la mise à niveau, alors :
+
--
* Des volumes avec `space guarantee = volume` ne constatez aucune différence après la mise à niveau.
* Des volumes avec `space guarantee = none` activer la déduplication en arrière-plan de l'agrégat.
* Des volumes avec `storage policy inline-only` définir leur stratégie sur auto.
* Les volumes dotés de règles d'efficacité du stockage définies par l'utilisateur n'ont pas de modification de règle, à l'exception des volumes avec `space guarantee = none`. Ces volumes ont activé la déduplication en arrière-plan de l'agrégat.


--


Les fonctionnalités d'efficacité du stockage, activées avant la mise à niveau, sont conservées après la mise à niveau vers ONTAP Select 9.5 ou une version ultérieure. Si les fonctionnalités d'efficacité du stockage n'étaient pas activées avant la mise à niveau, l'efficacité du stockage n'est pas activée après la mise à niveau.
