---
sidebar: sidebar 
permalink: concept_vpi_manage_before.html 
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, manage, managing 
summary: 'Avant d"installer et de gérer le plug-in vCenter Deploy, vous devez procéder à plusieurs opérations.' 
---
= Avant de commencer
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Avant d'installer et de gérer le plug-in vCenter Deploy, vous devez procéder à plusieurs opérations.



== Décidez si vous souhaitez utiliser l'interface utilisateur Web de déploiement ou l'interface de ligne de commande

Dans la plupart des cas, l'interface utilisateur Web de déploiement constitue l'option la plus pratique pour gérer le plug-in vCenter. Il s'agit de l'option décrite dans cette procédure. Cependant, vous pouvez également gérer le plug-in à l'aide de l'interface de ligne de commande de déploiement. Pour plus d'informations, saisissez les commandes suivantes à l'invite de l'interface de ligne de commande de déploiement :

* `deploy plugin ?` (Les sous-commandes incluent : installation, suppression, affichage et mise à jour)
* `deploy plugin-packages show`




== Préparation commune à toutes les tâches de gestion

Vous devez suivre plusieurs étapes, quelle que soit la tâche de gestion. La préparation commune comprend :

* Lecture de la section mise en route pour se familiariser avec le plug-in de déploiement vCenter.
* S'assurer que l'utilitaire d'administration de déploiement ONTAP Select est installé et en cours d'exécution.
Pour plus d'informations, consultez la documentation relative à l'installation et au déploiement de clusters pour VMware.
* Acquisition des informations d'identification du compte :
+
** Déployer un compte administrateur
** Comptes de serveur vCenter


* Assurance que l'utilitaire de déploiement dispose d'un accès réseau au port 443 sur le serveur vCenter.


Une préparation supplémentaire peut être nécessaire en fonction de la tâche de gestion.



== Préparez les comptes de serveur vCenter

Avant d'installer et d'utiliser le plug-in de déploiement, vous devez créer les comptes vCenter avec les privilèges requis. Vous pouvez créer un compte unique avec tous les privilèges nécessaires ou créer plusieurs comptes avec un seul privilège. Dans un souci de simplicité, l'exemple suivant distribue les privilèges vCenter dans trois rôles distincts qui peuvent ensuite être attribués aux trois comptes correspondants.



=== Validez l'accès utilisateur au plug-in

Vous devez disposer d'un compte pour valider l'accès au plug-in via vSphere. Le compte doit disposer du privilège vCenter suivant : sessions.validate.session. Une fois le compte créé dans vCenter, vous devez le définir dans l'utilitaire d'administration de déploiement. Dans l'interface utilisateur Web de déploiement, cliquez sur l'onglet Administration, puis sur informations d'identification pour indiquer l'emplacement et les informations d'identification du serveur vCenter.

Ce compte est utilisé de l'une des manières suivantes :

* Le serveur vCenter nommé devient disponible en tant que cible d'installation dans la boîte de dialogue d'enregistrement du plug-in.
* Le compte est utilisé par le déploiement pour valider les demandes des utilisateurs vSphere d'accès au plug-in une fois le plug-in installé.




=== Gestion du plug-in

Dans l'interface utilisateur Web de déploiement, vous pouvez installer le plug-in, puis le mettre à niveau ou le supprimer. Chaque fois que vous effectuez l'une de ces actions de gestion, vous êtes invité à créer un compte vCenter dans la fenêtre contextuelle. Chaque action de gestion est contrôlée par un privilège vCenter distinct.

Pour installer, mettre à niveau et supprimer le plug-in, vous devez attribuer les privilèges suivants :

* Extension
+
** Extension de registre
** Mettre à jour l'extension
** Annuler l'enregistrement de l'extension




Vous pouvez créer un seul rôle et un seul compte avec les trois privilèges ou diviser les privilèges entre plusieurs comptes selon vos besoins.



=== Accédez au plug-in

Les utilisateurs finaux peuvent accéder au plug-in via vSphere. Vous devez attribuer le privilège suivant aux comptes qui utiliseront le plug-in :

* NetApp
+
** Déploiement de ONTAP Select
+
*** Administrateur





