---
sidebar: sidebar 
permalink: concept_lic_platforms.html 
keywords: license, licensing, platform license offerings, license offerings, standard, premium, premium xl 
summary: 'Vous pouvez acheter une licence de niveau de capacité ou de pool de capacité ONTAP Select avec l"un des trois niveaux de capacité de la plateforme. Ces offres de licences déterminent les fonctionnalités des hôtes dans lesquels vous déployez ONTAP Select.' 
---
= Découvrez les offres de licences de plateforme pour ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez acheter une licence ONTAP Select Capacity Tier ou Capacity Pool de niveau Standard, Premium ou Premium XL. Ces offres de licences déterminent les fonctionnalités des hôtes dans lesquels vous déployez ONTAP Select.



== Avantages de l'offre de licence de plateforme

Une offre de licence spécifique détermine les capacités de l'hôte hyperviseur dans deux domaines :

* Type d'instance (processeur, mémoire)
* Ou des caractéristiques supplémentaires


Les offres de licences sont classées dans un ordre croissant de capacités allant de la version standard à la version Premium XL. En général, l'option de licence que vous choisissez vous accorde les capacités de ce niveau et de tous les niveaux inférieurs. Par exemple, le niveau Premium fournit les capacités de Premium et de Standard.

Le tableau suivant compare les fonctionnalités des offres de licence standard, premium et premium XL.

[cols="25,25,25,25,25"]
|===
2+| La licence prend en charge ... | Standard | Premium | XL haut de gamme 


2+| Type d'instance | Petit seulement | Petit ou moyen | Petit, moyen ou grand 


.2+| Disques durs (HDD) dans un ... | Configuration RAID matérielle | Oui. | Oui. | Oui. 


| Configuration vNAS | Oui. | Oui. | Oui. 


.3+| Disques SSD (Solid State Drives) dans un ... | Configuration RAID matérielle | Non | Oui. | Oui. 


| Configuration RAID logicielle | Non | Oui. | Oui. 


| Configuration vNAS | Oui. | Oui. | Oui. 


.3+| Disques NVMe dans un ... | Configuration RAID matérielle | Non | Non | Oui. 


| Configuration RAID logicielle | Non | Non | Oui. 


| Configuration vNAS | Oui. | Oui. | Oui. 


2+| Les SDS dans MetroCluster | Non | Oui. | Oui. 
|===

NOTE: Les machines virtuelles basées sur le noyau (KVM) ne prennent pas en charge le type d'instance volumineuse.



== Comparez les offres de licences de plate-forme prises en charge par le matériel

Les offres de licences XL standard, Premium et Premium prennent en charge un large éventail de matériels et de logiciels. Pour obtenir des informations à jour sur les versions matérielles et logicielles, reportez-vous au link:https://mysupport.netapp.com/matrix/["Matrice d'interopérabilité"^].

[role="tabbed-block"]
====
.Élément de base
--
[cols="5"30"]
|===


2+| Type d'élément de base 3+| Description 


2+| Protocoles hôtes 3+| NFS, SMB/CIFS, iSCSI et NVMe over TCP 


2+| Options de déploiement 3+| Cluster à nœud unique, cluster à deux nœuds (paire HA), cluster à quatre, six, huit, dix ou douze nœuds 


2+| Capacité prise en charge (par nœud) 3+| Jusqu'à 400 To de données brutes (ESXi et KVM) 
|===
--
.Sous-jacent
--
[cols="5"30"]
|===


2+| Type de matériel 3+| Description 


2+| Taille de l'instance | Petit | Moyen | Grand 


2+| Famille CPU | Intel Xeon E5-26xx v3 (Haswell) ou ultérieur | Intel Xeon E5-26xx v3 (Haswell) ou ultérieur | Intel Xeon E5-26xx v3 (Haswell) ou ultérieur 


2+| Processeur/mémoire ONTAP Select | 4 processeurs virtuels (vCPU) / 16 Go de RAM | 8 vCPU/64 Go de RAM | 16 vCPU / 128 Go de RAM 


2+| Configuration minimale requise pour le processeur/la mémoire de l'hôte ^1^ | 6 cœurs/24 Go de RAM | 10 cœurs / 72 Go de RAM | 18 cœurs/136 Go de RAM 


2+| Réseau (par nœud) 3+| Un cluster à un seul nœud nécessite au minimum deux ports 1 GbE. Un cluster à deux nœuds (paire HA) nécessite au minimum quatre ports 1 GbE. Un cluster à quatre, six, huit, dix ou douze nœuds nécessite au minimum deux ports 10 GbE. 
|===
^1^ Suppose deux cœurs et 8 Go de RAM pour l'hyperviseur.

--
.Type de stockage
--
Le tableau suivant indique le type de licence minimum requis pour le stockage spécifié. 

[cols="5"30"]
|===


2+| Type de stockage 3+| Description 


2+| Type de licence | Standard | Premium | XL haut de gamme 


2+| Taille de l'instance | Petit | Petit et moyen | Petit, moyen et grand 


2+| DAS local avec contrôleur RAID matériel | 8 à 60 disques | 8 à 60 disques | 8 à 60 disques 


2+| HDD (SAS, NL-SAS ET SATA) | Sans objet | 4 à 60 disques | 4 à 60 disques 


2+| SSD (SAS) | Sans objet | 4 à 60 disques (SSD uniquement) | 4 à 60 disques (SSD uniquement) 


2+| DAS local avec RAID logiciel | Sans objet | En vigueur | 4 à 14 disques (NVMe uniquement) 


2+| Tableaux externes ^1^ 3+| Les datastores hébergés sur baies externes sont connectés via FC, FCoE, iSCSI et NFS (NFS n'est pas pris en charge pour KVM). Ces datastores assurent haute disponibilité et résilience. 
|===
^1^ la prise en charge du protocole des baies externes reflète la connectivité du stockage en réseau.

--
.Logiciels
--
[cols="5"30"]
|===


2+| Type de logiciel 3+| Description 


2+| Hyperviseur (VMware) 3+| VMware vSphere 9.0, VMware vSphere 8.0GA et mises à jour 1 à 3, VMware vSphere 7.0GA et mises à jour 1 à 3C 


2+| Hyperviseur (KVM)  a| 
Red Hat Enterprise Linux 64 bits (KVM) 10.0, 9.6, 9.5, 9.4, 9.3, 9.2, 9.1, 9.0, 8.8, 8.7 et 8.6

Rocky Linux (KVM) 10.0, 9.6, 9.5, 9.4, 9.3, 9.2, 9.1, 9.0, 8.9, 8.8, 8.7 et 8.6

*Remarque* : Il existe des limitations de flux de travail RAID logiciel pour les hyperviseurs KVM sur les hôtes RHEL 10.0 et Rocky Linux 10.0. Pour plus d'informations, consultez les articles suivants de la base de connaissances :

* link:https://kb.netapp.com/on-prem/ontap/ontap-select/Select-Issues/CDEPLOY-4020["CDEPLOY-4020 : ONTAP Select Deploy : Message d’avertissement lors de la création du cluster HWR sous RHEL 10 et ROCKY 10"^]
* link:https://kb.netapp.com/on-prem/ontap/ontap-select/Select-Issues/CDEPLOY-4025["CDEPLOY-4025 : ONTAP Select DeployGUI : Les pools de stockage et les disques de stockage ne sont pas visibles pour SWR sur la page de création de cluster sur les hôtes RHEL10/Rocky 10"^]




2+| Logiciel de gestion 3+| Suite de gestion NetApp Active IQ Unified Manager ONTAP Select Deploy Utility SnapCenter (en option) 
|===
--
====
.Informations associées
* link:concept_lic_production.html["En savoir plus sur les types de licence de niveau de capacité et de pool de capacité"]

