---
sidebar: sidebar 
permalink: concept_adm_before.html 
keywords: administer, administering, web, before you begin 
summary: 'Une fois que vous avez créé un cluster ONTAP Select, vous pouvez prendre en charge le déploiement en effectuant diverses tâches administratives. Il y a quelques considérations d"ordre général à prendre en compte.' 
---
= Avant de commencer à gérer ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Une fois que vous avez créé un cluster ONTAP Select, vous pouvez prendre en charge le déploiement en effectuant diverses tâches administratives. Il y a quelques considérations d'ordre général à prendre en compte.

En général, les procédures que vous pouvez effectuer à l'aide de l'interface Web de déploiement sont réparties en trois catégories.

.Déployer un cluster ONTAP Select
Vous pouvez déployer un cluster à un ou plusieurs nœuds. Voir link:task_deploy_cluster.html["Déployer un cluster ONTAP Select"] pour en savoir plus.

.Exécutez une procédure sur un cluster ONTAP Select existant
Les procédures administratives sont organisées en différentes catégories, telles que _Security_ et _clusters_.

.Effectuez une procédure sur l'utilitaire de déploiement
Plusieurs procédures sont spécifiques au déploiement (par exemple, la modification du mot de passe de l'administrateur).



== Administrer ONTAP Select

De nombreuses procédures administratives sont disponibles dans le cadre de la prise en charge de ONTAP Select. En outre, il existe des procédures spécifiques à l'utilitaire d'administration de déploiement. Le plus important de ces procédures est présenté ci-dessous. En général, tous utilisent l'interface utilisateur Web de déploiement.


NOTE: Vous pouvez également link:https://docs.netapp.com/us-en/ontap-select/task_cli_signing_in.html["utilisez l'interface de ligne de commande"] Pour administrer ONTAP Select.



== Effectuer une configuration ONTAP supplémentaire

Une fois un cluster ONTAP Select déployé, vous pouvez configurer et gérer le cluster comme vous le feriez avec un système ONTAP matériel. Par exemple, vous pouvez utiliser ONTAP System Manager ou l'interface de ligne de commandes ONTAP pour configurer le cluster ONTAP Select.

.Logiciels client NetApp
Vous pouvez vous connecter à ONTAP Select à l'aide du logiciel client NetApp pris en charge suivant :

* ONTAP System Manager
* Active IQ Unified Manager
* OnCommand Insight
* OnCommand Workflow Automation
* SnapCenter
* Virtual Storage Console pour VMware vSphere


Pour identifier les versions prises en charge du logiciel client, consultez le link:https://mysupport.netapp.com/matrix/["Matrice d'interopérabilité NetApp"^]. Si le logiciel client prend en charge ONTAP 9, la même version est également prise en charge avec ONTAP Select.


NOTE: L'utilisation de SnapCenter et des plug-ins correspondants nécessite des licences basées sur serveur. Les licences des plug-ins SnapCenter ne sont pas prises en charge pour le moment avec ONTAP Select pour les systèmes de stockage.

Tout autre logiciel client NetApp non inclus dans la liste n'est pas pris en charge par ONTAP Select.

.Options de configuration possibles
Plusieurs options sont disponibles lors de la configuration du cluster, y compris les suivantes :

* Création de la configuration réseau
* Mise en place des agrégats
* Création des machines virtuelles de stockage des données (SVM)


.Licences achetées avec capacité de stockage
Si vous décidez de ne pas installer les fichiers de licence ayant une capacité de stockage dans le cadre du déploiement du cluster ONTAP Select, vous devez acquérir et installer les fichiers de licence avant que ce délai expire pour les clusters exécutant une licence achetée.

.Agrégats en miroir
Des disques de spare de données sont créés par l'utilitaire d'administration Deploy sur chaque nœud ONTAP Select à partir de l'espace de datastore utilisable (par exemple, pool0 et Pool1). Pour mettre en œuvre la haute disponibilité des données dans un cluster multinœud, vous devez créer un agrégat en miroir à l'aide de ces unités.
