---
sidebar: sidebar 
permalink: concept_vpi_vcenter_integration.html 
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, vcenter integration 
summary: 'Le plug-in de déploiement est étroitement intégré au serveur vCenter. Grâce à cette intégration, vous pouvez facilement parcourir les ressources gérées par l"utilitaire de déploiement et le serveur vCenter. Plusieurs exemples de cette intégration sont fournis ci-dessous.' 
---
= Déployez le plug-in et l'intégration à vCenter
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le plug-in de déploiement est étroitement intégré au serveur vCenter. Grâce à cette intégration, vous pouvez facilement parcourir les ressources gérées par l'utilitaire de déploiement et le serveur vCenter. Plusieurs exemples de cette intégration sont fournis ci-dessous.



== Ressources VMware affectées à un cluster ONTAP Select

Un cluster ONTAP Select s'exécute sur VMware en tant que ensemble d'un ou de plusieurs nœuds. Chaque nœud est une machine virtuelle dédiée sur un hôte ESXi différent. Un cluster ONTAP Select est associé aux ressources VMware suivantes :

* Hôtes
* Machines virtuelles ONTAP
* Datastore
* Réseaux


Il existe plusieurs façons d'afficher les ressources VMware utilisées par un cluster ONTAP Select spécifique.



== Affichez les ressources VMware d'un cluster via le plug-in

Vous pouvez afficher les ressources VMware affectées à un cluster ONTAP Select via le plug-in de déploiement.

.Étapes
. Connectez-vous au serveur vCenter via vSphere HTML5 à l'aide d'un navigateur.
. Cliquez sur *clusters ONTAP Select* dans le volet *listes d'inventaire globales*.
. Cliquez sur le cluster souhaité dans la liste de droite.
. Cliquez sur l'onglet *plus d'objets* et sélectionnez la catégorie de ressources souhaitée en haut de la page.
. Sélectionnez une ressource VMware spécifique pour afficher des informations supplémentaires.




== Afficher les clusters ONTAP Select via une machine virtuelle ESXi

Vous pouvez afficher le cluster ONTAP Select et les ressources associées en accédant à une machine virtuelle VMware.

.Étapes
. Connectez-vous au serveur vCenter via vSphere HTML5 à l'aide d'un navigateur.
. Cliquez sur *Menu* en haut, puis sur *VM et modèles*.
. Sélectionnez la machine virtuelle souhaitée dans la liste de gauche.
. Cliquez sur l'onglet *More Objects* pour afficher le cluster ONTAP Select exécuté dans la VM.
. Pour afficher l'ensemble des ressources VMware associées au cluster, cliquez sur le cluster ONTAP Select, puis sur l'onglet *More Objects*.




== Créez un cluster à un seul nœud sur un hôte ESXI

Vous pouvez sélectionner un hôte d'hyperviseur ESXI via l'interface vSphere et déployer un cluster ONTAP Select à un seul nœud.

.Étapes
. Connectez-vous au serveur vCenter via vSphere HTML5 à l'aide d'un navigateur.
. Cliquez sur *Menu* en haut, puis sur *hôtes et clusters*.
. Cliquez avec le bouton droit de la souris sur l'hôte de l'hyperviseur souhaité à gauche, sélectionnez *ONTAP Select*, puis cliquez sur *Nouveau ONTAP Select*.
. Terminez le processus de déploiement en suivant les étapes de la section link:task_deploy_cluster.html["Déployer un cluster ONTAP Select"].

