---
sidebar: sidebar 
permalink: concept_vpi_planning.html 
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, planning 
summary: 'Avant d"installer et d"utiliser le plug-in vCenter Deploy, vous devez vous préparer à assurer la réussite de votre installation.' 
---
= Prévoyez d'utiliser le plug-in de déploiement vCenter
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Avant d'installer et d'utiliser le plug-in vCenter Deploy, vous devez vous préparer à assurer la réussite de votre installation.



== Configuration logicielle requise

Vous devez tenir compte de plusieurs exigences logicielles, comme décrit dans le tableau suivant.

[cols="35,65"]
|===
| Logiciel | Version prise en charge 


| Utilitaire ONTAP Select Deploy | 2.11.2 ou ultérieure 


| VMware vSphere | 6.5 GA ou version ultérieure 


| Interface utilisateur VMware vSphere | HTML5 (la version Flash n'est pas prise en charge) 


| VMware ESXi | 6.5U2 ou version ultérieure 
|===


== Restrictions de taille des clusters

Vous devez tenir compte de plusieurs restrictions liées à la taille du cluster, comme indiqué dans le tableau suivant.

[cols="35,65"]
|===
| Élément | Nombre maximum pris en charge 


| ONTAP Select déploie les clusters | 100 


| Nœuds (machines virtuelles) | 1000 


| Hôtes | 800 
|===


== Privilèges RBAC pour les comptes d'utilisateur vCenter

Plusieurs privilèges vCenter sont nécessaires pour gérer et accéder au plug-in. Ces privilèges correspondent aux actions des trois catégories suivantes :

* Gestion du plug-in via le déploiement :
+
** Installer
** Mise à niveau
** Déposer


* Accès au plug-in via le client vSphere
* Validation de l'accès utilisateur au plug-in via vSphere


Voir link:concept_vpi_manage_before.html#preparing-the-vcenter-server-accounts["Préparation des comptes de serveur vCenter"] pour en savoir plus.



== Limitations de AutoSupport

Le plug-in vCenter Deploy fournit un minimum d'informations sur l'utilisation de l'utilitaire d'administration Deploy (y compris l'URL du plug-in). Cependant, AutoSupport comprend un tableau des plug-ins installés qui peut être affiché via le visualiseur AutoSupport.


NOTE: Vous ne pouvez pas télécharger un package AutoSupport via le client Web vSphere à l'aide du plug-in Deploy. Vous devez utiliser l'interface de déploiement natif pour télécharger les packages AutoSupport.



== Restrictions supplémentaires

Plusieurs restrictions supplémentaires doivent être prises en compte avant d'installer et d'utiliser le plug-in vCenter Deploy :

* Chaque instance du plug-in vCenter ne prend en charge qu'un seul serveur vCenter.
* Les serveurs vCenter configurés en mode lié ne sont pas pris en charge.
* L'interface graphique du plug-in de déploiement de vSphere n'affiche que les clusters dotés de machines virtuelles ONTAP Select gérées par le même serveur vCenter. Les clusters ONTAP Select qui s'exécutent sur des hôtes ESXi et KVM autonomes ne sont pas inclus.

