---
sidebar: sidebar 
permalink: concept_lic_platforms.html 
keywords: license, licensing, platform license offerings, license offerings, standard, premium, premium xl 
summary: 'Vous pouvez acheter une licence de niveau de capacité ou de pool de capacité ONTAP Select avec l"un des trois niveaux de capacité de la plateforme. Ces offres de licences déterminent les fonctionnalités des hôtes dans lesquels vous déployez ONTAP Select.' 
---
= Découvrez les offres de licences de plateforme pour ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez acheter une licence ONTAP Select Capacity Tier ou Capacity Pool de niveau Standard, Premium ou Premium XL. Ces offres de licences déterminent les fonctionnalités des hôtes dans lesquels vous déployez ONTAP Select.



== Avantages de l'offre de licence de plateforme

Une offre de licence spécifique définit et limite les fonctionnalités de l'hôte hyperviseur dans deux domaines :

* Type d'instance (processeur, mémoire)
* Ou des caractéristiques supplémentaires


Les offres de licences sont classées dans un ordre croissant de capacités allant de la version standard à la version Premium XL. En général, l'option de licence que vous choisissez vous accorde les capacités de ce niveau et de tous les niveaux inférieurs. Par exemple, le niveau Premium fournit les capacités de Premium et de Standard.



== Offres de licences de plateforme

Trois offres de licences de plateforme sont disponibles.



=== Standard

L'offre standard offre les fonctionnalités suivantes :

* Type d'instance de petite taille uniquement
* Disques durs (HDD) uniquement
* Contrôleur RAID matériel local uniquement
* VNAS




=== Premium

L'offre Premium offre inclut les fonctionnalités suivantes :

* Type d'instance petit ou moyen
* Disques durs ou SSD
* Contrôleur RAID local ou RAID logiciel
* VNAS
* Les SDS dans MetroCluster




=== XL haut de gamme

L'offre XL haut de gamme offre les fonctionnalités suivantes :

* Type d'instance petit, moyen ou grand
* HDD, SSD ou disques NVMe
* Contrôleur RAID local ou RAID logiciel
* VNAS
* Les SDS dans MetroCluster



NOTE: L'utilisation du type d'instance volumineuse n'est pas prise en charge sur une machine virtuelle basée sur le noyau (KVM).



== Comparez les offres de licences de plate-forme prises en charge par le matériel

Les offres de licences XL standard, Premium et Premium prennent en charge un large éventail de matériels et de logiciels. Pour obtenir des informations à jour sur les versions matérielles et logicielles, reportez-vous au link:https://mysupport.netapp.com/matrix/["Matrice d'interopérabilité"^].

[role="tabbed-block"]
====
.Élément de base
--
[cols="5"30"]
|===


2+| Type d'élément de base 3+| Description 


2+| Protocoles hôtes 3+| NFS, SMB/CIFS, iSCSI et NVMe over TCP 


2+| Options de déploiement 3+| Cluster à un seul nœud, deux nœuds (paire haute disponibilité), cluster à quatre, six ou huit nœuds 


2+| Capacité prise en charge (par nœud) 3+| Jusqu'à 400 To de données brutes (ESXi et KVM) 
|===
--
.Sous-jacent
--
[cols="5"30"]
|===


2+| Type de matériel 3+| Description 


2+| Taille de l'instance | Petit | Moyen | Grand 


2+| Famille CPU | Intel Xeon E5-26xx v3 (Haswell) ou ultérieur | Intel Xeon E5-26xx v3 (Haswell) ou ultérieur | Intel Xeon E5-26xx v3 (Haswell) ou ultérieur 


2+| Processeur/mémoire ONTAP Select | 4 processeurs virtuels (vCPU) / 16 Go de RAM | 8 vCPU/64 Go de RAM | 16 vCPU / 128 Go de RAM 


2+| Configuration minimale requise pour le processeur/la mémoire de l'hôte ^1^ | 6 cœurs/24 Go de RAM | 10 cœurs / 72 Go de RAM | 18 cœurs/136 Go de RAM 


2+| Réseau (par nœud) 3+| Au moins deux ports 1 GbE pour un cluster à un seul nœud au minimum quatre ports 1 GbE pour un cluster à deux nœuds (paire haute disponibilité) au minimum deux ports 10 GbE pour un cluster à quatre, six ou huit nœuds 
|===
^1^ utilise deux cœurs et 8 Go de RAM pour l’hyperviseur.

--
.Type de stockage
--
Le tableau suivant indique le type de licence minimum requis pour le stockage spécifié. 

[cols="5"30"]
|===


2+| Type de stockage 3+| Description 


2+| Type de licence | Standard | Premium | Pemium XL 


2+| Taille de l'instance | Petit | Petit et moyen | Petit, moyen et grand 


2+| DAS local avec contrôleur RAID matériel | 8 à 60 disques | 8 à 60 disques | 8 à 60 disques 


2+| HDD (SAS, NL-SAS ET SATA) | Sans objet | 4 à 60 disques | 4 à 60 disques 


2+| SSD (SAS) | Sans objet | 4 à 60 disques (SSD uniquement) | 4 à 60 disques (SSD uniquement) 


2+| DAS local avec RAID logiciel | Sans objet | Sans objet | 4 à 14 disques (NVMe uniquement) 


2+| Tableaux externes ^1^ 3+| Les datastores hébergés sur baies externes sont connectés via FC, FCoE, iSCSI et NFS (NFS n'est pas pris en charge pour KVM). Ces datastores assurent haute disponibilité et résilience. 
|===
^1^ la prise en charge du protocole des baies externes reflète la connectivité du stockage en réseau.

--
.Logiciels
--
[cols="5"30"]
|===


2+| Type de logiciel 3+| Description 


2+| Hyperviseur (VMware) 3+| VMware vSphere 8.0GA et mises à jour 1 à 3 VMware vSphere 7.0GA et mises à jour 1 à 3C 


2+| Hyperviseur (KVM) 3+| Red Hat Enterprise Linux 64 bits (KVM) 9.6, 9.5, 9.4, 9.3, 9.2, 9.1, 9.0, 8.8, 8.7 et 8.6 Rocky Linux (KVM) 9.6 9.5, 9.4, 9.3, 9.2, 9.1, 9.0, 8.9, 8.8, 8.7 et 8.6 


2+| Logiciel de gestion 3+| Suite de gestion NetApp Active IQ Unified Manager ONTAP Select Deploy Utility SnapCenter (en option) 
|===
--
====
.Informations associées
link:concept_lic_production.html["En savoir plus sur les types de licence de niveau de capacité et de pool de capacité"].
