---
sidebar: sidebar 
permalink: concept_lic_cp_serial_number.html 
keywords: license, licensing, Capacity Pools, node serial numbers 
summary: Avec le modèle de licence Capacity tiers, le numéro de série du nœud à neuf chiffres est identique au numéro de série de licence attribué au nœud. Cependant, le format des numéros de série attribués aux nœuds utilisant le modèle de licence des pools de capacité est différent. 
---
= Numéros de série des nœuds pour le modèle de licence ONTAP Select Capacity pools
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Avec le modèle de licence Capacity tiers, le numéro de série du nœud à neuf chiffres est identique au numéro de série de licence attribué au nœud. Cependant, le format des numéros de série attribués aux nœuds utilisant le modèle de licence des pools de capacité est différent.

Le numéro de série d'un nœud utilisant une licence Capacity pools a le format suivant :

`999 ppppppppp nnnnnnnn`


NOTE: Des espaces ont été ajoutés pour plus de clarté, mais ne font pas partie du numéro de série réel.

Chaque section du numéro de série du nœud est décrite dans le tableau suivant, de gauche à droite.

[cols="15,85"]
|===
| Section | Description 


| « 999 » | Valeur à trois chiffres constante réservée par NetApp. 


| ppppp | Numéro de série de licence variable à neuf chiffres attribué au pool de capacité par NetApp 


| nnnnnnnn | Valeur variable à huit chiffres générée par le Gestionnaire de licences pour chaque nœud utilisant le pool de capacité 
|===

NOTE: Attention : lors de l'ouverture d'un dossier avec prise en charge NetApp impliquant un nœud qui utilise une licence de pool de capacité, vous ne pouvez pas fournir le numéro de série de nœud complet à vingt chiffres. Vous devez plutôt fournir le numéro de série de la licence de pool de capacité à neuf chiffres. Vous pouvez obtenir le numéro de série de la licence à partir du numéro de série de nœud, comme indiqué ci-dessus. Ignorez les trois premiers chiffres du numéro de série du nœud ('999') et extrayez les neuf chiffres suivants (ppppp).
