---
sidebar: sidebar 
permalink: concept_lic_cp_operation.html 
keywords: license, licensing, Capacity Pools, operation details 
summary: Le modèle de licence des pools de capacité est différent du modèle des tiers de capacité. Au lieu de dédier la capacité de stockage à chaque nœud individuel, la capacité de stockage est allouée à un pool et partagée entre plusieurs nœuds. Des composants et processus supplémentaires ont été créés pour prendre en charge le modèle de pools de capacité. 
---
= Détails opérationnels du modèle de licence des pools de capacité ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le modèle de licence des pools de capacité est différent du modèle des tiers de capacité. Au lieu de dédier la capacité de stockage à chaque nœud individuel, la capacité de stockage est allouée à un pool et partagée entre plusieurs nœuds. Des composants et processus supplémentaires ont été créés pour prendre en charge le modèle de pools de capacité.



== Gestionnaire de licences

Le Gestionnaire de licences s'exécute comme un processus distinct au sein de chaque instance de l'utilitaire d'administration de déploiement. Certaines des fonctions fournies par LM incluent :

* Générez un numéro de série à vingt chiffres unique pour chaque nœud en fonction du numéro de série de licence du pool de capacité
* Créez des baux de capacité à partir des pools de capacité partagée en fonction des demandes des nœuds ONTAP Select
* Génération de rapports sur l'utilisation du pool via l'interface utilisateur de déploiement




== Caractéristiques du bail

Le stockage alloué à chaque agrégat de données au niveau d'un nœud utilisant une licence Capacity Pool doit être associé à un bail. Le nœud demande un bail de stockage et, si la capacité est disponible, le Gestionnaire de licences répond par un bail. Chaque bail comporte les attributs explicites ou implicites suivants :

* Gestionnaire de licences
+
Chaque nœud ONTAP Select est associé à une instance de License Manager

* Pool de capacité
+
Chaque nœud ONTAP Select est associé à un pool de capacité

* Allocation de stockage
+
Une valeur de capacité spécifique est attribuée dans le bail

* Date et heure d'expiration
+
Les baux ont une durée comprise entre une heure et sept jours selon la configuration de l'utilisateur.





== ID de verrouillage de licence

Chaque instance du Gestionnaire de licences, et donc chaque instance d'utilitaire de déploiement correspondante, est identifiée par un numéro unique de 128 bits. Ce nombre est combiné au numéro de série de la licence Capacity Pool à neuf chiffres pour verrouiller le pool à une instance de License Manager spécifique (qui est en fait une instance de déploiement). Vous devez fournir les deux valeurs au niveau du site de support NetApp dans le cadre de la génération du fichier de licence NetApp (NLF).

Vous pouvez déterminer l'ID de verrouillage de licence de votre instance de déploiement à l'aide de l'interface utilisateur Web de la manière suivante :

* Page de démarrage
+
Deploy affiche cette page lors de votre première connexion. Vous pouvez également ouvrir le menu déroulant en haut à droite de la page et sélectionner *Getting Started* pour afficher cette page. Le LLID s'affiche dans la section Ajouter des licences.

+
Sélectionnez l'onglet *Administration* en haut de la page, puis sélectionnez *Systems* et *Settings*.





== Opérations de location de base

Un nœud ONTAP Select doit localiser ou demander un bail de capacité valide chaque fois qu'un agrégat de données est créé, étendu ou modifié. Vous pouvez utiliser un bail obtenu lors d'une demande précédente qui est toujours valide, ou vous pouvez demander un nouveau bail si nécessaire. Les étapes suivantes sont effectuées par le nœud ONTAP Select pour localiser un bail de Capacity Pool :

. Si un bail existant est situé au niveau du nœud, il est utilisé tant que tous les éléments suivants sont vrais :
+
** Le bail n'a pas expiré
** La demande de stockage de l'agrégat ne dépasse pas la capacité de location


. Si un bail existant ne peut pas être localisé, le nœud demande un nouveau bail auprès du Gestionnaire de licences.




== Renvoyer la capacité de stockage vers un pool de capacité

La capacité de stockage est allouée à partir d'un pool de capacité selon les besoins et chaque nouvelle demande peut réduire le stockage disponible dans le pool. La capacité de stockage est renvoyée dans le pool dans plusieurs situations, notamment :

* La location d'un agrégat de données expire et n'est pas renouvelée par le nœud
* L'agrégat de données est supprimé



NOTE: Si une machine virtuelle ONTAP Select est supprimée, les baux actifs restent en vigueur jusqu'à leur expiration. Dans ce cas, la capacité est renvoyée dans le pool.
