---
sidebar: sidebar 
permalink: concept_nw_internal_external.html 
keywords: ontap select, internal network, external network 
summary: Caractéristiques des réseaux ONTAP Select internes et externes. 
---
= Réseaux internes et externes ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Caractéristiques des réseaux internes et externes ONTAP Select.



== Réseau interne ONTAP Select

Le réseau interne ONTAP Select, présent uniquement dans la variante multi-nœuds du produit, est responsable de fournir au cluster ONTAP Select la communication de cluster, l’interconnexion haute disponibilité et les services de réplication synchrone. Ce réseau comprend les ports et interfaces suivants :

* *E0c, e0d.* Hosting cluster network LIFs
* *E0e.* Hébergement de la LIF RSM
* *E0f.* Hébergement de la LIF d'interconnexion haute disponibilité


Le débit et la latence de ce réseau sont essentiels pour déterminer les performances et la résilience du cluster ONTAP Select. Une isolation réseau est nécessaire pour assurer la sécurité des clusters et garantir que les interfaces système restent séparées du reste du trafic réseau. Par conséquent, ce réseau doit être utilisé exclusivement par le cluster ONTAP Select.


NOTE: L'utilisation du réseau interne Select pour le trafic autre que le trafic Select cluster, tel que le trafic d'application ou de gestion, n'est pas prise en charge. Il ne peut y avoir aucun autre VM ou hôte sur le VLAN interne de ONTAP.

Les paquets réseau traversant le réseau interne doivent se trouver sur un réseau VLAN dédié de couche 2. Pour ce faire, vous pouvez effectuer l'une des tâches suivantes :

* Affectation d'un groupe de ports Tagged VLAN aux NIC virtuels internes (e0c à e0f) (mode VST)
* Utilisation du VLAN natif fourni par le commutateur en amont où le VLAN natif n'est pas utilisé pour un autre trafic (affecter un groupe de ports sans ID VLAN, c'est-à-dire le mode est)


Dans tous les cas, le balisage VLAN pour le trafic réseau interne est effectué en dehors du VM ONTAP Select.


NOTE: Seuls les vSwitches standard et distribués ESXi sont pris en charge. Les autres commutateurs virtuels ou la connectivité directe entre hôtes ESXi ne sont pas pris en charge. Le réseau interne doit être entièrement ouvert ; les NAT ou les pare-feu ne sont pas pris en charge.

Au sein d'un cluster ONTAP Select , le trafic interne et le trafic externe sont séparés par des objets réseau virtuels de couche 2, appelés groupes de ports. L'attribution correcte des groupes de ports aux vSwitch est extrêmement importante, en particulier pour le réseau interne, qui est responsable de la fourniture des services de cluster, d'interconnexion HA et de réplication en miroir. Une bande passante réseau insuffisante vers ces ports peut entraîner une dégradation des performances, voire affecter la stabilité du nœud du cluster.  Par conséquent, les clusters à quatre, six, huit, dix et douze nœuds nécessitent que le réseau interne ONTAP Select utilise une connectivité de 10 Gb ; les cartes réseau de 1 Gb ne sont pas prises en charge.  Des compromis peuvent toutefois être faits au niveau du réseau externe, car la limitation du flux de données entrantes vers un cluster ONTAP Select n'affecte pas sa capacité à fonctionner de manière fiable.

Un cluster à deux nœuds peut utiliser quatre ports 1 Gbit pour le trafic interne ou un seul port 10 Gbit à la place des deux ports 10 Gbit/s requis par le cluster à quatre nœuds. Dans un environnement dans lequel les conditions empêchent le serveur d'utiliser quatre cartes NIC de 10 Gbit/s, deux cartes NIC de 10 Gbit/s peuvent être utilisées pour le réseau interne et deux cartes réseau de 1 Gbit/s peuvent être utilisées pour le réseau ONTAP externe.



=== Validation et dépannage du réseau interne

Le réseau interne d'un cluster multi-nœuds peut être validé à l'aide de la fonctionnalité de vérification de la connectivité réseau. Cette fonction peut être appelée depuis l'interface de ligne de commande de déploiement en exécutant la commande  `network connectivity-check start`.

Lancer la commande suivante pour afficher les valeurs de sortie du test :

[listing]
----
network connectivity-check show --run-id X (X is a number)
----
Cet outil est uniquement utile pour le dépannage du réseau interne d'un cluster Select multinœud. L'outil ne doit pas être utilisé pour le dépannage des clusters mononœud (y compris les configurations vNAS), la connectivité entre ONTAP Deploy et ONTAP Select, ni les problèmes de connectivité côté client.

L'assistant de création de cluster (faisant partie de l'interface utilisateur ONTAP Deploy) inclut le vérificateur de réseau interne comme étape optionnelle disponible lors de la création de clusters multi-nœuds. Étant donné le rôle important que le réseau interne joue dans les clusters multi-nœuds, faire de cette étape une partie du flux de travail de création de cluster améliore le taux de réussite des opérations de création de cluster.

Depuis ONTAP Deploy 2.10, la taille de MTU utilisée par le réseau interne peut être définie entre 7,500 et 9,000. Le vérificateur de connectivité réseau peut également être utilisé pour tester la taille de MTU entre 7,500 et 9,000. La valeur MTU par défaut est définie sur la valeur du commutateur réseau virtuel. Cette valeur par défaut doit être remplacée par une valeur plus petite si une superposition réseau comme VXLAN est présente dans l'environnement.



== Réseau externe ONTAP Select

Le réseau externe ONTAP Select est responsable de toutes les communications sortantes du cluster et, par conséquent, est présent dans les configurations à nœud unique et à nœuds multiples. Bien que ce réseau ne soit pas soumis aux mêmes exigences de débit strictes que le réseau interne, l'administrateur doit veiller à ne pas créer de goulots d'étranglement réseau entre le client et la machine virtuelle ONTAP, car des problèmes de performance pourraient être à tort considérés comme des problèmes ONTAP Select.


NOTE: D'une manière similaire au trafic interne, le trafic externe peut être balisé au niveau de la couche vSwitch (VST) et au niveau de la couche est (commutateur externe). De plus, le trafic externe peut être balisé par la machine virtuelle ONTAP Select elle-même dans un processus appelé VGT. Voir la section link:concept_nw_data_mgmt_separation.html["Séparation du trafic de données et de gestion"] pour plus d'informations.

Le tableau suivant met en évidence les principales différences entre les réseaux internes et externes de ONTAP Select.

*Référence rapide de réseau interne et externe*

[cols="3*"]
|===
| Description | Réseau interne | Réseau externe 


| Services réseau | Cluster HA/IC RAID SyncMirror (RSM) | Gestion des données intercluster (SnapMirror et SnapVault) 


| Isolement du réseau | Obligatoire | Facultatif 


| Taille de trame (MTU) | 7,500 à 9,000 | 1,500 (par défaut) 9,000 (pris en charge) 


| Attribution d'adresse IP | Auto-générée | Défini par l'utilisateur 


| Prise en charge de DHCP | Non | Non 
|===


=== Regroupement de cartes réseau

Pour vous assurer que les réseaux internes et externes possèdent à la fois les caractéristiques de bande passante et de résilience requises pour assurer des performances et une tolérance aux pannes élevées, il est recommandé d'utiliser le regroupement des adaptateurs réseau physiques. Les configurations en cluster à 2 nœuds avec une seule liaison 10 Gb sont prises en charge. Cependant, la meilleure pratique recommandée par NetApp consiste à utiliser le regroupement des cartes réseau sur les réseaux internes et externes du cluster ONTAP Select.



=== Génération d'adresses MAC

Les adresses MAC attribuées à tous les ports réseau ONTAP Select sont générées automatiquement par l'utilitaire de déploiement inclus. La fonction de mise en service utilise un identifiant unique propre à la plateforme propre à l'entreprise (OUI) spécifique à NetApp pour s'assurer qu'il n'y a aucun conflit avec les systèmes FAS. Une copie de cette adresse est ensuite stockée dans une base de données interne au sein de la VM d'installation de ONTAP Select (ONTAP Deploy), afin d'empêcher une réattribution accidentelle lors de futurs déploiements de nœuds. L'administrateur ne doit en aucun cas modifier l'adresse MAC attribuée à un port réseau.
