---
sidebar: sidebar 
permalink: concept_api_versions.html 
keywords: rest api, deploy rest api, rest, version, versioning 
summary: 'Un numéro de version est attribué à l"API REST incluse dans ONTAP Select Deploy. Le numéro de version de l"API est indépendant du numéro de version de déploiement. Il est important de connaître la version d"API incluse dans votre version de déploiement et d"identifier en quoi cela pourrait affecter votre utilisation de l"API.' 
---
= Déploiement des versions d'API
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Un numéro de version est attribué à l'API REST incluse dans ONTAP Select Deploy. Le numéro de version de l'API est indépendant du numéro de version de déploiement. Il est important de connaître la version d'API incluse dans votre version de déploiement et d'identifier en quoi cela pourrait affecter votre utilisation de l'API.

La version actuelle de l'utilitaire d'administration Deploy inclut la version 3 de l'API REST. Les anciennes versions de l'utilitaire Deploy comprennent les versions d'API suivantes :

Déploiement 2.8 et versions ultérieures:: ONTAP Select Deploy 2.8, ainsi que que que toutes les versions ultérieures incluent la version 3 de l'API REST.
Déployer les versions 2.7.2 et antérieures:: ONTAP Select Deploy 2.7.2. Toutes les versions antérieures comprennent la version 2 de l'API REST.



NOTE: Les versions 2 et 3 de l'API REST ne sont pas compatibles. Si vous effectuez une mise à niveau vers le déploiement de la version 2.8 ou ultérieure à partir d'une version antérieure incluant la version 2 de l'API, vous devez mettre à jour tout code existant qui accède directement à l'API ainsi que tous les scripts à l'aide de l'interface de ligne de commande.
