---
sidebar: sidebar 
permalink: concept_api_before_python.html 
keywords: rest api, deploy rest api, rest, python, before you begin 
summary: 'Vous devez préparer l"environnement avant d"exécuter les exemples de scripts Python.' 
---
= Avant d'accéder à l'API à l'aide de Python
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous devez préparer l'environnement avant d'exécuter les exemples de scripts Python.

Avant d'exécuter les scripts Python, assurez-vous que l'environnement est correctement configuré :

* La dernière version applicable de Python2 doit être installée. Les codes échantillons ont été testés à l'aide de Python2. Ils devraient également être portables à Python3, mais n'ont pas été testés pour la compatibilité.
* Les requêtes et les bibliothèques urllib3 doivent être installées. Vous pouvez utiliser pip ou un autre outil de gestion Python, selon les besoins de votre environnement.
* Le poste de travail client sur lequel s'exécutent les scripts doit disposer d'un accès réseau à la machine virtuelle ONTAP Select Deploy.


En outre, vous devez disposer des informations suivantes :

* Adresse IP de la machine virtuelle déployée
* Nom d'utilisateur et mot de passe d'un compte administrateur de déploiement

