---
sidebar: sidebar 
permalink: index.html 
summary: Bienvenue sur le portail de documentation de ONTAP Select. 
---
= Documentation ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp ONTAP Select est une appliance de stockage Software-defined que vous pouvez déployer sur de nombreux serveurs matériels génériques exécutant l'hyperviseur VMware ESXi. Elle vous apporte l'agilité dont vous avez besoin pour concevoir une infrastructure de cloud privé flexible et évolutive.



== Découvrez les nouveautés

* link:reference_new_ots.html["Nouveautés de cette version"]


[NOTE]
====
* Depuis la version ONTAP Select 9.10.1, il n'est plus possible de déployer un nouveau cluster sur l'hyperviseur KVM.
* Depuis ONTAP Select 9.11.1, toutes les fonctionnalités de gestion ne sont plus disponibles pour les clusters et hôtes KVM existants, à l'exception des fonctions de mise hors ligne et de suppression.


====


== Accédez à la documentation du produit

ONTAP Select 9.12.1 peut être déployé sur VMware ESXi. Ce site contient de la documentation sur ONTAP Select 9.12.1, 9.11.1, 9.10.1, 9.9.1, 9.8 et 9.7 fonctionnant sur VMware ESXi, ainsi que la documentation indépendante de l'hyperviseur (par exemple, l'API REST).

Vous trouverez les notes de mise à jour ainsi que la documentation relative à la version KVM du produit prise en charge par les versions précédentes sur le https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62293["Bibliothèque de produits ONTAP Select"^].



== Obtenez plus d'informations et entrez en contact avec vos pairs

* link:reference_additional_info.html["Où obtenir de l'aide et trouver plus d'informations"]

