---
settings:
  name: ONTAP Select
  harmony_integration: maestro
  internal:
    pdf_enabled: true
    lipi_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - version-number: 9.18.1
    url: "/ontap-select"
  - version-number: 9.17.1
    url: "/ontap-select-9171"
  - version-number: 9.16.1
    url: "/ontap-select-9161"
  - version-number: 9.15.1
    url: "/ontap-select-9151"
  - version-number: 9.14.1
    url: "/ontap-select-9141"
  langs: fr-fr,us-en,de-de,es-es,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: ONTAP Select 9.18.1
    url: "/index.html"
  - title: Notes de version
    entries:
    - title: Notes de version de ONTAP Select
      url: "/reference_release_notes.html"
    - title: Quoi de neuf
      url: "/reference_new_ots.html"
  - title: Concepts
    entries:
    - title: Découvrez ONTAP Select
      url: "/concept_ots_overview.html"
    - title: Déploiement de ONTAP Select
      url: "/concept_ots_deploy.html"
    - title: Cas d'utilisation professionnelle
      entries:
      - title: Besoins professionnels et scénarios d'utilisation
        url: "/concept_usecase_overview.html"
      - title: Bureau distant et succursale
        url: "/concept_usecase_robo.html"
      - title: Le cloud privé et le data Center
        url: "/concept_usecase_private_cloud.html"
      - title: Protection des données et efficacité
        url: "/concept-data-protection-and-efficiency.html"
    - title: Terminologie
      url: "/concept_terminology.html"
  - title: Planification
    entries:
    - title: Flux de travail de déploiement
      url: "/concept_workflow_deploy.html"
    - title: ONTAP Select
      entries:
      - title: Exigences générales
        url: "/reference_plan_ots_general.html"
      - title: Hyperviseur et matériel
        url: "/reference_plan_ots_hardware.html"
      - title: Stockage et RAID
        url: "/reference_plan_ots_storage.html"
      - title: Exigences de stockage externe
        entries:
        - title: VMware ESXi
          url: "/reference_plan_ots_vnas.html"
        - title: KVM
          url: "/reference_plan_ots_kvm.html"
      - title: Mise en réseau
        url: "/reference_plan_ots_networking.html"
      - title: À deux nœuds sans commutateur
        url: "/reference_plan_ots_two_node.html"
      - title: Bureaux distants et succursales
        url: "/reference_plan_ots_robo.html"
      - title: Les SDS dans MetroCluster
        url: "/reference_plan_ots_mcc_sds.html"
      - title: VMware vCenter sur ESXi
        url: "/reference_plan_ots_vcenter.html"
    - title: Déploiement de ONTAP Select
      entries:
      - title: Exigences générales
        url: "/reference_plan_dep_general.html"
      - title: Un environnement VMware
        url: "/reference_plan_dep_vmware.html"
    - title: Et des meilleures pratiques
      url: "/reference_plan_best_practices.html"
  - title: Licence
    entries:
    - title: Options
      entries:
      - title: Licences d'évaluation
        url: "/concept_lic_evaluation.html"
      - title: Licences de production
        url: "/concept_lic_production.html"
      - title: Offres de licences de plateforme
        url: "/concept_lic_platforms.html"
    - title: Modèle de licence pour les pools de capacité
      entries:
      - title: Détails opérationnels
        url: "/concept_lic_cp_operation.html"
      - title: Numéros de série du nœud
        url: "/concept_lic_cp_serial_number.html"
      - title: Restrictions
        url: "/concept_lic_cp_restrictions.html"
      - title: Pools de capacité et tiers de capacité
        url: "/concept_lic_cp_compare_ct.html"
      - title: Récapitulatif des avantages
        url: "/concept_lic_cp_benefits.html"
    - title: Achat
      entries:
      - title: Flux de travail des licences
        url: "/concept_lic_workflow.html"
      - title: Tiers de capacité
        url: "/task_lic_acquire_ct.html"
      - title: Pools de capacité
        url: "/task_lic_acquire_cp.html"
    - title: Fonctionnalités ONTAP
      url: "/reference_lic_ontap_features.html"
  - title: Installer
    entries:
    - title: Liste de contrôle de pré-installation
      entries:
      - title: Checklist de préparation des hôtes
        entries:
        - title: Liste de contrôle de l'hôte KVM
          url: "/kvm-host-configuration-and-preparation-checklist.html"
        - title: Liste de contrôle de l'hôte ESXi
          url: "/esxi-host-configuration-and-preparation-checklist.html"
      - title: Déployer les informations requises de l'utilitaire
        url: "/reference_chk_deploy_req_info.html"
      - title: Informations requises pour ONTAP Select
        url: "/reference_chk_select_req_info.html"
      - title: Configuration de l'hôte NVMe
        url: "/task_chk_nvme_configure.html"
    - title: Installez ONTAP Select Deploy
      url: "/task_install_deploy.html"
    - title: Déployer un cluster
      url: "/task_deploy_cluster.html"
    - title: État initial du cluster
      url: "/reference_initial_state.html"
  - title: Administration
    entries:
    - title: Avant de commencer
      url: "/concept_adm_before.html"
    - title: Mettre à niveau les nœuds
      url: "/concept_adm_upgrading_nodes.html"
    - title: Diagnostics et support
      url: "/task_adm_support.html"
    - title: Secure ONTAP Select
      url: "/task_adm_security.html"
    - title: Vérifiez la connectivité réseau
      url: "/task_adm_connectivity.html"
    - title: Administrer les services de médiateur
      url: "/task_adm_mediators.html"
    - title: Clusters
      entries:
      - title: Clusters ONTAP Select
        url: "/task_adm_clusters.html"
      - title: Développer ou réduire un cluster
        url: "/task_cluster_expansion_contraction.html"
    - title: Nœuds et hôtes
      entries:
      - title: Accéder à la console vidéo de la machine virtuelle
        url: "/task_adm_video_console.html"
      - title: Redimensionner les nœuds du cluster
        url: "/task_adm_resize.html"
      - title: Remplacez les disques RAID logiciels défectueux
        url: "/task_adm_replace_drives_swraid.html"
      - title: Mise à niveau vers VMFS6
        url: "/task_adm_upgrade_vmfs6.html"
    - title: Licences
      url: "/task_adm_licenses.html"
  - title: Plongée en profondeur
    entries:
    - title: Stockage
      entries:
      - title: Concepts et caractéristiques généraux
        url: "/concept_stor_concepts_chars.html"
      - title: Services RAID matériels pour stockage local
        url: "/concept_stor_hwraid_local.html"
      - title: Services RAID logiciels pour le stockage local
        url: "/concept_stor_swraid_local.html"
      - title: Configurations de baies externes et VSAN
        url: "/concept_stor_vsan_external.html"
      - title: Augmenter la capacité de stockage
        url: "/concept_stor_capacity_inc.html"
      - title: Prise en charge de l'efficacité du stockage
        url: "/concept_stor_eff_support.html"
    - title: Mise en réseau
      entries:
      - title: Concepts et caractéristiques généraux
        url: "/concept_nw_concepts_chars.html"
      - title: Configuration à un ou plusieurs nœuds
        url: "/concept_nw_single_multi_node.html"
      - title: Réseaux internes et externes
        url: "/concept_nw_internal_external.html"
      - title: Configurations compatibles
        url: "/concept_nw_supported_configs.html"
      - title: Configuration VMware vSphere vSwitch
        url: "/concept_nw_vsphere_vswitch_config.html"
      - title: Configuration physique des commutateurs
        url: "/concept_nw_physical_switch_config.html"
      - title: Séparation des données et des fonctions de gestion
        url: "/concept_nw_data_mgmt_separation.html"
    - title: Architecture haute disponibilité
      entries:
      - title: Configuration DE L'INFRASTRUCTURE HA
        url: "/concept_ha_config.html"
      - title: Réplication synchrone et agrégats en miroir
        url: "/concept_ha_mirroring.html"
      - title: Autres fonctions de haute disponibilité
        url: "/concept_ha_other.html"
    - title: Performance
      entries:
      - title: Présentation des performances
        url: "/concept_perf_general.html"
      - title: Performances ONTAP Select 9.6
        url: "/concept_perf_premium_ha_direct_ssd_96.html"
  - title: Automatisez avec LE REPOS
    entries:
    - title: Concepts
      entries:
      - title: Services web REST
        url: "/concept_api_rest.html"
      - title: Accédez à l'API de déploiement
        url: "/concept_api_how_access.html"
      - title: Fonctionnement de base
        url: "/concept_api_operation.html"
      - title: Transaction de demande et de réponse
        url: "/concept_api_transaction.html"
      - title: Traitement asynchrone
        url: "/concept_api_async_proc.html"
    - title: Accès à l'aide d'un navigateur
      entries:
      - title: Avant de commencer
        url: "/concept_api_before_browser.html"
      - title: Accédez à la page doc
        url: "/task_api_access_doc_page.html"
      - title: Comprendre un appel d'API
        url: "/task_api_understanding_call.html"
    - title: Processus de flux de travail
      entries:
      - title: Avant de commencer
        url: "/concept_api_before_workflows.html"
      - title: Workflow 1 Créez un cluster
        url: "/reference_api_workflow01.html"
    - title: Accès avec Python
      entries:
      - title: Avant de commencer
        url: "/concept_api_before_python.html"
      - title: Comprendre les scripts
        url: "/concept_api_understanding_scripts.html"
    - title: Exemples de code Python
      entries:
      - title: Création d'un cluster
        url: "/reference_api_script_cc.html"
      - title: JSON pour créer un cluster
        url: "/reference_api_json_cc.html"
      - title: Ajouter une licence de nœud
        url: "/reference_api_script_anl.html"
      - title: Supprime un cluster
        url: "/reference_api_script_dc.html"
      - title: Module de support commun
        url: "/reference_api_script_common.html"
      - title: Redimensionner les nœuds du cluster
        url: "/reference_api_script_resize.html"
  - title: Utiliser l'interface de ligne de commande
    entries:
    - title: Connectez-vous à l'aide de SSH
      url: "/task_cli_signing_in.html"
    - title: Déployer un cluster
      url: "/task_cli_deploy_cluster.html"
    - title: Sécurité
      url: "/task_cli_security.html"
    - title: Connectivité réseau
      url: "/task_cli_connectivity.html"
    - title: Clusters
      url: "/task_cli_clusters.html"
    - title: Nœuds et hôtes
      entries:
      - title: Mise à niveau d'ESXi
        url: "/cli-upgrade-esxi.html"
      - title: Modifier un serveur de gestion des hôtes
        url: "/reference_host_modify_command.html"
    - title: Utilitaire de déploiement
      entries:
      - title: Mettre à niveau une instance de déploiement
        url: "/task_cli_upgrade_deploy.html"
      - title: Migrer une instance de déploiement
        url: "/task_cli_migrate_deploy.html"
      - title: Ajouter des images ONTAP Select
        url: "/task_cli_deploy_image_add.html"
      - title: Supprimer les images ONTAP Select
        url: "/task_cli_deploy_image_remove.html"
      - title: Restaurez le déploiement pour un cluster à deux nœuds
        url: "/task_cli_deploy_recover_two_node.html"
  - title: Déployez une instance d'évaluation de 90 jours d'un cluster
    url: "/deploy-evaluation-ontap-select-ovf-template.html"
  - title: FAQ
    url: "/reference_faq.html"
  - title: Mentions légales
    url: "/legal-notices.html"
