---
sidebar: sidebar 
permalink: reference_plan_ots_hardware.html 
keywords: plan, planning, vmware, hardware, hardware requirements 
summary: 'Il existe plusieurs problèmes matériels à prendre en compte et à planifier liés à l"environnement VMware.' 
---
= Considérations relatives à l'hyperviseur et au matériel VMware ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Il existe plusieurs problèmes matériels à prendre en compte et à planifier liés à l'environnement VMware.



== Exigences liées à l'hyperviseur

Il existe plusieurs exigences relatives à l'hyperviseur dans lequel ONTAP Select s'exécute.


NOTE: Vous devriez revoir lelink:reference_release_notes.html["Notes de version de ONTAP Select"] pour toute autre restriction ou limitation connue.



=== Licences VMware

Pour déployer un cluster ONTAP Select, votre entreprise doit disposer d'une licence VMware vSphere valide pour les hôtes de l'hyperviseur où ONTAP Select s'exécute. Vous devez utiliser les licences adaptées à votre déploiement.



=== Compatibilité logicielle

Vous pouvez déployer ONTAP Select sur les hyperviseurs KVM et ESXi.

[role="tabbed-block"]
====
.KVM
--
ONTAP Select prend en charge les versions d'hyperviseur KVM suivantes :

* KVM sur Red Hat Enterprise Linux (RHEL) 10.0, 9.6, 9.5, 9.4, 9.2, 9.1, 9.0, 8.8, 8.7 et 8.6
* KVM sur Rocky Linux 10.0, 9.6, 9.5, 9.4, 9.3, 9.2, 9.1, 9.0, 8.9, 8.8, 8.7 et 8.6


[NOTE]
====
Il existe des limitations de flux de travail RAID logiciel pour les hyperviseurs KVM sur les hôtes RHEL 10.0 et Rocky Linux 10.0. Pour plus d'informations, consultez les articles suivants de la base de connaissances :

* link:https://kb.netapp.com/on-prem/ontap/ontap-select/Select-Issues/CDEPLOY-4020["CDEPLOY-4020 : ONTAP Select Deploy : Message d’avertissement lors de la création du cluster HWR sous RHEL 10 et ROCKY 10"^]
* link:https://kb.netapp.com/on-prem/ontap/ontap-select/Select-Issues/CDEPLOY-4025["CDEPLOY-4025 : ONTAP Select DeployGUI : Les pools de stockage et les disques de stockage ne sont pas visibles pour SWR sur la page de création de cluster sur les hôtes RHEL10/Rocky 10"^]


====
--
.VMware ESXi
--
ONTAP Select prend en charge les versions d'hyperviseur ESXi suivantes :

* VMware ESXi 9.0
* VMware ESXi 8.0 U3
* VMware ESXi 8.0 U2
* VMware ESXi 8.0 U1 (build 21495797)
* VMware ESXi 8.0 GA (build 20513097)



NOTE: NetApp prend en charge ONTAP Select sur les versions identifiées de ESXi tant que VMware continue également à prendre en charge les mêmes versions.


NOTE: ESXi 7.0 GA a atteint la fin de sa disponibilité.  Si vous disposez de clusters ONTAP Select avec cette version, vous devez effectuer une mise à niveau vers les versions prises en charge conformément à la documentation. https://mysupport.netapp.com/matrix["Matrice d'interopérabilité (IMT)"^] .

--
====


=== VMware vCenter et les hôtes ESXi autonomes

Si un hôte d'hyperviseur ESXi est géré par un serveur vCenter, vous devez enregistrer l'hôte dans l'utilitaire d'administration de déploiement à l'aide des informations d'identification vCenter. Vous ne pouvez pas enregistrer l'hôte en tant qu'hôte autonome à l'aide des informations d'identification VMware ESXi.



== Configuration matérielle principale requise

L'hôte de l'hyperviseur physique dans lequel vous déployez ONTAP Select doit respecter plusieurs exigences matérielles. Vous pouvez choisir n'importe quelle plateforme pour l'hôte de l'hyperviseur, tant qu'elle respecte les exigences matérielles minimales. Les fournisseurs suivants proposent des plateformes matérielles prises en charge : Cisco, Dell, HP, Fujitsu, Lenovo, Et Supermicro.


NOTE: À partir d' ONTAP Select 9.9.1, seuls les modèles de processeur basés sur Intel Xeon Sandy Bridge ou ultérieurs sont pris en charge.

Pour plus d'informations, reportez-vous au https://mysupport.netapp.com/matrix["Matrice d'interopérabilité, fenêtre=_blank"].



=== Configuration matérielle de base

Il existe plusieurs exigences matérielles courantes qui s'appliquent à toutes les plateformes, indépendamment du type d'instance de nœud ou de l'offre de licence.

.Processeur
Les microprocesseurs pris en charge incluent les processeurs Intel Xeon pour serveur, voir link:https://www.intel.com/content/www/us/en/products/processors/xeon/view-all.html?Processor+Type=1003["Processeurs Intel Xeon,window=_blank"] pour plus d'informations.


NOTE: Les processeurs AMD (Advanced micro Devices) ne sont pas pris en charge par ONTAP Select.

.Configuration Ethernet
Il existe plusieurs configurations Ethernet prises en charge en fonction de la taille du cluster.

[cols="2,3,3"]
|===
| Taille du cluster | Configuration minimale requise | Exigences recommandées 


| Cluster à un seul nœud | 2 x 1 GbE | 2 x 10 GbE 


| Cluster à deux nœuds ou MetroCluster SDS | 4 x 1 GbE ou 1 x 10 GbE | 2 x 10 GbE 


| cluster de quatre, six, huit, dix ou douze nœuds | 2 x 10 GbE | 4 x 10 GbE ou 2 x 25 GbE 
|===


=== Configuration matérielle supplémentaire en fonction du type d'instance

Il y a plusieurs autres exigences matérielles en fonction du type d'instance de nœud.

Reportez-vous à la section link:concept_lic_platforms.html["Comprendre les offres de licences de plate-forme"] pour en savoir plus.

[cols="a1,a2,a2,a2"]
|===
| Taille du nœud | cœurs de processeur | Mémoire | Offre de licence de plateforme requise 


| Petit | Six cœurs physiques ou plus, dont quatre réservés à ONTAP Select | 24 Go ou plus, avec 16 Go réservés à ONTAP Select | Standard, premium ou premium XL 


| Moyen | Dix cœurs physiques ou plus, dont huit réservés à ONTAP Select | 72 Go ou plus, avec 64 Go réservés à ONTAP Select | Premium ou premium XL 


| Grand | Dix-huit cœurs physiques ou plus, dont seize réservés à ONTAP Select | 136 Go ou plus, avec 128 Go réservés à ONTAP Select | XL haut de gamme 
|===

NOTE: Il existe des besoins supplémentaires en termes de disque selon les licences de la plate-forme. Voir link:reference_plan_ots_storage.html["Stockage et RAID"] pour en savoir plus.
