---
sidebar: sidebar 
permalink: reference_plan_ots_storage.html 
keywords: plan, planning, storage, software raid, hardware raid, raid, nvme 
summary: Vous devez tenir compte de plusieurs problèmes de planification liés au stockage hôte ONTAP Select. 
---
= Considérations relatives au stockage ONTAP Select et à la technologie RAID
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous devez tenir compte de plusieurs problèmes de planification liés au stockage hôte ONTAP Select.


NOTE: Les informations relatives à la prise en charge du stockage externe sont décrites dans le link:reference_plan_ots_vnas.html["Exigences ONTAP Select vNAS"].



== Configuration matérielle du contrôleur RAID

Le contrôleur RAID sur l'hôte de l'hyperviseur dans lequel vous déployez ONTAP Select doit répondre à plusieurs exigences.


NOTE: Un hôte sur lequel ONTAP Select s'exécute nécessite des disques physiques locaux lors de l'utilisation d'un contrôleur RAID matériel ou de la fonctionnalité RAID logicielle fournie avec ONTAP Select. Si vous utilisez la solution ONTAP Select vNAS pour accéder au stockage externe, aucun contrôleur RAID local et la fonctionnalité RAID logicielle ne sont pas utilisés.

La configuration minimale requise pour le contrôleur RAID est la suivante :

* Débit de 12 Gbit/s.
* 512 Mo de mémoire cache interne alimentée par batterie ou Flash (SuperCap)
* Configuré en mode de réinscription :
+
** Activer le mode retour arrière pour « écrire » (si pris en charge)
** Activation de la stratégie « toujours en lecture anticipée » (si elle est prise en charge)


* Tous les disques locaux derrière le contrôleur RAID doivent être configurés en tant que groupe RAID unique ; plusieurs contrôleurs RAID peuvent être utilisés si nécessaire :
+
** Désactivez le cache de disque local pour le groupe RAID. Il est fondamental pour préserver l'intégrité des données.


* La configuration des LUN doit être effectuée selon les consignes suivantes :
+
** Si la taille du groupe RAID dépasse la taille de LUN maximale de 64 To, vous devez configurer plusieurs LUN de taille égale qui consomment tout le stockage disponible au sein du groupe RAID.
** Si la taille du groupe RAID est inférieure à la taille maximale de LUN de 64 To, vous devez configurer une LUN qui consomme tout le stockage disponible au sein du groupe RAID.






== Configuration RAID logicielle requise

Lors du déploiement d'un cluster ONTAP Select sur l'hyperviseur, vous pouvez utiliser la fonctionnalité RAID logicielle fournie par ONTAP Select à la place d'un contrôleur RAID matériel local. Vous devez connaître plusieurs conditions et restrictions avant de déployer un cluster à l'aide du logiciel RAID.



=== Exigences générales

L'environnement d'un déploiement RAID logiciel doit répondre aux principales exigences suivantes :

* VMware ESXi 7.0 GA (build 15843807) ou version ultérieure
* Licence ONTAP Select Premium ou version supérieure
* Disques SSD locaux uniquement
* Séparation des disques système de la racine et des agrégats de données
* Aucun contrôleur RAID matériel sur l'hôte



NOTE: Si un contrôleur RAID matériel est présent, voir link:concept_stor_concepts_chars.html["Stockage de plongée en profondeur"] pour connaître les exigences de configuration supplémentaires.



=== Exigences spécifiques à ESXi

* VMware ESXi 7.0 GA (build 15843807) ou version ultérieure
* VMware VMotion, HA et DRS ne sont pas pris en charge
* Vous ne pouvez pas utiliser le RAID logiciel avec un nœud qui a été mis à niveau à partir de ONTAP Select 9.4 ou d'une version antérieure. Dans ce cas, vous devez créer un nouveau nœud pour le déploiement RAID logiciel.




=== Configuration requise pour KVM

Il existe également des exigences spécifiques en matière de configuration des progiciels. Voir link:https://docs.netapp.com/us-en/ontap-select/reference_chk_host_prep.html#kvm-hypervisor["Préparation du serveur Linux"] pour en savoir plus.

Attentes des supports pour KVM:: Les périphériques de stockage flash SSD utilisés doivent répondre aux exigences supplémentaires suivantes :
+
--
* Les périphériques SSD doivent se présenter de manière précise et persistante à l'hôte Linux via les méthodes suivantes :
+
** # cat /sys/block/<device>/queue/rotationnel
+
La valeur signalée pour ces commandes doit être « 0 ».



* Les périphériques doivent être connectés à un HBA ou, dans certains cas, à un contrôleur RAID configuré pour fonctionner en mode JBOD. Lors de l'utilisation d'un contrôleur RAID, la fonction de périphérique doit être transmise à l'hôte sans superposer aucune fonctionnalité RAID. Lorsque vous utilisez un contrôleur RAID en mode JBOD, vous devez consulter la documentation RAID ou contacter le fournisseur si nécessaire pour vous assurer que le périphérique indique la vitesse de rotation « 0 ».
* Il existe deux composants de stockage distincts :
+
** Stockage de machines virtuelles
+
Il s'agit d'un pool LVM (pool de stockage) contenant les données système utilisées pour héberger la machine virtuelle ONTAP Select. Le pool LVM doit être sauvegardé par un périphérique Flash haute longévité et peut être SAS, SATA ou NVMe. Un périphérique NVMe est recommandé pour améliorer les performances.

** Disques de données
+
Il s'agit d'un ensemble de disques SSD SAS ou SATA utilisés pour la gestion des données. Les SSD doivent donc être robustes et de haute performance. L'interface NVMe n'est pas prise en charge.



* Tous les périphériques doivent être formatés avec 512BPS.


--




=== Configuration de nœuds ONTAP Select

Vous devez configurer chaque nœud ONTAP Select et chaque hôte d'hyperviseur de la manière suivante pour séparer les disques système des agrégats racine et de données :

* Créer un pool de stockage système vous devez créer un pool de stockage pour les données du système ONTAP Select. Vous devez connecter le pool de stockage dans le cadre de la configuration du nœud ONTAP Select.
* Reliez les disques physiques nécessaires l'hôte de l'hyperviseur doit être connecté aux disques SSD requis et disponible pour une utilisation par la machine virtuelle ONTAP Select. Ces disques détiennent la racine et les agrégats de données. Vous devez connecter les disques de stockage dans le cadre de la configuration du noeud ONTAP Select.




== Les restrictions de capacité de stockage

Dans le cadre de la planification d'un déploiement ONTAP Select, vous devez connaître les restrictions liées à l'allocation et à l'utilisation du stockage.

Les restrictions les plus importantes en matière de stockage sont présentées ci-dessous. Consultez également le  pour obtenir des link:https://mysupport.netapp.com/matrix/["Matrice d'interopérabilité"^]informations plus détaillées.


TIP: ONTAP Select applique plusieurs restrictions liées à l'allocation et à l'utilisation du stockage. Avant de déployer un cluster ONTAP Select ou d'acheter une licence, vous devez vous familiariser avec ces restrictions. Voir la link:https://docs.netapp.com/us-en/ontap-select/concept_lic_evaluation.html["Licence"] pour plus d'informations.



=== Calculer la capacité de stockage brute

La capacité de stockage ONTAP Select correspond à la taille totale autorisée des données virtuelles et des disques root rattachés à la machine virtuelle ONTAP Select. Vous devez tenir compte de ce point lors de l'allocation de la capacité.



=== Capacité de stockage minimale pour un cluster à un seul nœud

La taille minimale du pool de stockage alloué au nœud dans un cluster à un seul nœud est :

* Évaluation : 500 Go
* Production : 1.0 To


L'allocation minimale pour un déploiement de production comprend 1 To pour les données utilisateur, plus environ 266 Go utilisés par les différents processus internes ONTAP Select, qui est considéré comme une surcharge requise.



=== Capacité de stockage minimale pour un cluster multinœud

La taille minimale du pool de stockage alloué pour chaque nœud d'un cluster à plusieurs nœuds est :

* Évaluation : 1.9 To
* Production : 2.0 To


L'allocation minimale pour un déploiement de production se compose de 2 To pour les données utilisateur, plus environ 266 Go utilisés par divers processus internes ONTAP Select, considérés comme une surcharge requise.

[NOTE]
====
Chaque nœud d'une paire HA doit disposer de la même capacité de stockage.

Lors de l'estimation de la quantité de stockage d'une paire haute disponibilité, vous devez tenir compte du fait que tous les agrégats (racine et données) sont mis en miroir. Par conséquent, chaque plex de l'agrégat consomme une quantité égale de stockage.

Par exemple, lorsqu'un agrégat de 2 To est créé, il alloue 2 To à deux instances plex (2 To pour plexes 0 et 2 To pour plexes 1) ou 4 To du volume total de stockage sous licence.

====


=== Capacité de stockage et pools de stockage multiples

Vous pouvez configurer chaque nœud ONTAP Select de façon à utiliser jusqu'à 400 To de stockage avec un stockage DAS local, VMware VSAN ou des baies de stockage externes. Cependant, un pool de stockage unique a une taille maximale de 64 To lorsqu'il est utilisé un stockage DAS ou des baies de stockage externes. Par conséquent, si vous prévoyez d'utiliser plus de 64 To de stockage dans les situations suivantes, vous devez allouer plusieurs pools de stockage comme suit :

* Attribuez le pool de stockage initial lors du processus de création du cluster
* Augmentez le stockage nœud en allouant un ou plusieurs pools de stockage supplémentaires



NOTE: Un tampon de 2 % reste inutilisé dans chaque pool de stockage et ne nécessite pas de licence de capacité. Ce stockage n'est pas utilisé par ONTAP Select, sauf si un bouchon de capacité est spécifié. Si un plafond de capacité est spécifié, cette quantité de stockage sera utilisée à moins que la quantité spécifiée ne tombe dans la zone tampon de 2 %. La mémoire tampon est nécessaire pour éviter les erreurs occasionnelles qui se produisent lors de la tentative d'allocation de tout l'espace dans un pool de stockage.



=== Capacité de stockage et VMware VSAN

Avec VMware VSAN, un datastore peut être supérieur à 64 To. Toutefois, vous ne pouvez allouer que jusqu'à 64 To au départ lors de la création du cluster ONTAP Select. Une fois le cluster créé, vous pouvez allouer du stockage supplémentaire à partir du datastore VSAN existant. La capacité de datastore VSAN qui peut être consommée par ONTAP Select est basée sur l'ensemble des règles de stockage de VM.



=== Et des meilleures pratiques

Voici les recommandations concernant le matériel principal de l'hyperviseur :

* Tous les disques d'un agrégat ONTAP Select unique doivent être du même type. Par exemple, vous ne devez pas combiner des disques HDD et SSD dans le même agrégat.




== Besoins supplémentaires en lecteurs de disque selon les licences de la plate-forme

Les lecteurs que vous choisissez sont limités en fonction de l'offre de licences de plateforme.


NOTE: Les exigences relatives au disque s'appliquent lors de l'utilisation d'un contrôleur RAID local et de lecteurs, ainsi que d'un RAID logiciel. Ces exigences ne s'appliquent pas au stockage externe accessible via la solution ONTAP Select vNAS.

.Standard
* 8 À 60 DISQUES DURS INTERNES (NL-SAS, SATA, SAS 10 000 TR/MIN)


.Premium
* 8 À 60 DISQUES DURS INTERNES (NL-SAS, SATA, SAS 10 000 TR/MIN)
* 4 à 60 SSD internes


.XL haut de gamme
* 8 À 60 DISQUES DURS INTERNES (NL-SAS, SATA, SAS 10 000 TR/MIN)
* 4 à 60 SSD internes
* 4 à 14 NVMe internes



NOTE: La technologie RAID logicielle avec disques DAS locaux est prise en charge avec la licence Premium (SSD uniquement) et la licence Premium XL (SSD ou NVMe).



== Disques NVMe avec RAID logiciel

Vous pouvez configurer les services RAID logiciels pour utiliser les disques SSD NVMe. Votre environnement doit répondre aux exigences suivantes :

* ONTAP Select 9.7 ou version ultérieure avec un utilitaire d'administration de déploiement pris en charge
* Offre de licence Premium XL ou licence d'évaluation de 90 jours
* VMware ESXi version 6.7 ou ultérieure
* Dispositifs NVMe conformes à la spécification 1.0 ou ultérieure


Vous devez configurer manuellement les disques NVMe avant de les utiliser. Voir link:task_chk_nvme_configure.html["Configurez un hôte pour qu'il utilise des disques NVMe"] pour en savoir plus.
