---
sidebar: sidebar 
permalink: reference_plan_ots_kvm.html 
keywords: plan, planning, vnas, kvm 
summary: 'Vous devez prendre en compte plusieurs problèmes de planification liés à l"utilisation de l"hyperviseur KVM.' 
---
= Configuration requise pour ONTAP Select KVM
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez configurer ONTAP Select sur l'hyperviseur KVM avec une baie de stockage externe.



== Exigences et restrictions de base

Si vous utilisez une baie externe pour les pools de stockage ONTAP Select, les restrictions de configuration suivantes s'appliquent :

* Vous devez définir comme type de pool logique à l'aide de CLVM.
* Vous devez indiquer une limite de capacité de stockage.
* La configuration prend uniquement en charge les protocoles FC, FCoE (Fibre Channel over Ethernet) et iSCSI.
* La configuration ne reconnaît pas le stockage à provisionnement fin.



CAUTION: La capacité de stockage spécifiée doit se trouver dans les limites de stockage autorisées du stockage externe. Une erreur se produit si vous n'indiquez pas de limite de capacité ou si le stockage externe est à court d'espace pendant l'opération de création de disque.



== Et des meilleures pratiques

Vous devez respecter les recommandations suivantes :

* Définissez les ports réseau dédiés, la bande passante et les configurations vSwitch pour les réseaux ONTAP Select et le stockage externe
* Configuration de l'option Capacity pour limiter l'utilisation du stockage (la ONTAP Select ne peut pas consommer la totalité de la capacité d'un pool de stockage externe)
* Vérifiez que toutes les baies de stockage externes utilisent autant que possible les fonctionnalités de redondance et de haute disponibilité (HA)

