---
sidebar: sidebar 
permalink: reference_lic_ontap_features.html 
keywords: license, licensing, ontap features, default ontap features 
summary: 'ONTAP Select prend en charge la plupart des fonctionnalités ONTAP. La licence de nombreuses fonctionnalités de ONTAP est automatique pour chaque nœud lors du déploiement d"un cluster. Toutefois, certaines fonctionnalités requièrent une licence distincte.' 
---
= Prise en charge de ONTAP Select pour les fonctionnalités ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select prend en charge la plupart des fonctionnalités ONTAP. La licence de nombreuses fonctionnalités de ONTAP est automatique pour chaque nœud lors du déploiement d'un cluster. Toutefois, certaines fonctionnalités requièrent une licence distincte.


NOTE: Les fonctionnalités ONTAP qui dépendent matériel ne sont généralement pas prises en charge par ONTAP Select.



== Fonctionnalités ONTAP activées automatiquement par défaut

ONTAP Select prend en charge les fonctionnalités ONTAP suivantes sous licence par défaut :

* Protection anti-ransomware autonome (ARP) (mises à jour manuelles)
* CIFS
* La déduplication et la compression
* FlexCache
* FlexClone
* ISCSI
* NDMP
* Chiffrement de volume NetApp (pays sans restriction uniquement)
* NFS
* NVMe over TCP
* Fonctionnalité de colocation ONTAP
* ONTAP S3
* SnapMirror S3
* SnapMirror
* Nuage SnapMirror
* SnapRestore
* SnapVault
* Reprise d'activité pour les machines virtuelles de stockage (reprise d'activité SVM)
+

NOTE: ONTAP Select prend en charge SVM DR en tant que source et destination avec un maximum de 16 relations. La prise en charge du SVM DR est limitée à l'utilisation de la version ONTAP source aux versions +2. Par exemple, la source ONTAP Select 9.12.1 peut se connecter à ONTAP de destination versions 9.12.1, 9.13.1 ou 9.14.1.





== Fonctionnalités ONTAP sous licence séparée

Vous devez acheter une licence distincte pour toute fonctionnalité ONTAP non activée par défaut, notamment :

* FabricPool
* MetroCluster SDS (offre de licence ONTAP Select Premium)
* SnapLock Enterprise pour ONTAP Select 9.16.1 et versions antérieures (disponibles sur lelink:https://mysupport.netapp.com/site/["Site de support NetApp"^] )
+

NOTE: La SnapLock Compliance n'est pas prise en charge pour ONTAP Select.

+
** Copies Snapshot inviolables


* SnapLock Select



NOTE: Vous n'avez pas besoin d'une licence FabricPool lorsque vous utilisez StorageGRID.

.Informations associées
* link:concept_ots_overview.html#comparing-ontap-select-and-ontap-9["Comparatif ONTAP Select/ONTAP 9"]
* link:https://mysupport.netapp.com/site/systems/master-license-keys["Clés de licence principales pour ONTAP NetApp"^]

