---
sidebar: sidebar 
permalink: reference_lic_ontap_features.html 
keywords: license, licensing, ontap features, default ontap features 
summary: 'ONTAP Select prend en charge la plupart des fonctionnalités ONTAP. La licence de nombreuses fonctionnalités de ONTAP est automatique pour chaque nœud lors du déploiement d"un cluster. Toutefois, certaines fonctionnalités requièrent une licence distincte.' 
---
= Fonctionnalités ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select prend en charge la plupart des fonctionnalités ONTAP. La licence de nombreuses fonctionnalités de ONTAP est automatique pour chaque nœud lors du déploiement d'un cluster. Toutefois, certaines fonctionnalités requièrent une licence distincte.


NOTE: Les fonctionnalités ONTAP qui dépendent matériel ne sont généralement pas prises en charge par ONTAP Select.



== Fonctionnalités ONTAP activées automatiquement par défaut

Les fonctionnalités suivantes sont incluses dans ONTAP Select et sous licence par défaut :

* NVMe over TCP
* NFS
* CIFS
* ISCSI
* SnapMirror
* SnapVault
* FlexClone
* SnapRestore
* La déduplication et la compression
* Fonctionnalité de colocation ONTAP
* ONTAP S3
* Chiffrement de volume NetApp (pays sans restriction uniquement)




== Fonctionnalités ONTAP sous licence séparée

Vous devez acheter une licence distincte pour toute fonctionnalité ONTAP non activée par défaut, notamment :

* SnapLock Enterprise (la conformité SnapLock n'est pas prise en charge pour ONTAP Select)
* FabricPool
* Service de disponibilité des données
* FlexCache (aucun coût)
* SyncMirror (aucun coût)
* MetroCluster SDS (offre de licence ONTAP Select Premium)



NOTE: Vous n'avez pas besoin d'une licence FabricPool lorsque vous utilisez StorageGRID Webscale.

.Informations associées
* link:concept_ots_overview.html#comparing-ontap-select-and-ontap-9["Comparatif ONTAP Select/ONTAP 9"]

