---
sidebar: sidebar 
permalink: reference_additional_info.html 
keywords: community, forums, help, support, blogs, videos, imt, release notes, bugs, limitations, known issues 
summary: 'Vous trouverez d"autres ressources d"aide et d"autres informations sur ONTAP Select.' 
---
= Où obtenir de l'aide et trouver plus d'informations
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous trouverez d'autres ressources d'aide et d'autres informations sur ONTAP Select.



== Ressources produits ONTAP Select

Les pages produits suivantes incluent des liens vers de nombreuses ressources ONTAP Select.

* https://www.netapp.com/data-management/software-defined-storage-ontap-select/documentation["Ressources NetApp ONTAP Select"^]
* https://www.netapp.com/us/products/data-management-software/ontap-select-sds.aspx["Page produit de NetApp ONTAP Select"^]




== Ressources ONTAP 9

* https://docs.netapp.com/us-en/ontap/["Documentation ONTAP 9"^]
+
Fournit la documentation relative à ONTAP 9 (à l'exception des commandes de l'interface de ligne de commandes).

* https://docs.netapp.com/ontap-9/index.jsp["Centre de documentation ONTAP 9"^]
+
Fournit de la documentation relative aux commandes de l'interface de ligne de commandes ONTAP 9.





== Blogs

Il existe une collection d'articles de blog couvrant différents aspects de ONTAP Select.

* https://blog.netapp.com/tag/ontap-select/["Blogs NetApp ONTAP Select"^]




== NetApp

Vous pouvez entrer en contact avec d'autres utilisateurs pour poser des questions et contribuer à la communauté NetApp ONTAP Select.

* http://community.netapp.com/t5/forums/filteredbylabelpage/board-id/data-ontap-discussions/label-name/ontap%20select["Communauté NetApp : ONTAP Select"^]




== Matrice d'interopérabilité NetApp

La matrice d'interopérabilité contient des informations détaillées sur la configuration et la prise en charge des produits.

* https://mysupport.netapp.com/matrix/["NetApp IMT"^]

