---
sidebar: sidebar 
permalink: reference_lic_ontap_features.html 
keywords: license, licensing, ontap features, default ontap features 
summary: 'ONTAP Select prend en charge la plupart des fonctionnalités ONTAP. La licence de nombreuses fonctionnalités de ONTAP est automatique pour chaque nœud lors du déploiement d"un cluster. Toutefois, certaines fonctionnalités requièrent une licence distincte.' 
---
= Prise en charge de ONTAP Select pour les fonctionnalités ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select prend en charge la plupart des fonctionnalités ONTAP . De nombreuses fonctionnalités ONTAP sont automatiquement concédées sous licence pour chaque nœud lors du déploiement d'un cluster. Cependant, certaines fonctionnalités nécessitent une licence distincte.


NOTE: Les fonctionnalités ONTAP qui dépendent matériel ne sont généralement pas prises en charge par ONTAP Select.



== Fonctionnalités ONTAP concédées sous licence par défaut

ONTAP Select prend en charge les fonctionnalités ONTAP suivantes sous licence par défaut :

* Protection anti-ransomware autonome (ARP) (mises à jour manuelles)
* CIFS
* La déduplication et la compression
* Gestion externe des clés utilisant le protocole d'interopérabilité de gestion des clés (KMIP)
+
La gestion externe des clés est la seule gestion des clés prise en charge par ONTAP Select. En savoir plus link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/configure-netapp-volume-encryption-concept.html["activation et configuration de la gestion des clés externes"^].

* FlexCache
+
ONTAP Select prend en charge les volumes de cache FlexCache® avec écriture différée. Les volumes d'origine FlexCache® avec écriture différée ne sont pas pris en charge.

+
link:concept_ots_overview.html#flexcache-write-back-with-ontap-select["En savoir plus sur l'écriture différée FlexCache® avec ONTAP Select"]

* FlexClone
* ISCSI
* NDMP
* Chiffrement de volume NetApp (pays sans restriction uniquement)
* NFS
* NVMe over TCP
* Fonctionnalité de colocation ONTAP
* ONTAP S3
* SnapMirror S3
* SnapLock Select
+
SnapLock Select est l'implémentation de ONTAP SnapLock conçue pour ONTAP Select et inclut SnapLock Enterprise. Elle n'inclut pas SnapLock Compliance.

+
link:https://docs.netapp.com/us-en/ontap/snaplock/index.html["Découvrez ONTAP SnapLock"^]

* SnapMirror
* SnapMirror cloud
* SnapRestore
* SnapVault
* Reprise d'activité pour les machines virtuelles de stockage (reprise d'activité SVM)
+
ONTAP Select prend en charge SVM DR en tant que source et destination, avec un maximum de 16 relations. La prise en charge de SVM DR est limitée à l'utilisation de la version ONTAP source jusqu'aux versions +2. Par exemple, la source ONTAP Select 9.16.1 peut se connecter aux versions ONTAP de destination 9.16.1, 9.17.1 ou 9.18.1.





== Fonctionnalités ONTAP sous licence séparée

Vous devez acquérir une licence distincte pour toute fonctionnalité ONTAP qui n'est pas sous licence par défaut, notamment :

* FabricPool
+

NOTE: Vous n'avez pas besoin d'une licence FabricPool lorsque vous utilisez StorageGRID.

* MetroCluster SDS (offre de licence ONTAP Select Premium)


.Informations associées
* link:concept_ots_overview.html#compare-ontap-select-and-ontap-9["Comparez ONTAP Select et ONTAP 9"]
* link:https://mysupport.netapp.com/site/systems/master-license-keys["Découvrez les clés de licence principales NetApp ONTAP"^]

