---
sidebar: sidebar 
permalink: reference_plan_ots_two_node.html 
keywords: plan, planning, two nodes, two node clusters 
summary: 'Le déploiement d"un cluster à deux nœuds avec haute disponibilité implique la planification et la configuration identiques à celles des autres configurations de nœuds du cluster. Cependant, il y a plusieurs différences à noter lors de la création d"un cluster à deux nœuds.' 
---
= Clusters ONTAP Select à deux nœuds avec HA
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le déploiement d'un cluster à deux nœuds avec haute disponibilité implique la planification et la configuration identiques à celles des autres configurations de nœuds du cluster. Cependant, il y a plusieurs différences à noter lors de la création d'un cluster à deux nœuds.

.Environnement cible
Le cluster à deux nœuds est constitué d'une paire haute disponibilité et a été spécialement conçu pour les déploiements dans les bureaux distants et les succursales.


NOTE: Tout en étant conçu principalement pour l'environnement distant et les succursales, vous pouvez également déployer un cluster à deux nœuds dans le data Center si nécessaire.

.Licences
Vous pouvez déployer un cluster à deux nœuds à l'aide de n'importe quelle licence VMware vSphere. Néanmoins, les licences VMware ROBO Standard et Advanced sont idéales pour les déploiements de bureaux distants et succursales.

.Service médiateur
Lorsqu'un cluster se compose de deux nœuds, il n'est pas possible d'obtenir le quorum nécessaire lorsqu'un nœud tombe en panne ou perd la communication. Pour résoudre ces types de situations split-brain, chaque instance de l'utilitaire ONTAP Select Deploy comprend un service médiateur. Ce service se connecte à chaque nœud des clusters actifs à deux nœuds pour surveiller les paires haute disponibilité et faciliter la gestion des défaillances. Le service médiateur conserve les informations d'état HA à une cible iSCSI dédiée associée à chaque cluster à deux nœuds.


CAUTION: Si vous disposez d'un ou plusieurs clusters à deux nœuds actifs, la machine virtuelle ONTAP Select Deploy qui administre les clusters doit être active en permanence. Si la machine virtuelle ONTAP Select Deploy est arrêtée ou tombe en panne, le service de médiation est indisponible et la capacité de haute disponibilité est perdue pour les clusters à deux nœuds.

.Emplacement du service cluster et médiateur
Étant donné que les clusters à deux nœuds sont généralement déployés dans un bureau distant ou une succursale, ils peuvent être éloignés du centre de données de l'entreprise et de l'utilitaire ONTAP Select Deploy qui fournit le support administratif.  Avec cette configuration, le trafic de gestion entre l'utilitaire ONTAP Select Deploy et le cluster transite par le WAN. Consultez les notes de version pour plus d'informations sur les limitations et les restrictions.

. Adresse IP statique attribuée à ONTAP Select Deploy


Vous devez attribuer une adresse IP statique à l'utilitaire d'administration ONTAP Select Deploy.  Cette exigence s'applique à toutes les instances ONTAP Select Deploy qui gèrent un ou plusieurs clusters ONTAP Select à deux nœuds.
