---
sidebar: sidebar 
permalink: reference_new_ots.html 
keywords: new features 
// summary: The current release includes several new features and improvements specific to ONTAP Select. 
summary: La version actuelle inclut plusieurs nouvelles fonctionnalités ou améliorations spécifiques à ONTAP Select. 
---
= Nouveautés de ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Découvrez les nouvelles fonctionnalités et les améliorations apportées aux versions prises en charge de ONTAP Select.



== ONTAP Select 9.16.1

ONTAP Select 9.16.1 inclut plusieurs nouvelles fonctionnalités et améliorations.

Mise à jour de la prise en charge des fichiers de licence NetApp:: À partir de ONTAP Select 9.16.1, la prise en charge du fichier de licence NetApp (NLF) est mise à jour. Le nouveau format NLF inclut des licences pour les fonctionnalités ARP, ONTAP S3 et S3 SnapMirror. link:reference_lic_ontap_features.html#ontap-features-automatically-enabled-by-default["En savoir plus >>"].
+
--
Pour un nouveau déploiement ONTAP Select 9.16.1, le nouveau format NLF est automatiquement appliqué. Lorsque vous mettez à niveau un déploiement ONTAP Select existant vers 9.16.1, le nouveau format NLF n'est pas appliqué. Pour obtenir les licences des fonctionnalités ARP, ONTAP S3 et S3 SnapMirror, vous devez télécharger la version NLF mise à jour après la mise à niveau. Si vous revenez à ONTAP Select 9.15.1 ou version antérieure, vous devez réinstaller les licences de fonction que vous aviez avant la mise à niveau.

--
Prise en charge de la protection anti-ransomware autonome:: ONTAP Select 9.16.1 introduit la prise en charge de la protection anti-ransomware autonome (ARP). ONTAP Select 9.16.1 prend uniquement en charge les mises à jour manuelles pour ARP, les mises à jour automatiques ne sont pas prises en charge. La licence de fonction ARP est incluse dans le fichier NLF pour ONTAP Select 9.16.1. link:reference_lic_ontap_features.html#ontap-features-automatically-enabled-by-default["En savoir plus >>"].
Prise en charge améliorée de VMware ESXi:: ONTAP Select 9.16.1 inclut la prise en charge de VMware ESXi 8.0 U3.




== ONTAP Select 9.15.1

ONTAP Select 9.15.1 inclut plusieurs nouvelles fonctionnalités et améliorations.

Prise en charge de l'hyperviseur KVM mise à jour:: À partir de ONTAP Select 9.15.1, l'hyperviseur KVM (Kernel-based Virtual machine) est pris en charge sur Red Hat Enterprise Linux (RHEL) 9.4 et Rocky Linux 9.4.
Prise en charge de l'extension et de la réduction des clusters:: Depuis ONTAP Select 9.15.1, l'extension et la réduction des clusters sont prises en charge.
+
--
* Extension des clusters à six nœuds à huit nœuds
+
Vous pouvez augmenter la taille du cluster d'un cluster de six nœuds à un cluster de huit nœuds grâce à la fonction d'extension de cluster. L'extension des clusters à partir d'un, deux ou quatre nœuds vers des clusters à six ou huit nœuds n'est pas prise en charge actuellement. link:task_cluster_expansion_contraction.html#expand-the-cluster["En savoir plus >>"].

* Contraction des clusters de huit nœuds à six nœuds
+
Vous pouvez réduire la taille d'un cluster de huit nœuds à six nœuds grâce à la fonctionnalité de contraction de cluster. Les contractions de clusters de six ou huit nœuds en clusters à un, deux ou quatre nœuds ne sont pas prises en charge actuellement. link:task_cluster_expansion_contraction.html#contract-the-cluster["En savoir plus >>"].



--



NOTE: La prise en charge de l'extension et de la réduction des clusters est limitée aux clusters ESX uniquement.



== ONTAP Select 9.14.1

ONTAP Select 9.14.1 inclut plusieurs nouvelles fonctionnalités et améliorations.

Prise en charge de l'hyperviseur KVM:: Depuis ONTAP Select 9.14.1, la prise en charge de l'hyperviseur KVM a été rétablie. Auparavant, la prise en charge du déploiement d'un nouveau cluster sur un hyperviseur KVM a été supprimée dans ONTAP Select 9.10.1 et la prise en charge de la gestion des clusters et des hôtes KVM existants, à l'exception de la mise hors ligne ou de la suppression, a été supprimée dans ONTAP Select 9.11.1.
Le plug-in Deploy VMware vCenter n'est plus pris en charge:: À partir de ONTAP Select 9.14.1, le plug-in de déploiement de VMware vCenter n'est plus pris en charge.
Prise en charge de ONTAP Select Deploy mise à jour:: Si vous exécutez une version de ONTAP Select Deploy 9.14.1 antérieure à 9.14.1P2, vous devez mettre à niveau vers ONTAP Select Deploy 9.14.1P2 dès que possible. Pour plus d'informations, reportez-vous à la section link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2886733["Notes de mise à jour de ONTAP Select 9.14.1"^].
Prise en charge améliorée de VMware ESXi:: ONTAP Select 9.14.1 inclut la prise en charge de VMware ESXi 8.0 U2.




== ONTAP Select 9.13.1

ONTAP Select 9.13.1 inclut plusieurs nouvelles fonctionnalités et améliorations.

Prise en charge de NVMe over TCP:: Lorsque vous effectuez une mise à niveau vers ONTAP Select 9.13.1, vous devez disposer de la nouvelle licence pour prendre en charge NVMe over TCP. Cette licence est automatiquement incluse lorsque vous déployez ONTAP Select pour la première fois à partir de la version 9.13.1.
Prise en charge de VMware ESXi mise à jour:: À partir de ONTAP 9.13.1, VMware ESXi 8.0.1 GA (build 20513097) est pris en charge par la version matérielle 4 et ultérieure.
Prise en charge de ONTAP Select Deploy mise à jour:: Depuis avril 2024, ONTAP Select Deploy 9.13.1 n'est plus disponible sur le site de support NetApp. Si vous exécutez ONTAP Select Deploy 9.13.1, vous devez effectuer une mise à niveau vers ONTAP Select Deploy 9.14.1P2 dès que possible. Pour plus d'informations, reportez-vous à la section link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2886733["Notes de mise à jour de ONTAP Select 9.14.1"^].




== ONTAP Select 9.12.1

ONTAP Select 9.12.1 bénéficie de la plupart des nouveautés de la version actuelle du produit principal ONTAP. Elle n'inclut aucune nouvelle fonctionnalité ni amélioration spécifique à ONTAP Select.

Depuis avril 2024, ONTAP Select Deploy 9.12.1 n'est plus disponible sur le site de support NetApp. Si vous exécutez ONTAP Select Deploy 9.12.1, vous devez effectuer une mise à niveau vers ONTAP Select Deploy 9.14.1P2 dès que possible. Pour plus d'informations, reportez-vous à la section link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2886733["Notes de mise à jour de ONTAP Select 9.14.1"^].



== ONTAP Select 9.11.1

ONTAP Select 9.11.1 inclut un certain nombre de nouvelles fonctionnalités et améliorations.

Prise en charge améliorée de VMware ESXi:: ONTAP Select 9.11.1 inclut la prise en charge de VMware ESXi 7.0 U3C.
Prise en charge de VMware NSX-T:: ONTAP Select 9.10.1 et versions ultérieures ont été qualifiés pour VMware NSX-T version 3.1.2. Il n'y a pas de problèmes fonctionnels ni de défaillances lors de l'utilisation de NSX-T avec un cluster à nœud unique ONTAP Select déployé avec un fichier OVA et l'utilitaire d'administration ONTAP Select Deploy. Cependant, lorsque vous utilisez NSX-T avec un cluster multinœud ONTAP Select, nous vous conseillons de prendre en compte les restrictions suivantes concernant ONTAP Select 9.11.1 :
+
--
* Vérificateur de connectivité réseau
+
Le vérificateur de connectivité réseau disponible via la CLI de déploiement échoue lorsqu'il est exécuté sur un réseau basé sur NSX-T.



--
L'hyperviseur KVM n'est plus pris en charge::
+
--
* Depuis la version ONTAP Select 9.10.1, il n'est plus possible de déployer un nouveau cluster sur l'hyperviseur KVM.
* Depuis ONTAP Select 9.11.1, toutes les fonctionnalités de gestion ne sont plus disponibles pour les clusters et hôtes KVM existants, à l'exception des fonctions de mise hors ligne et de suppression.
+
NetApp recommande fortement aux clients de planifier et d'exécuter une migration complète de données depuis ONTAP Select pour KVM vers toute autre plateforme ONTAP, y compris ONTAP Select pour ESXi. Pour plus d'informations, reportez-vous à la section https://mysupport.netapp.com/info/communications/ECMLP2877451.html["Avis de fin de disponibilité"^]



--




== ONTAP Select 9.10.1

ONTAP Select 9.10.1 inclut un certain nombre de nouvelles fonctionnalités et améliorations.

Prise en charge de VMware NSX-T:: ONTAP Select 9.10.1 a été qualifié pour VMware NSX-T version 3.1.2. Il n'y a pas de problèmes fonctionnels ni de défaillances lors de l'utilisation de NSX-T avec un cluster à nœud unique ONTAP Select déployé avec un fichier OVA et l'utilitaire d'administration ONTAP Select Deploy. Cependant, lorsque vous utilisez NSX-T avec un cluster multinœud ONTAP Select, nous vous recommandons de prendre en compte les exigences et restrictions suivantes :
+
--
* MTU du cluster
+
Vous devez ajuster manuellement la taille de MTU du cluster à 8800 avant de déployer le cluster pour tenir compte de la surcharge supplémentaire. Les conseils de VMware sont de permettre la création d'un tampon de 200 octets lors de l'utilisation de NSX-T.

* Configuration réseau 4x10 Gb
+
Pour les déploiements ONTAP Select sur un hôte VMware ESXi configuré avec quatre cartes réseau, l'utilitaire de déploiement vous invite à suivre les meilleures pratiques de répartition du trafic interne entre deux groupes de ports différents et du trafic externe entre deux groupes de ports différents. Toutefois, lorsque vous utilisez un réseau de superposition, cette configuration ne fonctionne pas et vous devez ignorer la recommandation. Dans ce cas, vous ne devez utiliser qu'un seul groupe de ports interne et un seul groupe de ports externe.

* Vérificateur de connectivité réseau
+
Le vérificateur de connectivité réseau disponible via la CLI de déploiement échoue lorsqu'il est exécuté sur un réseau basé sur NSX-T.



--
L'hyperviseur KVM n'est plus pris en charge:: Depuis ONTAP Select la version 9.10.1, il n'est plus possible de déployer un nouveau cluster sur l'hyperviseur KVM. Cependant, si vous mettez à niveau un cluster d'une version précédente vers 9.10.1, vous pouvez toujours utiliser l'utilitaire de déploiement pour gérer le cluster.




== ONTAP Select 9.9.1

ONTAP Select 9.9.1 inclut un certain nombre de nouvelles fonctionnalités et améliorations.

Prise en charge de la famille de processeurs:: À partir de ONTAP Select 9.9.1, seuls les modèles de processeurs Intel Xeon Sandy Bridge ou version ultérieure sont pris en charge pour ONTAP Select.
Prise en charge de VMware ESXi mise à jour:: La prise en charge de VMware ESXi a été améliorée avec ONTAP Select 9.9.1. Les versions suivantes sont désormais prises en charge :
+
--
* ESXi 7.0 U2
* ESXi 7.0 U1


--




== ONTAP Select 9.8

ONTAP Select 9.8 inclut plusieurs fonctionnalités nouvelles et modifiées.

Interface haut débit:: La fonction d'interface haut débit améliore la connectivité réseau en offrant une option pour les réseaux 25G (25GbE) et 40G (40GbE). Pour obtenir les meilleures performances lors de l'utilisation de ces vitesses élevées, vous devez respecter les meilleures pratiques en matière de configurations de mappage des ports, comme décrit dans la documentation ONTAP Select.
Prise en charge de VMware ESXi mise à jour:: Deux changements ont été apportés à ONTAP Select 9.8 concernant la prise en charge de VMware ESXi.
+
--
* ESXi 7.0 est pris en charge (GA Build 15843807 et versions ultérieures)
* ESXi 6.0 n'est plus pris en charge


--

