---
sidebar: sidebar 
permalink: reference_initial_state.html 
keywords: install, installing, initial state, cluster initial state 
summary: 'Vous devez connaître l"état initial d"un cluster après son déploiement et sa configuration en fonction des besoins de votre environnement.' 
---
= État initial du cluster ONTAP Select après le déploiement
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous devez connaître l'état initial d'un cluster après son déploiement et sa configuration en fonction des besoins de votre environnement.

Un cluster ONTAP Select possède plusieurs caractéristiques après sa création.


NOTE: La restriction des rôles et des autorisations pour le compte d'administrateur ONTAP peut limiter la capacité de ONTAP Select Deploy à gérer le cluster. Pour plus d'informations, consultez l'article de la base de connaissances link:https://kb.netapp.com/onprem/ontap/ONTAP_Select/OTS_Deploy_cluster_refresh_fails_with_error%3A_ONTAPSelectSysCLIVersionFailed_zapi_returned_bad_status_0%3A_None["Échec de l'actualisation du cluster de déploiement OTS avec erreur"^].

.LIF
Deux types de LIF spécifiées par le client sont attribués :

* Gestion du cluster (un par cluster)
* Gestion des nœuds (un par nœud)



NOTE: Un cluster multi-nœuds possède un réseau interne avec des LIFs générées automatiquement.

.SVM
Trois SVM sont actifs :

* SVM d'administration
* SVM du nœud
* SVM système (cluster



NOTE: Les SVM de données ne sont pas créés dans le cadre du déploiement des clusters ONTAP Select. Ils doivent être créés par l'administrateur du cluster après le déploiement. Pour plus d'informations, voir https://docs.netapp.com/us-en/ontap/nfs-config/create-svms-data-access-task.html["Créer un SVM"^].

.64 bits
L'agrégat root est créé.

.Caractéristiques
Toutes les fonctionnalités sont disponibles sous licence. SnapLock et FabricPool requièrent deux licences distinctes.

.Informations associées
* link:https://docs.netapp.com/us-en/ontap/system-admin/types-svms-concept.html["Types de SVM contenus dans un cluster"^]
* link:reference_lic_ontap_features.html["Fonctionnalités ONTAP activées par défaut"]

