---
sidebar: sidebar 
permalink: reference_lic_ontap_features.html 
keywords: license, licensing, ontap features, default ontap features 
summary: 'ONTAP Select prend en charge la plupart des fonctionnalités ONTAP. La licence de nombreuses fonctionnalités de ONTAP est automatique pour chaque nœud lors du déploiement d"un cluster. Toutefois, certaines fonctionnalités requièrent une licence distincte.' 
---
= Prise en charge de ONTAP Select pour les fonctionnalités ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select prend en charge la plupart des fonctionnalités ONTAP . De nombreuses fonctionnalités ONTAP sont automatiquement concédées sous licence pour chaque nœud lors du déploiement d'un cluster. Cependant, certaines fonctionnalités nécessitent une licence distincte.


NOTE: Les fonctionnalités ONTAP qui dépendent matériel ne sont généralement pas prises en charge par ONTAP Select.



== Fonctionnalités ONTAP activées automatiquement par défaut

ONTAP Select prend en charge les fonctionnalités ONTAP suivantes sous licence par défaut :

* Protection anti-ransomware autonome (ARP) (mises à jour manuelles)
* CIFS
* La déduplication et la compression
* FlexCache
* FlexClone
* ISCSI
* NDMP
* Chiffrement de volume NetApp (pays sans restriction uniquement)
* NFS
* NVMe over TCP
* Fonctionnalité de colocation ONTAP
* ONTAP S3
* SnapLock Select
+
SnapLock Select est l'implémentation de ONTAP SnapLock conçue pour ONTAP Select et inclut SnapLock Enterprise. Elle n'inclut pas SnapLock Compliance. Pour plus d'informations, consultez la link:https://docs.netapp.com/us-en/ontap/snaplock/index.html["Documentation ONTAP SnapLock"^].

* SnapMirror S3
* SnapMirror
* SnapMirror Cloud
* SnapRestore
* SnapVault
* Reprise d'activité pour les machines virtuelles de stockage (reprise d'activité SVM)
+
ONTAP Select prend en charge SVM DR en tant que source et destination avec un maximum de 16 relations. La prise en charge du SVM DR est limitée à l'utilisation de la version ONTAP source aux versions +2. Par exemple, la source ONTAP Select 9.12.1 peut se connecter à ONTAP de destination versions 9.12.1, 9.13.1 ou 9.14.1.





== Fonctionnalités ONTAP sous licence séparée

Vous devez acquérir une licence distincte pour toute fonctionnalité ONTAP qui n'est pas activée par défaut, notamment :

* FabricPool
+

NOTE: Vous n'avez pas besoin d'une licence FabricPool lorsque vous utilisez StorageGRID.

* MetroCluster SDS (offre de licence ONTAP Select Premium)


.Informations associées
* link:concept_ots_overview.html#compare-ontap-select-and-ontap-9["Comparatif ONTAP Select/ONTAP 9"]
* link:https://mysupport.netapp.com/site/systems/master-license-keys["Clés de licence principales pour ONTAP NetApp"^]

