---
sidebar: sidebar 
permalink: reference_faq.html 
keywords: faq, frequently asked questions 
summary: Trouvez des réponses aux questions courantes sur ONTAP Select. 
---
= FAQ pour ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous trouverez des réponses aux questions fréquemment posées à propos de ONTAP Select.

[NOTE]
====
Depuis ONTAP Select 9.14.1, la prise en charge de l'hyperviseur KVM a été rétablie. Auparavant, la prise en charge du déploiement d'un nouveau cluster sur un hyperviseur KVM a été supprimée dans ONTAP Select 9.10.1 et la prise en charge de la gestion des clusters et des hôtes KVM existants, à l'exception de la mise hors ligne ou de la suppression, a été supprimée dans ONTAP Select 9.11.1.

====


== Généralités

Il y a plusieurs questions générales et réponses.

.Quelle est la différence entre le déploiement ONTAP Select et ONTAP Select ?
ONTAP Select Deploy est l'utilitaire utilisé pour créer des clusters ONTAP Select. Actuellement, ONTAP Select Deploy est la seule méthode disponible pour créer un cluster de production. ONTAP Select Deploy peut également être utilisé pour créer un cluster d'évaluation afin que les clients puissent tester et documenter les étapes réelles d'un déploiement en production. ONTAP Select Deploy peut également convertir un cluster d'évaluation en cluster de production en utilisant une licence de niveau de capacité appropriée et une capacité suffisante pour couvrir l'espace utilisé au cours de l'évaluation.

ONTAP Select Deploy est une machine virtuelle qui contient une image de ONTAP Select. Lors de l'installation des clusters, ONTAP Select Deploy met en œuvre plusieurs vérifications afin que les exigences minimales relatives au ONTAP Select soient respectées. ONTAP Select Deploy VM et les clusters Select peuvent être mis à niveau séparément.

.Comment résoudre un problème de performances avec ONTAP Select ?
Comme ONTAP sur FAS, les données de performances doivent être collectées à l'aide de l'utilitaire perfstat. Voici un exemple de commande :

[listing]
----
perfstat8 –i N,m -t <sample time in minutes> --verbose --nodes=<filer IP> --diag-passwd=abcxyz --mode="cluster-mode" > <name of output file>
----
.Comment accéder à la page API swagger pour ONTAP Select Deploy ?
[listing]
----
http://<Deploy-IP-Address/api/ui
----

NOTE: La version API v3 n'est pas rétrocompatible avec la version précédente de l'API. Une nouvelle procédure API est disponible sur le https://library.netapp.com/ecm/ecm_download_file/ECMLP2845694["Field Portal"^].

.La machine virtuelle ONTAP Select peut-elle être sauvegardée avec VMware ou d'autres snapshots tiers ?
Non La machine virtuelle ONTAP Select utilise des disques persistants indépendants, exclus des snapshots basés sur VMware. La seule méthode de sauvegarde de ONTAP Select prise en charge est SnapMirror ou SnapVault.

.Où puis-je obtenir des précisions sur les questions qui ne sont pas traitées dans cette FAQ ?
Contactez link:mailto:ng-ses-ontap-select@netapp.com["ng-ses-ontap-select@netapp.com"].



== Licences, installation, mises à niveau et restauration

Il y a plusieurs questions et réponses concernant les licences, l'installation, les mises à niveau et les reprises.

.Est-il possible de mettre à niveau ONTAP Select et ONTAP Select Deploy séparément ?
Oui. L'utilitaire ONTAP Select Deploy peut être mis à niveau séparément du cluster ONTAP Select. De même, le cluster Select peut être mis à niveau séparément à partir de l'utilitaire ONTAP Select Deploy.

.ONTAP Select peut-il être mis à niveau à l'aide de la même procédure qu'un cluster FAS ?
Oui, la procédure de mise à niveau pour un cluster Select est identique à la mise à niveau d'un cluster FAS, bien que le binaire de mise à niveau ONTAP Select soit un téléchargement distinct du binaire de mise à niveau ONTAP on FAS.

.Est-il possible de rétablir ONTAP Select avec la même procédure que celle d'un cluster FAS ?
Oui, la procédure de restauration d'un cluster ONTAP Select est quasiment identique à la procédure de restauration d'un cluster FAS. Il y a toutefois quelques différences :

* Seules les instances mises à niveau de ONTAP Select peuvent être rétablies et seulement jusqu'à la version d'installation d'origine. Les nouvelles installations ne peuvent pas être rétablies dans une ancienne version de code, même si ONTAP Select en général prend en charge cette ancienne version.
* Pour ONTAP Select (KVM) et ONTAP Select (ESX) utilisant RAID logiciel, il n'est pas possible de revenir à une version antérieure qui ne prend pas en charge le RAID logiciel. En outre, une nouvelle installation de ONTAP Select 9.5 ou version ultérieure sur ESX utilise les pilotes réseau VMXNET3 et, si possible, le pilote vNMVE. Ces nouvelles installations ne peuvent pas être rétablies dans des versions antérieures de ONTAP Select.
* Si la machine virtuelle ONTAP Select a également été mise à niveau vers une grande instance (à l'aide de la licence Premium XL), le retour à une version antérieure à 9.6 n'est pas pris en charge, car la fonctionnalité Grande instance n'est pas disponible dans les versions antérieures.


.ONTAP MetroCluster SDS a-t-il besoin d'une licence Premium au moins ?
Oui.

.Est-il possible de modifier la configuration réseau du cluster ONTAP Select après l'installation ?
Les modifications apportées aux propriétés de cluster ONTAP Select suivantes sont reconnues par ONTAP Select Deploy à l'aide de l'opération d'actualisation de cluster disponible via l'interface utilisateur, la CLI ou l'API REST :

* Configuration du réseau (adresses IP, DNS, NTP, masque de réseau et passerelle)
* Cluster ONTAP Select, nom du nœud et version


Les modifications suivantes du serveur virtuel ONTAP Select sont également reconnues :

* Modifications du nom et de l'état du serveur virtuel ONTAP Select (par exemple, en ligne ou hors ligne)
* Modifications du nom du réseau de l'hôte et du nom du pool de stockage


La mise à niveau vers ONTAP Select Deploy 2.6 permet la prise en charge de ces modifications dans tout cluster ONTAP Select déjà déployé, mais sa configuration d'origine n'a pas été modifiée. En d'autres termes, si les propriétés du cluster ONTAP Select mentionnées ci-dessus ont été modifiées à l'aide de System Manager ou de vCenter, la mise à niveau vers ONTAP Select Deploy 2.6 ne corrige pas ces incohérences. Les modifications de la propriété ONTAP Select doivent d'abord être annulées pour que le déploiement d'ONTAP Select ajoute ses métadonnées uniques à chaque machine virtuelle d'ONTAP Select.

.Est-il possible de modifier la configuration réseau de ONTAP Select Deploy après l'installation ?
La modification des informations réseau de l'instance Deploy après son exécution dans un environnement n'est pas prise en charge. Pour plus d'informations, consultez l'article de la base de connaissances. link:https://kb.netapp.com/onprem/ontap/ONTAP_Select/Modifying_DNS_configuration_of_ONTAP_Deploy_instance["Modification de la configuration DNS de l'instance ONTAP Deploy"^] .

.Comment Deploy détecte-t-il que les licences ONTAP Select sont renouvelées ?
La méthode est la même pour toutes les licences, bien que les caractéristiques spécifiques varient selon qu'il s'agit d'une licence Capacity Tier ou Capacity Pool.

* ONTAP Select Deploy détecte si les licences et les contrats de support sont renouvelés à l'achat d'un fichier de licence mis à jour auprès de NetApp. Le fichier de licence (.NLF) comprend les dates de capacité, de début et de fin ; et est généré sur le link:https://mysupport.netapp.com/site/["Site de support NetApp"^], Puis mis à jour sur le serveur de déploiement.
+

NOTE: Vous pouvez charger le NLF dans le serveur de déploiement en utilisant les fonctions *Ajouter* et *mettre à jour*. *Add* ajoute de nouvelles licences au serveur et *Update* met à jour les fichiers existants avec des informations telles que la capacité, la licence de nœud (standard, Premium, Premium XL), les dates de début et de fin du support (licence Capacity Tier) ou les dates de début et de fin de l'abonnement (licence Capacity Pool).

+

CAUTION: Ne tentez pas de modifier le fichier de licence. Cela invalide la clé de sécurité et rend la licence non valide.

* Une licence *Capacity Tier* est une licence permanente par nœud liée au numéro de série du nœud ONTAP Select. Il est vendu avec un contrat de support distinct. Pendant que la licence est permanente, le contrat de support doit être renouvelé pour accéder aux mises à niveau ONTAP Select et bénéficier de l'assistance du support technique NetApp. Un contrat de support en cours de validité est également requis pour modifier les paramètres de licence, tels que la capacité ou la taille du nœud.
+
L'achat d'une mise à jour de licence Capacity Tier, d'une modification de paramètre ou d'un renouvellement de contrat de support nécessite le numéro de série du nœud dans le cadre de la commande. Les numéros de série des nœuds de niveau de capacité comportent neuf chiffres et commencent par le numéro « 32 ».

+
Une fois l'achat terminé et le fichier de licence généré, il est téléchargé sur le serveur de déploiement à l'aide de la fonction *Update*.

* Une licence *Capacity Pool* est un abonnement permettant d'utiliser un pool de capacité et une taille de nœud spécifiques (standard, Premium, Premium XL) pour déployer un ou plusieurs clusters. L'abonnement comprend le droit d'utiliser une licence et un support pour une durée spécifiée. Le droit d'utiliser une licence et le contrat de support ont des dates de début et de fin spécifiées.


.Comment le déploiement détecte-t-il si les nœuds ont renouvelé des licences ou un contrat de support ?
L'achat, la génération et le téléchargement d'un fichier de licence mis à jour permettent à Deploy de détecter les licences et les contrats de support renouvelés.

Si une date de fin de contrat de support pour le niveau de capacité est dépassée, le nœud peut rester en cours d'exécution, mais vous ne pouvez pas télécharger et installer les mises à jour ONTAP, ou bien appeler le support technique NetApp pour obtenir de l'aide sans mettre à jour au préalable le contrat de support.

Si un abonnement au pool de capacité expire, le système vous avertit d'abord mais après 30 jours, si le système s'arrête, il ne redémarre pas tant qu'un abonnement mis à jour n'est pas installé sur le serveur de déploiement.



== Stockage

Plusieurs questions et réponses concernant le stockage sont à poser.

.Une seule instance ONTAP Select peut-elle créer des clusters sur ESX et KVM ?
Oui. ONTAP Select Deploy peut être installé sur KVM ou ESX, et les deux installations peuvent créer des clusters ONTAP Select sur l'un ou l'autre des hyperviseurs.

.VCenter est-il requis pour ONTAP Select sur ESX ?
Si les hôtes ESX sont sous licence appropriée, il est inutile de gérer les hôtes ESX par un serveur vCenter. Toutefois, si les hôtes sont gérés par un serveur vCenter, vous devez configurer le déploiement de ONTAP Select pour utiliser ce serveur vCenter. En d'autres termes, vous ne pouvez pas configurer des hôtes ESX comme autonomes dans ONTAP Select Deploy s'ils sont gérés activement par vCenter Server. Notez que ONTAP Select Deploy VM s'appuie sur vCenter pour suivre toutes les migrations de VM ONTAP Select entre les hôtes ESXi en raison d'un événement vMotion ou VMware HA.

.Qu'est-ce que le RAID logiciel ?
ONTAP Select peut utiliser des serveurs sans contrôleur RAID matériel. Dans ce cas, la fonctionnalité RAID est implémentée dans le logiciel. Avec la technologie RAID logicielle, les disques SSD et NVMe sont pris en charge. Le démarrage ONTAP Select et les disques centraux doivent tout de même résider dans une partition virtualisée (pool de stockage ou datastore). ONTAP Select utilise RD2 (partitionnement données-racines) pour partitionner les disques SSD. La partition racine ONTAP Select réside donc sur les mêmes piles de disques physiques utilisées pour les agrégats de données. Toutefois, l'agrégat racine, l'amorçage et les disques virtualisés centraux ne sont pas pris en compte par rapport à la licence de capacité.

Toutes les méthodes RAID disponibles sur les systèmes AFF/FAS sont également disponibles pour ONTAP Select. Notamment RAID 4, RAID DP et RAID-TEC. Le nombre minimal de disques SSD varie en fonction du type de configuration RAID choisi. Les meilleures pratiques exigent la présence d'au moins une pièce de rechange. Les disques de secours et de parité ne sont pas pris en compte pour la licence de capacité.

.En quoi le RAID logiciel est-il différent d'une configuration RAID matérielle ?
La technologie RAID logicielle est une couche de la pile logicielle ONTAP. Le logiciel RAID offre un contrôle plus administratif, car les disques physiques sont partitionnés et disponibles en tant que disques bruts au sein de la machine virtuelle ONTAP Select. Alors qu'avec le RAID matériel, une seule grande LUN est généralement disponible, puis peut être sculptée pour créer des Kfiles d'attente VMDs visibles au sein de ONTAP Select. Il est disponible en option et peut être utilisé à la place d'un RAID matériel.

Voici quelques-unes des conditions requises pour le RAID logiciel :

* Pris en charge pour ESX et KVM
+
** Depuis ONTAP Select 9.14.1, la prise en charge de l'hyperviseur KVM a été rétablie. Auparavant, la prise en charge de l'hyperviseur KVM a été supprimée dans ONTAP Select 9.10.1.


* Taille des disques physiques pris en charge : 200 Go – 32 To
* Pris en charge uniquement sur les configurations DAS
* Prise en charge avec des disques SSD ou NVMe
* Requiert une licence Premium ou Premium XL ONTAP Select
* Le contrôleur RAID matériel doit être absent ou désactivé ou fonctionner en mode SAS HBA
* Un pool de stockage LVM ou un datastore basé sur une LUN dédiée doit être utilisé pour les disques système : core dump, boot/NVRAM et le médiateur.


.ONTAP Select pour KVM prend-il en charge plusieurs liaisons NIC ?
Lors de l'installation sur KVM, vous devez utiliser une liaison unique et un pont unique. Un hôte avec deux ou quatre ports physiques doit avoir tous les ports dans la même liaison.

.Comment ONTAP Select signale-t-il une panne de disque physique ou de carte réseau dans l'hôte de l'hyperviseur ou signale-t-il une alerte ? ONTAP Select récupère-t-il ces informations depuis l'hyperviseur ou doit-il être défini au niveau de l'hyperviseur ?
Lors de l'utilisation d'un contrôleur RAID matériel, ONTAP Select ignore largement les problèmes de serveur sous-jacent. Si le serveur est configuré selon nos meilleures pratiques, une certaine redondance devrait exister. Nous recommandons la solution RAID 5/6 pour résister aux défaillances de disques. Pour les configurations RAID logicielles, ONTAP émet des alertes concernant les pannes de disque et, s'il existe un disque de rechange, lance la reconstruction du disque.

Vous devez utiliser au moins deux cartes réseau physiques pour éviter un point de défaillance unique au niveau de la couche réseau. NetApp recommande que les groupes de ports internes, de gestion et de données disposent de cartes réseau et d'une liaison montante ou plus dans l'équipe ou le lien. Cette configuration garantit que, en cas de défaillance de la liaison montante, le commutateur virtuel déplace le trafic de la liaison montante défaillante vers une liaison montante saine dans l'équipe NIC. Pour plus de détails sur la configuration réseau recommandée, reportez-vous à la section link:reference_plan_best_practices.html#networking["Résumé des meilleures pratiques : la mise en réseau"].

Toutes les autres erreurs sont gérées par ONTAP HA dans le cas d'un cluster à deux ou quatre nœuds. Si le serveur hyperviseur doit être remplacé et que le cluster ONTAP Select doit être reconstitué avec un nouveau serveur, reportez-vous à _Puis-je récupérer un nœud ONTAP Select ?_.

.Puis-je récupérer un nœud ONTAP Select ?
Contactez le support technique NetApp si vous devez récupérer un nœud ONTAP Select , par exemple, si une machine virtuelle ou un hôte ONTAP Select est complètement perdu ou si un cluster à nœud unique est supprimé accidentellement. Pour plus d'informations, consultez l'article de la base de connaissances. link:https://kb.netapp.com/on-prem/ontap/ontap-select/Select-KBs/ONTAP_Select_node_VM_recovery_in_case_of_disaster["Récupération de la machine virtuelle du nœud ONTAP Select en cas de sinistre"^] .

.Quelle est la taille maximale des datastores ONTAP Select prise en charge ?
Toutes les configurations, y compris VSAN, prennent en charge 400 To de stockage par nœud ONTAP Select.

Lorsque vous effectuez une installation sur des datastores de taille supérieure à la taille maximale prise en charge, vous devez utiliser Capacity Cap lors de la configuration du produit.

.Comment augmenter la capacité d'un nœud ONTAP Select ?
ONTAP Select Deploy contient un workflow d'ajout de stockage qui prend en charge l'extension de capacité sur un nœud ONTAP Select. Vous pouvez développer le stockage sous gestion en utilisant l'espace du même datastore (si de l'espace est toujours disponible) ou en ajoutant de l'espace à partir d'un datastore distinct. La combinaison de datastores locaux et distants dans le même agrégat n'est pas prise en charge.

Storage Add prend également en charge le RAID logiciel. Toutefois, dans le cas d'un RAID logiciel, des disques physiques supplémentaires doivent être ajoutés à la machine virtuelle ONTAP Select. L'ajout de stockage est semblable à la gestion d'une baie FAS ou AFF. Vous devez tenir compte des tailles de groupe RAID et des disques lors de l'ajout de stockage à un nœud ONTAP Select à l'aide du logiciel RAID.

.ONTAP Select prend-il en charge les datastores VSAN ou de type baie externe ?
ONTAP Select Deploy et ONTAP Select for ESX prennent en charge la configuration d'un cluster ONTAP Select à nœud unique en utilisant un VSAN ou un type de baie externe de datastore pour son pool de stockage.

ONTAP Select Deploy et ONTAP Select for KVM prennent en charge la configuration d'un cluster ONTAP Select à nœud unique à l'aide d'un type de pool de stockage logique partagé sur les baies externes. Les pools de stockage peuvent être basés sur iSCSI ou FC/FCoE. Les autres types de pools de stockage ne sont pas pris en charge.

Les clusters haute disponibilité à plusieurs nœuds sur un système de stockage partagé sont pris en charge.

.ONTAP Select prend-il en charge les clusters à plusieurs nœuds sur VSAN ou tout autre stockage externe partagé incluant certaines piles HCI ?
Les clusters à plusieurs nœuds qui utilisent un stockage externe (multinœud vNAS) sont pris en charge pour ESX et KVM. Le mélange d'hyperviseurs dans le même cluster n'est pas pris en charge. Une architecture haute disponibilité sur stockage partagé implique toujours que chaque nœud d'une paire haute disponibilité possède une copie en miroir de ses données partenaires. Toutefois, un cluster à plusieurs nœuds tire parti des avantages de la continuité de l'activité de ONTAP, contrairement à un cluster à un seul nœud qui repose sur VMware HA ou KVM Live Motion.

Bien qu'ONTAP ONTAP Select Deploy prenne en charge plusieurs machines virtuelles ONTAP Select sur le même hôte, ces instances ne peuvent pas faire partie du même cluster ONTAP Select lors de sa création. Pour les environnements ESX, NetApp recommande de créer des règles d'anti-affinité de machines virtuelles afin que VMware HA ne tente pas de migrer plusieurs machines virtuelles ONTAP Select du même cluster ONTAP Select vers un seul hôte ESX. De plus, si ONTAP Select Deploy détecte qu'une migration vMotion administrative (initiée par l'utilisateur) ou une migration en direct d'une machine virtuelle ONTAP Select a entraîné une violation de nos meilleures pratiques, comme le fait que deux nœuds ONTAP Select se retrouvent sur le même hôte physique, ONTAP Select Deploy publie une alerte dans l'interface utilisateur de déploiement et le journal. ONTAP Select Deploy ne peut connaître l'emplacement de la machine virtuelle ONTAP Select que par une actualisation du cluster, une opération manuelle que l'administrateur ONTAP Select Deploy doit lancer.  Il n'existe aucune fonctionnalité dans ONTAP Select Deploy permettant une surveillance proactive, et l'alerte n'est visible que via l'interface utilisateur de déploiement ou le journal. Autrement dit, elle ne peut pas être transmise à une infrastructure de surveillance centralisée.

.ONTAP Select prend-il en charge NSX VXLAN de VMware ?
Les groupes de ports NSX-V VXLAN sont pris en charge. Pour la haute disponibilité multinœud, y compris ONTAP MetroCluster SDS, assurez-vous de configurer la MTU du réseau interne entre 7500 et 8900 (au lieu de 9000) afin d'adapter la surcharge VXLAN. La MTU du réseau interne peut être configurée avec ONTAP Select Deploy lors du déploiement d'un cluster.

.ONTAP Select prend-il en charge la migration KVM ?
Les machines virtuelles ONTAP Select exécutées sur des pools de stockage de baies externes prennent en charge les migrations dynamiques de virsh.

.Ai-je besoin d'AF ONTAP Select Premium pour VSAN ?
Non, toutes les versions sont prises en charge, que les configurations VSAN ou baie externe soient 100 % Flash.

.Quels sont les paramètres VSAN FTT/FTM pris en charge ?
La machine virtuelle Select hérite de la règle de stockage du datastore VSAN et aucune restriction n'est appliquée aux paramètres FTT/FTM. Notez toutefois que, en fonction des paramètres FTT/FTM, la taille de la machine virtuelle ONTAP Select peut être nettement supérieure à la capacité configurée lors de sa configuration. ONTAP Select utilise des VMDK à mise à zéro et non volumineux qui sont créés lors de la configuration. Pour éviter d'affecter les autres VM utilisant le même datastore partagé, il est important de prévoir une capacité disponible suffisante dans le datastore afin de prendre en charge la taille de machine virtuelle véritablement Select telle que dérivée de la capacité Select et des paramètres FTT/FTM.

.Est-il possible d'exécuter plusieurs nœuds ONTAP Select sur un même hôte s'ils font partie de différents clusters Select ?
Il est possible de configurer plusieurs nœuds ONTAP Select sur le même hôte pour les configurations vNAS uniquement, tant que ces nœuds ne font pas partie du même cluster ONTAP Select. Cette opération n'est pas prise en charge dans les configurations DAS, car plusieurs nœuds ONTAP Select sur le même hôte physique seraient concurrents en vue de l'accès au contrôleur RAID.

.Peut-on disposer d'un hôte avec un seul port 10GE sur le ONTAP Select. Est-il disponible pour ESX et KVM ?
Vous pouvez utiliser un seul port 10GE pour la connexion au réseau externe. Cependant, NetApp vous recommande de l'utiliser uniquement dans les environnements de petit format limités. Cette opération est prise en charge par ESX et KVM.

.Quels processus supplémentaires devez-vous exécuter pour effectuer une migration en direct sur KVM ?
Vous devez installer et exécuter des composants open source CLVM et Pacemaker (pcs) sur chaque hôte participant à la migration en direct. Vous devez accéder aux mêmes groupes de volumes sur chaque hôte.



== VCenter

Il existe plusieurs questions et réponses concernant VMware vCenter.

.Comment ONTAP Select déploie-t-il la communication avec vCenter et quels ports de pare-feu doivent être ouverts ?
ONTAP Select Deploy utilise l'API VMware VIX pour communiquer avec vCenter, l'hôte ESX ou les deux. La documentation VMware indique que la connexion initiale à un serveur vCenter ou à un hôte ESX s'effectue via HTTPS/SOAP sur le port TCP 443. Il s'agit du port HTTP sécurisé sur TLS/SSL. Ensuite, une connexion à l'hôte ESX est établie sur un socket du port TCP 902. Les données transitant par cette connexion sont chiffrées via SSL. De plus, ONTAP Select Deploy émet un  `PING` commande pour vérifier qu'il existe un hôte ESX répondant à l'adresse IP que vous avez spécifiée.

ONTAP Select Deploy doit pouvoir communiquer avec les adresses IP de gestion du cluster et du nœud ONTAP Select comme suit :

* Ping
* SSH (port 22)
* SSL (port 443)


Pour les clusters à deux nœuds, ONTAP Select déploie les hôtes des boîtes aux lettres du cluster. Chaque nœud ONTAP Select doit pouvoir accéder au déploiement ONTAP Select via iSCSI (port 3260).

Pour les clusters multinœuds, le réseau interne doit être entièrement ouvert (pas de NAT ni de pare-feu).

.Quels sont les droits vCenter nécessaires à ONTAP Select Deploy pour créer des clusters ONTAP Select ?
La liste des droits vCenter requis est disponible ici : link:reference_plan_ots_vcenter.html["Serveur VMware vCenter"].



== HAUTE DISPONIBILITÉ et clusters

Il existe plusieurs questions et réponses concernant les paires haute disponibilité et les clusters.

.Quelle est la différence entre un cluster à quatre, six ou huit nœuds et un cluster ONTAP Select à deux nœuds ?
À la différence des clusters à quatre nœuds, à six nœuds et à huit nœuds dans lesquels ONTAP Select déploie la machine virtuelle est principalement utilisée pour créer le cluster, un cluster à deux nœuds utilise en continu la machine virtuelle de déploiement ONTAP Select pour assurer le quorum haute disponibilité. Si la machine virtuelle ONTAP Select Deploy n'est pas disponible, les services de basculement sont désactivés.

.Qu'est-ce que le SDS MetroCluster ?
MetroCluster SDS est une option de réplication synchrone à moindre coût appartenant au secteur des solutions de continuité de l'activité MetroCluster. Il est disponible uniquement avec ONTAP Select, contrairement à NetApp MetroCluster qui est disponible sur FAS Hybrid Flash, AFF et NetApp Private Storage for Cloud.

.En quoi le SDS de MetroCluster est-il différent de celui de NetApp MetroCluster ?
MetroCluster SDS est une solution de réplication synchrone proposée sous la forme de solutions NetApp MetroCluster. Toutefois, les distances prises en charge (~10 km contre 300 km) et le type de connectivité (seuls les réseaux IP sont pris en charge par les protocoles FC et IP).

.Quelle est la différence entre un cluster ONTAP Select à deux nœuds et un ONTAP MetroCluster SDS à deux nœuds ?
Le cluster à deux nœuds est défini comme un cluster pour lequel les deux nœuds se trouvent dans le même data Center, à 300 m les uns des autres. En général, les deux nœuds ont des liaisons ascendantes vers le même commutateur réseau ou le même ensemble de commutateurs réseau connectés par une liaison interswitch.

Le MetroCluster SDS à deux nœuds est défini comme un cluster dont les nœuds sont physiquement séparés (salles différentes, bâtiments différents ou data centers différents) et où les connexions uplink de chaque nœud sont connectées à des commutateurs réseau distincts. Bien que le SDS MetroCluster ne nécessite pas de matériel dédié, l'environnement doit prendre en charge un ensemble d'exigences minimales en termes de latence (5 ms de temps de propagation aller-retour et 5 ms de fluctuation du signal pendant 10 ms) et de distance physique (10 km).

MetroCluster SDS est une fonctionnalité Premium qui requiert la licence Premium ou Premium XL. Une licence Premium prend en charge la création d'ordinateurs virtuels de petite et moyenne taille ainsi que de disques durs et de supports SSD. Toutes ces configurations sont prises en charge.

.Le SDS ONTAP MetroCluster requiert-il du stockage local (DAS) ?
Le SDS ONTAP MetroCluster prend en charge toutes les configurations de stockage (DAS et vNAS).

.ONTAP MetroCluster SDS prend-il en charge le RAID logiciel ?
Oui, la configuration RAID logicielle est prise en charge avec le support SSD sur KVM et ESX.

.ONTAP MetroCluster SDS prend-il en charge les disques SSD et rotatifs ?
Oui, bien qu'une licence Premium soit requise, cette licence prend en charge les ordinateurs virtuels de petite et moyenne taille ainsi que les disques SSD et les supports rotatifs.

.ONTAP MetroCluster SDS prend-il en charge les tailles de clusters à quatre nœuds ou plus ?
Non, seuls les clusters à deux nœuds avec un médiateur peuvent être configurés en tant que SDS MetroCluster.

.Quelles sont les exigences du SDS ONTAP MetroCluster ?
Les exigences sont les suivantes :

* Trois centres de données (un pour le ONTAP Select déploient Mediator et un pour chaque noeud).
* 5ms de RTT et fluctuation du signal 5 ms pendant un total maximum de 10 ms et une distance physique maximale de 10 km entre les nœuds ONTAP Select.
* Un RTT de 125 ms et une bande passante minimale de 5 Mbit/s entre le Mediator de déploiement ONTAP Select et chaque nœud ONTAP Select.
* Une licence Premium ou Premium XL.


.ONTAP Select prend-il en charge vMotion ou VMware HA ?
Les machines virtuelles ONTAP Select qui s'exécutent sur des datastores VSAN ou sur des baies externes (c'est-à-dire les déploiements vNAS) prennent en charge vMotion, DRS et VMware HA.

.ONTAP Select prend-il en charge Storage vMotion ?
Storage vMotion est pris en charge dans toutes les configurations, y compris les clusters ONTAP Select à un ou plusieurs nœuds, et le serveur virtuel ONTAP Select Deploy. Storage vMotion peut être utilisé pour migrer ONTAP Select ou ONTAP Select Deploy VM entre différentes versions de VMFS (VMFS 5 à VMFS 6 par exemple), mais cette utilisation n'est pas limitée. Il est recommandé d'arrêter la machine virtuelle avant de lancer une opération Storage vMotion. Le déploiement de ONTAP Select doit lancer l'opération suivante une fois l'opération de stockage vMotion terminée :

[listing]
----
cluster refresh
----
Notez qu'une opération Storage vMotion entre différents types de datastores n'est pas prise en charge. En d'autres termes, les opérations de stockage vMotion entre datastores de type NFS et datastores VMFS ne sont pas prises en charge. En général, les opérations de stockage vMotion entre datastores externes et datastores DAS ne sont pas prises en charge.

.Le trafic haute disponibilité entre les nœuds ONTAP Select peut-il s'exécuter sur un vSwitch différent et/ou des ports physiques séparés et/ou à l'aide de câbles IP point à point entre les hôtes ESX ?
Ces configurations ne sont pas prises en charge. ONTAP Select ne dispose pas de visibilité sur l'état des liaisons montantes du réseau physique transportant le trafic client. Par conséquent, ONTAP Select s'appuie sur le cœur de haute disponibilité pour s'assurer que la VM est accessible en même temps aux clients et à ses homologues. En cas de perte de connectivité physique, la perte du signal de détection haute disponibilité entraîne le basculement automatique vers l'autre nœud, qui est le comportement souhaité.

La segmentation du trafic HA sur une infrastructure physique distincte peut entraîner la communication d'une VM Select avec son homologue, mais pas avec ses clients. Cela empêche le processus haute disponibilité automatique et entraîne une indisponibilité des données jusqu'à ce qu'un basculement manuel soit appelé.



== Service médiateur

Il y a plusieurs questions et réponses concernant le service de médiateur.

.Qu'est-ce que le service Mediator ?
Un cluster à deux nœuds utilise en permanence la machine virtuelle ONTAP Select Deploy pour obtenir le quorum haute disponibilité. Une machine virtuelle ONTAP Select de déploiement prenant part à une négociation de quorum HA à deux nœuds est appelée une machine virtuelle Mediator.

.Le service Mediator peut-il être distant ?
Oui. ONTAP Select Deploy, agissant en tant que médiateur pour une paire HA à deux nœuds, prend en charge une latence WAN pouvant atteindre 500 ms de temps de propagation aller-retour et nécessite une bande passante minimale de 5 Mbit/s.

.Quel protocole le service Mediator utilise-t-il ?
Le trafic du médiateur est iSCSI, provient des adresses IP de gestion de noeuds ONTAP Select et se termine sur l'adresse IP de déploiement ONTAP Select. Notez que vous ne pouvez pas utiliser le protocole IPv6 pour l'adresse IP de gestion des nœuds ONTAP Select lors de l'utilisation d'un cluster à deux nœuds.

.Puis-je utiliser un service Mediator pour plusieurs clusters HA à deux nœuds ?
Oui. Chaque machine virtuelle ONTAP Select Deploy peut servir de service médiateur commun pour un maximum de 100 clusters ONTAP Select à deux nœuds.

.L'emplacement du service Mediator peut-il être modifié après le déploiement ?
Oui. Il est possible d'utiliser une autre VM de déploiement ONTAP Select pour héberger le service Mediator.

.ONTAP Select prend-il en charge les clusters étirés avec (ou sans) le médiateur ?
Seul un cluster à deux nœuds avec un Mediator est pris en charge dans un modèle de déploiement HA étendu.
