---
sidebar: sidebar 
permalink: reference_api_workflow.html 
keywords: rest api, deploy rest api, rest, workflow, create cluster, curl, json 
summary: Vous pouvez déployer un cluster ONTAP Select à nœud unique sur un hôte VMware ESXi géré par vCenter. 
---
= Créez un cluster d'évaluation ONTAP Select à nœud unique sur ESXi
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez déployer un cluster ONTAP Select à un seul nœud sur un hôte VMware ESXi géré par vCenter. Le cluster est créé avec une licence d'évaluation.

Le workflow de création de cluster diffère dans les cas suivants :

* L'hôte ESXi n'est pas géré par vCenter (hôte autonome).
* Plusieurs nœuds ou hôtes sont utilisés au sein du cluster.
* Le cluster est déployé dans un environnement de production avec une licence achetée.
* L'hyperviseur KVM est utilisé à la place de VMware ESXi.




[[step-1-register-vcenter-server-credential]]
== Étape 1 : Enregistrez l’identifiant du serveur vCenter

Lors du déploiement sur un hôte ESXi géré par un serveur vCenter, vous devez ajouter un identifiant avant d'enregistrer l'hôte. L'utilitaire d'administration Deploy pourra ensuite utiliser l'identifiant pour s'authentifier auprès de vCenter.

[cols="15,15,70"]
|===
| Catégorie | Verbe HTTP | Chemin 


| Déployez | POST | /sécurité/informations d'identification 
|===
Gondolage::


[source, curl]
----
curl -iX POST -H 'Content-Type: application/json' -u admin:<password> -k -d @step01 'https://10.21.191.150/api/security/credentials'
----
Entrée JSON (étape 01)::


[source, json]
----
{
  "hostname": "vcenter.company-demo.com",
  "type": "vcenter",
  "username": "misteradmin@vsphere.local",
  "password": "mypassword"
}
----
Type de traitement:: Asynchrone
Sortie::
+
--
* ID d'identification dans l'en-tête de réponse d'emplacement
* Objet travail


--




[[step-2-register-a-hypervisor-host]]
== Étape 2 : Enregistrez un hôte hyperviseur

Ajoutez un hôte hyperviseur sur lequel la machine virtuelle contenant le nœud ONTAP Select sera exécutée.

[cols="15,15,70"]
|===
| Catégorie | Verbe HTTP | Chemin 


| Cluster | POST | /hôtes 
|===
Gondolage::


[source, curl]
----
curl -iX POST -H 'Content-Type: application/json' -u admin:<password> -k -d @step02 'https://10.21.191.150/api/hosts'
----
Entrée JSON (step02)::


[source, json]
----
{
  "hosts": [
    {
      "hypervisor_type": "ESX",
      "management_server": "vcenter.company-demo.com",
      "name": "esx1.company-demo.com"
    }
  ]
}
----
Type de traitement:: Asynchrone
Sortie::
+
--
* ID d'hôte dans l'en-tête de réponse d'emplacement
* Objet travail


--




[[step-3-create-a-cluster]]
== Étape 3 : Créez un cluster

Lorsque vous créez un cluster ONTAP Select, la configuration de base du cluster est enregistrée et Deploy génère automatiquement les noms des nœuds.

[cols="15,15,70"]
|===
| Catégorie | Verbe HTTP | Chemin 


| Cluster | POST | /clusters 
|===
Gondolage:: Vous devez définir le paramètre de requête node_count sur 1 pour un cluster à nœud unique.


[source, curl]
----
curl -iX POST -H 'Content-Type: application/json' -u admin:<password> -k -d @step03 'https://10.21.191.150/api/clusters? node_count=1'
----
Entrée JSON (étape03)::


[source, json]
----
{
  "name": "my_cluster"
}
----
Type de traitement:: Synchrone
Sortie::
+
--
* ID de cluster dans l'en-tête de réponse d'emplacement


--




[[step-4-configure-the-cluster]]
== Étape 4 : Configurer le cluster

Vous devez fournir les attributs suivants lors de la configuration du cluster.

[cols="15,15,70"]
|===
| Catégorie | Verbe HTTP | Chemin 


| Cluster | CORRECTIF | /clusters/{cluster_id} 
|===
Gondolage:: Veuillez fournir l'identifiant du cluster.


[source, curl]
----
curl -iX PATCH -H 'Content-Type: application/json' -u admin:<password> -k -d @step04 'https://10.21.191.150/api/clusters/CLUSTERID'
----
Entrée JSON (step04)::


[source, json]
----
{
  "dns_info": {
    "domains": ["lab1.company-demo.com"],
    "dns_ips": ["10.206.80.135", "10.206.80.136"]
    },
    "ontap_image_version": "9.5",
    "gateway": "10.206.80.1",
    "ip": "10.206.80.115",
    "netmask": "255.255.255.192",
    "ntp_servers": {"10.206.80.183"}
}
----
Type de traitement:: Synchrone
Sortie:: Aucune




[[step-5-retrieve-the-node-name]]
== Étape 5 : Récupérez le nom du nœud

L'utilitaire d'administration Deploy génère automatiquement les identifiants et les noms des nœuds lors de la création d'un cluster. Avant de pouvoir configurer un nœud, vous devez récupérer l'identifiant qui lui est attribué.

[cols="15,15,70"]
|===
| Catégorie | Verbe HTTP | Chemin 


| Cluster | OBTENEZ | /clusters/{cluster_id}/nœuds 
|===
Gondolage:: Veuillez fournir l'identifiant du cluster.


[source, curl]
----
curl -iX GET -u admin:<password> -k 'https://10.21.191.150/api/clusters/CLUSTERID/nodes?fields=id,name'
----
Type de traitement:: Synchrone
Sortie::
+
--
* Le tableau enregistre chaque élément décrivant un seul nœud avec l'ID et le nom uniques


--




[[step-6-configure-the-nodes]]
== Étape 6 : Configurez les nœuds

Fournissez la configuration de base du nœud, qui est le premier des trois appels API utilisés pour configurer un nœud.

[cols="15,15,70"]
|===
| Catégorie | Verbe HTTP | Chemin 


| Cluster | CHEMIN | /clusters/{cluster_id}/nodes/{node_id} 
|===
Gondolage:: Fournissez l'ID du cluster et l'ID du nœud.


[source, curl]
----
curl -iX PATCH -H 'Content-Type: application/json' -u admin:<password> -k -d @step06 'https://10.21.191.150/api/clusters/CLUSTERID/nodes/NODEID'
----
Entrée JSON (étape 06):: Indiquez l'ID de l'hôte sur lequel le nœud ONTAP Select sera exécuté.


[source, json]
----
{
  "host": {
    "id": "HOSTID"
    },
  "instance_type": "small",
  "ip": "10.206.80.101",
  "passthrough_disks": false
}
----
Type de traitement:: Synchrone
Sortie:: Aucune




[[step-7-retrieve-the-node-networks]]
== Étape 7 : Récupérez les réseaux de nœuds

Identifiez les réseaux de données et de gestion utilisés par le nœud dans le cluster à nœud unique. Le réseau interne n'est pas utilisé avec un cluster à nœud unique.

[cols="15,15,70"]
|===
| Catégorie | Verbe HTTP | Chemin 


| Cluster | OBTENEZ | /clusters/{cluster_id}/nodes/{node_id}/networks 
|===
Gondolage:: Fournissez l'ID du cluster et l'ID du nœud.


[source, curl]
----
curl -iX GET -u admin:<password> -k 'https://10.21.191.150/api/ clusters/CLUSTERID/nodes/NODEID/networks?fields=id,purpose'
----
Type de traitement:: Synchrone
Sortie::
+
--
* Tableau de deux enregistrements décrivant chacun un seul réseau pour le nœud, y compris l'ID et le but uniques


--




[[step-8-configure-the-node-networking]]
== Étape 8 : Configurez le réseau du nœud

Configurez les réseaux de données et de gestion. Le réseau interne n'est pas utilisé avec un cluster à nœud unique.


NOTE: Émettez deux fois l'appel API suivant, une fois pour chaque réseau.

[cols="15,15,70"]
|===
| Catégorie | Verbe HTTP | Chemin 


| Cluster | CORRECTIF | /clusters/{cluster_id}/noeuds/{node_id}/réseaux/{network_id} 
|===
Gondolage:: Fournissez l'ID du cluster, l'ID du nœud et l'ID du réseau.


[source, curl]
----
curl -iX PATCH -H 'Content-Type: application/json' -u admin:<password> -k -d @step08 'https://10.21.191.150/api/clusters/ CLUSTERID/nodes/NODEID/networks/NETWORKID'
----
Entrée JSON (étape 08):: Indiquez le nom du réseau.


[source, json]
----
{
  "name": "sDOT_Network"
}
----
Type de traitement:: Synchrone
Sortie:: Aucune




[[step-9-configure-the-node-storage-pool]]
== Étape 9 : Configurez le pool de stockage du nœud

La dernière étape de la configuration d'un nœud consiste à relier un pool de stockage. Vous pouvez déterminer les pools de stockage disponibles via le client Web vSphere, ou éventuellement via l'API REST de déploiement.

[cols="15,15,70"]
|===
| Catégorie | Verbe HTTP | Chemin 


| Cluster | CORRECTIF | /clusters/{cluster_id}/noeuds/{node_id}/réseaux/{network_id} 
|===
Gondolage:: Fournissez l'ID du cluster, l'ID du nœud et l'ID du réseau.


[source, curl]
----
curl -iX PATCH -H 'Content-Type: application/json' -u admin:<password> -k -d @step09 'https://10.21.191.150/api/clusters/ CLUSTERID/nodes/NODEID'
----
Entrée JSON (par étape 09):: La capacité du pool est de 2 To.


[source, json]
----
{
  "pool_array": [
    {
      "name": "sDOT-01",
      "capacity": 2147483648000
    }
  ]
}
----
Type de traitement:: Synchrone
Sortie:: Aucune




[[step-10-deploy-the-cluster]]
== Étape 10 : Déployez le cluster

Une fois le cluster et le nœud configurés, vous pouvez déployer le cluster.

[cols="15,15,70"]
|===
| Catégorie | Verbe HTTP | Chemin 


| Cluster | POST | /clusters/{cluster_id}/deploy 
|===
Gondolage:: Veuillez fournir l'identifiant du cluster.


[source, curl]
----
curl -iX POST -H 'Content-Type: application/json' -u admin:<password> -k -d @step10 'https://10.21.191.150/api/clusters/CLUSTERID/deploy'
----
Entrée JSON (step10):: Fournissez le mot de passe du compte administrateur ONTAP.


[source, json]
----
{
  "ontap_credentials": {
    "password": "mypassword"
  }
}
----
Type de traitement:: Asynchrone
Sortie::
+
--
* Objet travail


--


.Informations associées
link:deploy-evaluation-ontap-select-ovf-template.html["Déployez une instance d'évaluation de 90 jours d'un cluster ONTAP Select"]
