---
sidebar: sidebar 
permalink: sizing-capacity-tier-license.html 
keywords: license, licensing, Capacity Tiers, usable, space 
summary: La licence Capacity Tiers est basée sur la capacité disque sous-jacente gérée par chaque nœud, et non sur la capacité utilisable du nœud, de la paire haute disponibilité ou du cluster. Chaque licence Capacity Tiers est attribuée à un numéro de série de nœud individuel pour une capacité spécifiée et nécessite un contrat de support associé. 
---
= Considérations relatives au dimensionnement d'une licence ONTAP Select Capacity Tiers
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La licence Capacity Tiers est basée sur la capacité disque sous-jacente gérée par chaque nœud ONTAP Select et non sur la capacité utilisable du nœud, de la paire haute disponibilité ou du cluster. Chaque licence Capacity Tiers est attribuée à un numéro de série de nœud individuel pour une capacité spécifiée et nécessite un contrat de support associé.

La capacité souscrite pour une licence Capacity Tiers est exprimée en TiB entiers, avec un minimum de 1 TiB. Vous calculez la capacité souscrite en multipliant l'espace utilisable par le facteur de surcharge. Le facteur de surcharge diffère entre un cluster à nœud unique et un cluster à plusieurs nœuds (basé sur une paire haute disponibilité) :

* Le facteur de surcharge pour les clusters à nœud unique est de 1,13
* Le facteur de surcharge pour les clusters multi-nœuds est de 2,67


Calculez la capacité sous licence en fonction de l'espace utilisable afin de vous assurer d'en avoir suffisamment pour votre déploiement.

[cols="25,30,45"]
|===
| Description | Nœud unique | Paire HA 


| Espace utilisable | 10 Tio | 5 Tio par nœud 10 Tio pour paire haute disponibilité 


| Espace sous licence | 12 TiB (10 x 1,13 = 11,3, arrondir au TiB entier supérieur) | Deux licences de 14 TiB (5 x 2,67 = 13,35, arrondi au TiB entier supérieur) 


| Espace utilisable maximal par nœud *Remarque* : L’espace géré maximal par nœud ou paire haute disponibilité est de 400 TiB | 353 Tio (400 / 1,13)  a| 
Par nœud dans une paire haute disponibilité :

* 74 Tio [(400 / 2) / 2,67]


Par paire haute disponibilité dans un cluster à plusieurs nœuds :

* Deux nœuds : 148 TiB (2 x 74)
* Quatre nœuds : 296 TiB (4 x 74)
* Six-node : 444 TiB (6 x 74)
* Huit nœuds : 592 TiB (8 x 74)


|===
.Et ensuite
link:task_lic_acquire_ct.html["Acquérir une licence Capacity Tier pour ONTAP Select"]
