---
sidebar: sidebar 
permalink: sizing-capacity-tier-license.html 
keywords: license, licensing, Capacity Tiers, usable, space 
summary: La licence Capacity Tiers est basée sur la capacité disque sous-jacente gérée par chaque nœud, et non sur la capacité utilisable du nœud, de la paire haute disponibilité ou du cluster. Chaque licence Capacity Tiers est attribuée à un numéro de série de nœud individuel pour une capacité spécifiée et nécessite un contrat de support associé. 
---
= Déterminez la taille de la licence Capacity Tiers pour ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La licence Capacity Tiers est basée sur la capacité disque sous-jacente gérée par chaque nœud ONTAP Select et non sur la capacité utilisable du nœud, de la paire haute disponibilité ou du cluster. Chaque licence Capacity Tiers est attribuée à un numéro de série de nœud individuel pour une capacité spécifiée et nécessite un contrat de support associé.

La capacité souscrite pour une licence Capacity Tiers est exprimée en téraoctets (To), avec un minimum de 1 To. Vous calculez la capacité souscrite en multipliant l’espace utilisable par le facteur de surcharge. Le facteur de surcharge estime la capacité logicielle ONTAP Select à déduire de l’espace utilisable et s’applique à la détermination de la capacité ONTAP Select pour les disques NVMe, SSD, HDD ou virtuels. Le facteur de surcharge diffère entre un cluster à nœud unique et un cluster à nœuds multiples (basé sur une paire haute disponibilité).

* Le facteur de surcharge pour les clusters à nœud unique est de 1,13
* Le facteur de surcharge pour les clusters multi-nœuds est de 2,67


Vous devez calculer la capacité sous licence en fonction de l'espace utilisable afin de vous assurer que vous disposez de suffisamment d'espace pour votre déploiement. Par exemple, vous souhaitez 10 To de capacité utilisable pour une paire haute disponibilité (5 To par nœud) :

* Avec une paire haute disponibilité, les données sont dupliquées entre les deux nœuds pour assurer la redondance. Ainsi, pour 10 To de données utilisables dans une paire haute disponibilité, vous devez disposer de 10 To par nœud, au cas où l’un des nœuds serait hors ligne.
* Le facteur de 2,67 double la capacité de chaque nœud et ajoute la capacité de surcharge (0,67) nécessaire au fonctionnement d'ONTAP Select.
* La capacité de licence par nœud est de 14 To (5 x 2,67 = 13,35). Pour la paire haute disponibilité, vous avez besoin de deux licences de 14 To pour disposer de 10 To de capacité utilisable.


[cols="25,30,45"]
|===
| Description | Nœud unique | Paire HA 


| Espace utilisable | 10 To | 5 To par nœud 10 To pour paire haute disponibilité 


| Espace sous licence | 12 To (10 x 1.13 = 11.3, arrondir au To entier supérieur) | Deux licences de 14 TB (5 x 2.67 = 13.35, arrondi au TB entier supérieur) 


| Espace utilisable maximal par nœud *Remarque* : l’espace géré maximal par nœud ou paire haute disponibilité est de 400 TB | 353 To (400 / 1,13)  a| 
Par nœud dans une paire haute disponibilité :

* 149 To (400 / 2,67)


Par paire haute disponibilité dans un cluster à plusieurs nœuds :

* Deux nœuds : 298 To (2 x 149)
* Quatre nœuds : 596 To (4 x 149)
* Six-node : 894 To (6 x 149)
* Huit nœuds : 1,192 To (8 x 149)
* Dix nœuds : 1,490 To (10 x 149)
* Douze nœuds : 1 788 To (12 x 149)


|===
.Et ensuite
link:task_lic_acquire_ct.html["Acquérir une licence Capacity Tier pour ONTAP Select"]
