---
sidebar: sidebar 
permalink: sizing-capacity-pool-license.html 
keywords: license, licensing, Capacity Tiers, usable, space 
summary: La licence Capacity Tiers est basée sur la capacité disque sous-jacente gérée par chaque nœud, et non sur la capacité utilisable du nœud, de la paire haute disponibilité ou du cluster. Chaque licence Capacity Tiers est attribuée à un numéro de série de nœud individuel pour une capacité spécifiée et nécessite un contrat de support associé. 
---
= Considérations relatives au dimensionnement d'une licence ONTAP Select Capacity Pools
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La capacité souscrite pour une licence Capacity Pool est exprimée en téraoctets (To) entiers, avec un minimum de 2 To. Vous calculez la capacité souscrite en multipliant l’espace utilisable par le facteur de surcharge. Le facteur de surcharge estime la capacité de surcharge logicielle ONTAP Select à déduire de l’espace utilisable et s’applique à la détermination de la capacité ONTAP Select pour les disques NVMe, SSD, HDD ou virtuels. Le facteur de surcharge diffère entre les clusters à nœud unique et les clusters à nœuds multiples (basés sur des paires haute disponibilité).

* Le facteur de surcharge pour les clusters à nœud unique est de 1,13
* Le facteur de surcharge pour les clusters multi-nœuds est de 2,67


Vous devez calculer la capacité sous licence en fonction de l'espace utilisable afin de vous assurer qu'elle est suffisante pour votre déploiement. Par exemple, si vous souhaitez 20 To de capacité utilisable pour une paire haute disponibilité (10 To par nœud) :

* Avec une paire haute disponibilité, les données sont dupliquées entre les deux nœuds pour assurer la redondance. Ainsi, pour 20 To de données utilisables dans une paire haute disponibilité, vous devez disposer de 20 To par nœud, au cas où l'un des nœuds serait hors ligne.
* Le facteur de 2,67 double la capacité de chaque nœud et ajoute la capacité de surcharge (0,67) nécessaire au fonctionnement d'ONTAP Select.
* La capacité de licence par nœud est de 27 To (10 x 2,67 = 26,7). Pour la paire haute disponibilité, vous avez besoin de deux licences de 27 To pour disposer de 20 To de capacité utilisable.


[cols="25,30,45"]
|===
| Description | Nœud unique | paire haute disponibilité ou mélange de paire haute disponibilité et de nœud unique 


| Espace utilisable | 20 To | 10 To par cluster à nœud unique 20 To pour paire haute disponibilité 


| Espace sous licence | 23 To (20 x 1.13 = 22.6, arrondir au To entier supérieur) | 54 To (20 x 2,67 = 53,4, arrondir au To entier supérieur) 


| Espace utilisable maximal par nœud *Remarque* : l’espace géré maximal par nœud ou paire haute disponibilité est de 400 TB | 353 To (400 / 1,13)  a| 
Par nœud unique dans un cluster :

149 To (400 / 2,67)

Par paire haute disponibilité dans un cluster :

298 To (2 x 149)

|===
.Et ensuite
link:task_lic_acquire_cp.html["Acquérir une licence Capacity Pools pour ONTAP Select"]
