---
sidebar: sidebar 
permalink: task_cli_upgrade_deploy.html 
keywords: administer, administering, cli, deploy, upgrade deploy 
summary: 'Vous pouvez mettre à niveau une machine virtuelle de déploiement existante en place à l"aide de l"interface de ligne de commande.' 
---
= Mettez à niveau une instance de déploiement ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez mettre à niveau une machine virtuelle utilitaire ONTAP Select Deploy existante sur place à l'aide de l'interface de ligne de commande de l'utilitaire ONTAP Select Deploy.

.Avant de commencer
Assurez-vous que ONTAP Select Deploy n'est pas utilisé pour effectuer d'autres tâches pendant la mise à niveau.  Consultez les notes de version actuelles pour obtenir des informations et des restrictions sur la mise à niveau de l'utilitaire ONTAP Select Deploy.

[NOTE]
====
Si une ancienne instance de l'utilitaire d'administration de ONTAP Select Deploy est installée, vous devez mettre à niveau vers la version actuelle. Le nœud ONTAP Select et le composant ONTAP Select Deploy sont mis à niveau indépendamment. Voir link:concept_adm_upgrading_nodes.html["Mettez à niveau les nœuds ONTAP Select"^] pour plus d'informations.

Vous pouvez effectuer une mise à niveau directe vers ONTAP Select Deploy 9.17.1 à partir d' ONTAP Select Deploy 9.16.1 ou 9.15.1. Pour effectuer une mise à niveau à partir d' ONTAP Select Deploy 9.14.1 ou d'une version antérieure, consultez les notes de version de votre version ONTAP Select .

====


== Étape 1 : Télécharger le package

Pour commencer le processus de mise à niveau, téléchargez le fichier de mise à niveau de la machine virtuelle ONTAP Select Deploy approprié à partir dulink:https://mysupport.netapp.com/site/["Site de support NetApp"^] . Le package de mise à niveau est formaté dans un fichier compressé unique.

.Étapes
. Accédez au link:https://mysupport.netapp.com/site/["Site de support NetApp"^] À l'aide d'un navigateur Web, choisissez *Téléchargements* dans le menu Téléchargements.
. Faites défiler vers le bas et sélectionnez *mise à niveau de déploiement ONTAP Select*.
. Sélectionnez la version souhaitée du progiciel de mise à niveau.
. Consultez le contrat de licence de l'utilisateur final (CLUF) et sélectionnez *accepter et continuer*.
. Sélectionnez et téléchargez le pack approprié en répondant à toutes les invites de votre environnement.




== Étape 2 : Téléchargez le package sur la machine virtuelle ONTAP Select Deploy

Après avoir téléchargé le package, vous devez télécharger le fichier sur la machine virtuelle ONTAP Select Deploy.

.Description de la tâche
Cette tâche décrit une méthode de téléchargement du fichier sur la machine virtuelle ONTAP Select Deploy.  Il existe peut-être d’autres options plus adaptées à votre environnement.

.Avant de commencer
* Vérifiez que le fichier de mise à niveau est disponible sur votre poste de travail local.
* Vérifiez que vous disposez du mot de passe du compte utilisateur administrateur.


.Étapes
. Dans une invite de commandes sur votre poste de travail local, utilisez le `scp` Utilisez l'utilitaire (Secure Copy Protocol) pour charger le fichier image sur la machine virtuelle ONTAP Select Deploy, comme illustré dans l'exemple suivant :
+
....
scp ONTAPdeploy2.12_upgrade.tar.gz admin@10.228.162.221:/home/admin (provide password when prompted)
....


.Résultat
Le fichier de mise à niveau est stocké dans le répertoire personnel de l'utilisateur admin.



== Étape 3 : Appliquer le package de mise à niveau

Après avoir téléchargé le fichier de mise à niveau sur la machine virtuelle ONTAP Select Deploy, vous pouvez appliquer la mise à niveau.

.Avant de commencer
* Vérifiez dans quel répertoire le fichier de mise à niveau a été placé sur la machine virtuelle de l'utilitaire ONTAP Select Deploy.
* Vérifiez qu'ONTAP ONTAP Select Deploy n'est pas utilisé pour effectuer d'autres tâches pendant la mise à niveau.


.Étapes
. Sign in à l'interface de ligne de commande de l'utilitaire ONTAP Select Deploy à l'aide de SSH avec le compte administrateur.
. Effectuez la mise à niveau à l'aide du chemin de répertoire et du nom de fichier appropriés :
+
[source, cli]
----
deploy upgrade -package-path <file_path>
----
+
Exemple de commande :

+
....
deploy upgrade -package-path /home/admin/ONTAPdeploy2.12_upgrade.tar.gz
....


.Une fois que vous avez terminé
Avant la fin de la procédure de mise à niveau, vous êtes invité à créer une sauvegarde de la configuration de la machine virtuelle ONTAP Select Deploy.  Vous devez également vider le cache du navigateur afin de pouvoir afficher les pages ONTAP Select Deploy nouvellement créées.
