---
sidebar: sidebar 
permalink: task_vpi_adm_licenses.html 
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, administer, administering, licenses, licensing 
summary: 'Vous pouvez effectuer plusieurs tâches associées dans le cadre de l"administration des licences ONTAP Select.' 
---
= Licences ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez effectuer plusieurs tâches associées dans le cadre de l'administration des licences ONTAP Select.



== Gérer les licences

Vous pouvez ajouter, modifier et supprimer des licences de niveau de capacité ONTAP Select selon vos besoins.

.Étapes
. Cliquez sur *ONTAP Select Deploy* dans le volet *listes d'inventaire mondiales*.
. Cliquez sur l'onglet *Administration*.
. Développez l'option *Licenses* et cliquez sur *Capacity Tier* ou *Capacity Pool* pour sélectionner le type de licence.
+
Les licences actuelles et tout problème s'affichent.

. Vous pouvez également cliquer sur *Filtering* et créer un filtre pour limiter les licences affichées.
. Effectuez la tâche souhaitée :
+
.. Pour ajouter une licence, cliquez sur *+AJOUTER*, cliquez sur *Télécharger une ou plusieurs licences*, puis sélectionnez un fichier de licence.
.. Pour supprimer une licence existante, cliquez sur l'icône de corbeille située à droite de la licence.



