---
sidebar: sidebar 
permalink: task_cli_upgrade_deploy.html 
keywords: administer, administering, cli, deploy, upgrade deploy 
summary: 'Vous pouvez mettre à niveau une machine virtuelle de déploiement existante en place à l"aide de l"interface de ligne de commande.' 
---
= Mise à niveau d'une instance de déploiement
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez mettre à niveau une machine virtuelle de déploiement existante en place à l'aide de l'interface de ligne de commande.



== Avant de commencer

Assurez-vous que le déploiement n'est pas utilisé pour effectuer d'autres tâches pendant la mise à niveau. Vous devriez voir les notes de version actuelles pour obtenir des informations et des restrictions sur la mise à niveau de l'utilitaire de déploiement.



== Téléchargement du package de mise à niveau

Pour commencer le processus de mise à niveau, vous devez télécharger le fichier de mise à niveau de machine virtuelle de déploiement approprié depuis le site de support NetApp. Le package de mise à niveau est formaté comme un seul fichier compressé.

.Étapes
. Accédez au site de support NetApp à l'aide d'un navigateur Web et cliquez sur *Liens rapides de support*.
. Cliquez sur *Télécharger le logiciel* sous *Top Tasks* et connectez-vous.
. Cliquez sur *Rechercher votre produit*.
. Faites défiler et cliquez sur *ONTAP Select Deploy Upgrade*.
. Sélectionnez la version souhaitée du progiciel de mise à niveau.
. Lisez le contrat de licence utilisateur final (CLUF) et cliquez sur *Accept & continue*.
. Sélectionnez et téléchargez le pack approprié en répondant à toutes les invites de votre environnement.


link:https://mysupport.netapp.com["Support NetApp"^]



== Téléchargement du package sur la machine virtuelle de déploiement

Après l'acquisition du package de mise à niveau, vous devez télécharger le fichier sur la machine virtuelle de déploiement.

Le fichier de mise à niveau doit être disponible sur votre poste de travail local. Vous devez également disposer du mot de passe pour le compte utilisateur administrateur.

Cette tâche décrit une méthode de téléchargement du fichier sur la machine virtuelle de déploiement. D'autres options peuvent être plus adaptées à votre environnement.

.Étapes
. Dans un shell de commande sur votre poste de travail local, utilisez l'utilitaire sftp pour télécharger le fichier image sur la machine virtuelle de déploiement.
+
Exemple

+
....
sftp admin@10.234.81.101 (provide password when prompted)
put ONTAPdeploy2.12_upgrade.tar.gz
exit
....


Le fichier de mise à niveau est stocké dans le répertoire personnel de l'utilisateur admin.



== Application du package de mise à niveau

Une fois le fichier de mise à niveau téléchargé sur la machine virtuelle de déploiement, vous pouvez appliquer la mise à niveau.

Vous devez savoir dans quel répertoire le fichier de mise à niveau a été placé sur la machine virtuelle de l'utilitaire de déploiement. Assurez-vous également que le déploiement n'est pas utilisé pour effectuer d'autres tâches pendant la mise à niveau.

.Étapes
. Connectez-vous à l'interface de ligne de commande de l'utilitaire de déploiement à l'aide de SSH avec le compte d'administrateur.
. Effectuez la mise à niveau à l'aide du chemin de répertoire et du nom de fichier appropriés :
+
`deploy upgrade -package-path FILEPATH`

+
Exemple

+
....
deploy upgrade -package-path /home/admin/
ONTAPdeploy2.12_upgrade.tar.gz
....


Une fois la procédure de mise à niveau terminée, vous êtes invité à créer une sauvegarde de la configuration de la machine virtuelle de déploiement. Vous devez également effacer le cache du navigateur pour pouvoir afficher les nouvelles pages de déploiement.
