---
sidebar: sidebar 
permalink: task_install_deploy.html 
keywords: install, installing, ontap select deploy, deploy administration utility, deploy utility 
summary: 'Vous devez installer l"utilitaire d"administration ONTAP Select Deploy et utiliser l"utilitaire afin de créer un cluster ONTAP Select.' 
---
= Installez ONTAP Select Deploy
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous devez installer l'utilitaire d'administration ONTAP Select Deploy et utiliser l'utilitaire afin de créer un cluster ONTAP Select.



== Téléchargez l'image de la machine virtuelle

Le pack ONTAP Select est téléchargeable depuis le site du support NetApp.

.Description de la tâche
L'utilitaire d'administration ONTAP Select Deploy est proposé en tant que machine virtuelle basée sur le format OVF (Open Virtualization format). Le suffixe du fichier compressé unique `ova`.

.Étapes
. Accédez au site de support NetApp à l'aide d'un navigateur Web et cliquez sur *Liens rapides de support*.
. Cliquez sur *Télécharger le logiciel* sous *Top Tasks* et connectez-vous.
. Cliquez sur *Rechercher votre produit*.
. Faites défiler vers le bas et cliquez sur *ONTAP Select*.
. Sélectionnez la version souhaitée du package.
. Lisez le contrat de licence utilisateur final (CLUF) et cliquez sur *Accept & continue*.
. Sélectionnez et téléchargez le pack approprié en répondant à toutes les invites.




== Vérifiez la signature OVA de déploiement ONTAP Select

Vous devez vérifier la signature OVA (ONTAP Select Open Virtualization Appliance) avant d'installer le package d'installation.

.Avant de commencer
Vérifiez que votre système répond aux exigences suivantes :

* OpenSSL versions 1.0.2 à 3.0 pour la vérification de base
* Accès Internet public pour la vérification du protocole OCSP (Online Certificate Status Protocol)


.Étapes
. Vous pouvez obtenir les fichiers suivants sur la page de téléchargement du produit sur le site de support NetApp :
+
[cols="2*"]
|===
| Fichier | Description 


| `ONTAP-Select-Deploy-Production.pub` | Clé publique utilisée pour vérifier la signature. 


| `csc-prod-chain-ONTAP-Select-Deploy.pem` | La chaîne de confiance de l'autorité publique de certification (AC). 


| `csc-prod-ONTAP-Select-Deploy.pem` | Certificat utilisé pour générer la clé. 


| `ONTAPdeploy.ova` | Exécutable d'installation du produit pour ONTAP Select. 


| `ONTAPdeploy.ova.sig` | L'algorithme SHA-256 est écrasé, puis signé par l'agent RSA (Remote support Agent) à l'aide du `csc-prod` clé et signature pour l'installateur. 
|===
. Vérifiez que le `ONTAPdeploy.ova.sig` le fichier utilise les certificats et les commandes de validation associés.
. Vérifiez la signature à l'aide de la commande suivante :
+
[listing]
----
openssl dgst  -sha256 -verify ONTAP-Select-Deploy-Production.pub -signature ONTAPdeploy.ova.sig  ONTAPdeploy.ova
----




== Déployer la machine virtuelle

Vous devez installer et démarrer la machine virtuelle de déploiement ONTAP Select à l'aide de l'image de la machine virtuelle OVF. Dans le cadre du processus d'installation, vous devez configurer l'interface réseau pour utiliser DHCP ou une configuration IP statique.

.Avant de commencer
Vous devez préparer le déploiement de la machine virtuelle ONTAP Select Deploy :

* Activez la fonctionnalité OVF dans votre navigateur en installant le plug-in d'intégration client VMware ou en effectuant une configuration similaire, si nécessaire
* Activé DHCP dans l'environnement VMware si vous affectez dynamiquement une adresse IP à la machine virtuelle de déploiement


Vous devez disposer des informations de configuration à utiliser lors de la création de la machine virtuelle, notamment le nom de la machine virtuelle, du réseau externe et du nom d'hôte. Lors de la définition d'une configuration de réseau statique, vous avez besoin des informations supplémentaires suivantes :

* Adresse IP de la machine virtuelle déployée
* Masque de réseau
* Adresse IP de la passerelle (routeur)
* Adresse IP du serveur DNS principal
* Adresse IP du second serveur DNS
* Domaines de recherche DNS


.Description de la tâche
Si vous utilisez vSphere, l'assistant déployer le modèle OVF comprend un formulaire pour fournir toutes les informations de configuration de déploiement, y compris la configuration du réseau. Toutefois, si vous choisissez de ne pas utiliser ce formulaire, vous pouvez utiliser la console de la machine virtuelle de déploiement pour configurer le réseau à la place.

.Étapes
. Accédez au client vSphere et connectez-vous.
. Naviguez jusqu'à l'emplacement approprié dans la hiérarchie et sélectionnez *déployer le modèle OVF*.
. Sélectionnez le fichier OVA et remplissez l'assistant déployer modèle OVF en sélectionnant les options appropriées à votre environnement.
+
Vous devez définir le mot de passe du compte administrateur. Vous devez fournir ce mot de passe lors de votre connexion à l'utilitaire de déploiement.

. Une fois la machine virtuelle déployée, sélectionnez la nouvelle machine virtuelle et mettez-la sous tension si elle n'est pas déjà mise sous tension en fonction de vos données fournies à l'assistant de déploiement.
. Si nécessaire, vous pouvez configurer le réseau de déploiement à l'aide de la console de la machine virtuelle :
+
.. Cliquez sur l'onglet *Console* pour accéder au shell de configuration de l'hôte VMware ESXi et surveiller le processus de mise sous tension.
.. Attendez l'invite suivante :
+
Nom d'hôte :

.. Saisissez le nom de l'hôte et appuyez sur *entrée*.
.. Attendez l'invite suivante :
+
Saisissez un mot de passe pour l'utilisateur admin :

.. Saisissez le mot de passe et appuyez sur *entrée*.
.. Attendez l'invite suivante :
+
Utiliser DHCP pour définir les informations de mise en réseau ? [n] :

.. Tapez *n* pour définir une configuration IP statique ou y pour utiliser DHCP, puis appuyez sur *entrée*.
.. Si vous choisissez une configuration statique, fournissez toutes les informations de configuration réseau nécessaires.






== Connectez-vous à l'interface Web de déploiement

Vous devez vous connecter à l'interface utilisateur Web pour confirmer que l'utilitaire de déploiement est disponible et effectuer la configuration initiale.

.Étapes
. Pointez votre navigateur vers l'utilitaire de déploiement à l'aide de l'adresse IP ou du nom de domaine :
+
`\https://<ip_address>/`

. Indiquez le nom et le mot de passe du compte administrateur (admin) et connectez-vous.
. Si la fenêtre contextuelle *Bienvenue dans ONTAP Select* s'affiche, vérifiez les conditions préalables et cliquez sur *OK* pour continuer.
. Si c'est la première fois que vous vous êtes connecté et que vous n'avez pas installé le déploiement à l'aide de l'assistant disponible avec vCenter, fournissez les informations de configuration suivantes lorsque vous y êtes invité :
+
** Nouveau mot de passe pour le compte administrateur (obligatoire)
** AutoSupport (en option)
** Serveur vCenter avec identifiants de compte (facultatif)




.Informations associées
link:task_cli_signing_in.html["Connectez-vous pour déployer à l'aide de SSH"]
