---
sidebar: sidebar 
permalink: task_vpi_adm_support.html 
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, administer, administering, diagnostics, support 
summary: 'Vous pouvez effectuer plusieurs tâches de diagnostic et de support associées dans le cadre de l"administration de ONTAP Select.' 
---
= Diagnostics et support
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez effectuer plusieurs tâches de diagnostic et de support associées dans le cadre de l'administration de ONTAP Select.



== Affichage des paramètres système

Vous pouvez afficher les paramètres de base de l'utilitaire d'administration de déploiement via le plug-in vCenter.

.Étapes
. Cliquez sur *ONTAP Select Deploy* dans le volet *listes d'inventaire mondiales*.
. Cliquez sur l'onglet *Administration*.
. Développez l'option *système* et cliquez sur *Paramètres*.
. Mettez à jour la configuration du système selon vos besoins et cliquez sur *Enregistrer*.




== Affichage des messages d'événement

L'utilitaire d'administration Deploy comprend une fonction de consignation des événements qui fournit des informations sur l'activité du système. Vous pouvez afficher le contenu du journal des événements via le plug-in de déploiement pour déboguer n'importe quel problème ou lorsque vous y êtes invité par le support.

Vous pouvez filtrer la liste des messages d'événement en fonction de plusieurs caractéristiques, notamment :

* Catégorie
* Type
* Niveau
* Fréquence


.Étapes
. Cliquez sur *ONTAP Select Deploy* dans le volet *listes d'inventaire mondiales*.
. Cliquez sur l'onglet *Administration*.
. Développez l'option *Events* et cliquez sur *Deploy*.
. Vous pouvez également cliquer sur filtrage et créer un filtre pour limiter les messages d'événement affichés.




== Activation d'AutoSupport

AutoSupport est le principal outil de dépannage utilisé par NetApp pour prendre en charge ONTAP Select. Vous pouvez activer ou désactiver la fonction AutoSupport si nécessaire.

Une fois le nouveau cluster déployé, vérifiez que AutoSupport est activé. Vous devez désactiver AutoSupport uniquement si nécessaire. Si vous désactivez le protocole AutoSupport, les données sont toujours collectées, mais elles ne sont pas transmises à NetApp.

.Étapes
. Cliquez sur *ONTAP Select Deploy* dans le volet *listes d'inventaire mondiales*.
. Cliquez sur l'onglet *Administration*.
. Développez l'option *AutoSupport* et cliquez sur *configurer*
. Activez ou désactivez le protocole AutoSupport si nécessaire.




== Génération d'un pack AutoSupport

Le plug-in vCenter Deploy comprend la possibilité de générer un package AutoSupport. Vous devez générer un package pour déboguer des problèmes ou lorsque vous y êtes invité par le support.

Vous pouvez générer les packages AutoSupport suivants :

* Déployer les journaux fichiers journaux créés par l'utilitaire ONTAP Select Deploy
* Résolution des problèmes et informations de débogage sur les hôtes de l'hyperviseur et les nœuds ONTAP Select
* Informations sur les performances des hôtes de l'hyperviseur et des nœuds ONTAP Select


.Étapes
. Cliquez sur *ONTAP Select Deploy* dans le volet *listes d'inventaire mondiales*.
. Cliquez sur l'onglet *Administration*.
. Développez l'option *AutoSupport* et cliquez sur *generate*.
. Sélectionnez le type et fournissez une description pour le package ou indiquez un numéro de dossier, puis cliquez sur *générer AutoSupport*.
. Dans le volet de gauche, cliquez sur *Historique* sous *AutoSupport* et recherchez le paquet.
+
Vous pouvez cliquer sur *Actualiser* si nécessaire.



Vous pouvez télécharger le package AutoSupport sur votre poste de travail à l'aide de l'interface utilisateur native de l'utilitaire de déploiement. Vous ne pouvez pas télécharger le pack à l'aide du plug-in Deploy vCenter.
