---
sidebar: sidebar 
permalink: task_install_deploy.html 
keywords: install, installing, ontap select deploy, deploy administration utility, deploy utility 
summary: 'Vous devez installer l"utilitaire d"administration ONTAP Select Deploy et utiliser l"utilitaire afin de créer un cluster ONTAP Select.' 
---
= Installez ONTAP Select Deploy
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous devez installer l'utilitaire d'administration ONTAP Select Deploy et utiliser l'utilitaire afin de créer un cluster ONTAP Select.



== Étape 1 : Télécharger l'image de la machine virtuelle

Téléchargez le package ONTAP Select depuis le site de support NetApp .

.Avant de commencer
https://mysupport.netapp.com/site/user/registration["Vous possédez un compte sur le site de support NetApp"^].

.Description de la tâche
L'utilitaire d'administration ONTAP Select Deploy est fourni sous forme de machine virtuelle (VM) basée sur le standard Open Virtualization Format (OVF). Le fichier compressé unique a le suffixe `OVA` pour les hôtes ESXi et `TGZ` pour les hôtes KVM. La VM fournit le serveur Deploy et les images d'installation pour les nœuds ONTAP Select.

.Étapes
. Accédez à la page link:https://mysupport.netapp.com/site/downloads/["NetApp Support Site téléchargements"^].
. Faites défiler vers le bas et sélectionnez *ONTAP Select Deploy*.
. Sélectionnez la version ONTAP Select souhaitée.
. Consultez le contrat de licence de l'utilisateur final (CLUF) et sélectionnez *accepter et continuer*.
. Sélectionnez et téléchargez le package *ONTAP Select Deploy Install* approprié. Répondez à toutes les invites si nécessaire.




== Étape 2 : Vérifier la signature OVA de déploiement ONTAP Select

Vérifiez la signature de l'appliance de virtualisation ouverte ONTAP Select (OVA) avant d'installer le package d'installation.

.Avant de commencer
Vérifiez que votre système répond aux exigences suivantes :

* OpenSSL versions 1.0.2 à 3.0 pour la vérification de base
* Accès Internet public pour la vérification du protocole OCSP (Online Certificate Status Protocol)


.Étapes
. Obtenez les fichiers suivants à partir de la page de téléchargement du produit sur le site d'assistance NetApp :
+
[cols="2*"]
|===
| Fichier | Description 


| `ONTAP-Select-Deploy-Production.pub` | Clé publique utilisée pour vérifier la signature. 


| `csc-prod-chain-ONTAP-Select-Deploy.pem` | La chaîne de confiance de l'autorité publique de certification (AC). 


| `csc-prod-ONTAP-Select-Deploy.pem` | Certificat utilisé pour générer la clé. 


| `ONTAPdeploy.ova` | Exécutable d'installation du produit pour ONTAP Select. 


| `ONTAPdeploy.ova.sig` | L'algorithme SHA-256 est écrasé, puis signé par l'agent RSA (Remote support Agent) à l'aide du `csc-prod` clé et signature pour l'installateur. 
|===
. Vérifiez que le `ONTAPdeploy.ova.sig` le fichier utilise les certificats et les commandes de validation associés.
. Vérifiez la signature:
+
[source, cli]
----
openssl dgst  -sha256 -verify ONTAP-Select-Deploy-Production.pub -signature ONTAPdeploy.ova.sig  ONTAPdeploy.ova
----




== Étape 3 : Déployer la machine virtuelle

Installez et démarrez la machine virtuelle ONTAP Select Deploy à l'aide de l'image de machine virtuelle OVF. Dans le cadre du processus d'installation, vous configurez l'interface réseau pour utiliser DHCP ou une configuration IP statique.

.Avant de commencer
Dans le cas d'un hyperviseur ESXi, vous devez préparer le déploiement de la VM de déploiement ONTAP Select :

* Activez la fonctionnalité OVF dans votre navigateur en installant le plug-in d'intégration client VMware ou en effectuant une configuration similaire, si nécessaire
* Activez le protocole DHCP dans l'environnement VMware si vous attribuez une adresse IP de manière dynamique à la machine virtuelle de déploiement


Pour les hyperviseurs ESXi et KVM, vous devez disposer des informations de configuration à utiliser lors de la création de la machine virtuelle, y compris le nom de la machine virtuelle, du réseau externe et du nom d'hôte. Lors de la définition d'une configuration de réseau statique, vous avez besoin des informations supplémentaires suivantes :

* Adresse IP de la machine virtuelle de déploiement
* Masque de réseau
* Adresse IP de la passerelle (routeur)
* Adresse IP du serveur DNS principal
* Adresse IP du second serveur DNS
* Domaines de recherche DNS


.Description de la tâche
Si vous utilisez vSphere, l'assistant déployer le modèle OVF comprend un formulaire pour fournir toutes les informations de configuration de déploiement, y compris la configuration du réseau. Toutefois, si vous choisissez de ne pas utiliser ce formulaire, vous pouvez utiliser la console de la machine virtuelle de déploiement pour configurer le réseau.

.Étapes
Les étapes à suivre dépendent de l'utilisation ou non d'un hyperviseur ESXi ou KVM.

[role="tabbed-block"]
====
.VMware ESXi
--
. Accédez au client vSphere et connectez-vous.
. Naviguez jusqu'à l'emplacement approprié dans la hiérarchie et sélectionnez *déployer le modèle OVF*.
. Sélectionnez le fichier OVA et terminez l'assistant de déploiement du modèle OVF. Sélectionnez les options appropriées pour votre environnement.
+
Vous devez définir le mot de passe du compte administrateur. Vous devez fournir ce mot de passe lors de votre connexion à l'utilitaire de déploiement.

. Une fois la machine virtuelle déployée, sélectionnez la nouvelle machine virtuelle. S'il n'est pas encore sous tension en fonction des informations que vous avez saisies dans l'assistant de déploiement, mettez-le sous tension manuellement.
. Si nécessaire, vous pouvez configurer le réseau de déploiement à l'aide de la console de la machine virtuelle :
+
.. Sélectionnez l'onglet *Console* pour accéder au shell de configuration de l'hôte ESXi et surveiller le processus de mise sous tension.
.. Attendez l'invite suivante :
+
Nom d'hôte :

.. Saisissez le nom de l'hôte et appuyez sur *entrée*.
.. Attendez l'invite suivante :
+
Saisissez un mot de passe pour l'utilisateur admin :

.. Saisissez le mot de passe et appuyez sur *entrée*.
.. Attendez l'invite suivante :
+
Utiliser DHCP pour définir les informations de mise en réseau ? [n] :

.. Tapez *n* pour définir une configuration IP statique ou *y* pour utiliser DHCP, puis sélectionnez *entrée*.
.. Si vous choisissez une configuration statique, fournissez toutes les informations de configuration réseau requises.




--
.KVM
--
. Connectez-vous à l'interface de ligne de commande sur le serveur Linux :
+
[listing]
----
ssh root@<ip_address>
----
. Créer un nouveau répertoire et extraire l'image brute de la machine virtuelle :
+
[listing]
----
mkdir /home/select_deploy25
cd /home/select_deploy25
mv /root/<file_name> .
tar -xzvf <file_name>
----
. Créez et démarrez la machine virtuelle KVM en exécutant l'utilitaire d'administration de déploiement :
+
[listing]
----
virt-install --name=select-deploy --vcpus=2 --ram=4096 --os-variant=debian10 --controller=scsi,model=virtio-scsi --disk path=/home/deploy/ONTAPdeploy.raw,device=disk,bus=scsi,format=raw --network "type=bridge,source=ontap-br,model=virtio,virtualport_type=openvswitch" --console=pty --import --noautoconsole
----
. Si nécessaire, vous pouvez configurer le réseau de déploiement à l'aide de la console de la machine virtuelle :
+
.. Se connecter à la console VM :
+
[listing]
----
virsh console <vm_name>
----
.. Attendez l'invite suivante :
+
[listing]
----
Host name :
----
.. Tapez le nom d'hôte et sélectionnez *entrée*.
.. Attendez l'invite suivante :
+
[listing]
----
Use DHCP to set networking information? [n]:
----
.. Tapez *n* pour définir une configuration IP statique ou *y* pour utiliser DHCP, puis sélectionnez *entrée*.
.. Si vous choisissez une configuration statique, fournissez toutes les informations de configuration réseau nécessaires.




--
====


== Étape 4 : Sign in à l’interface web de déploiement

Sign in à l'interface utilisateur web pour confirmer que l'utilitaire Deploy est disponible et effectuer la configuration initiale.

.Étapes
. Pointez votre navigateur vers l'utilitaire de déploiement à l'aide de l'adresse IP ou du nom de domaine :
+
`\https://<ip_address>/`

. Indiquez le nom et le mot de passe du compte administrateur (admin) et connectez-vous.
. Si la fenêtre contextuelle *Bienvenue dans ONTAP Select* s'affiche, vérifiez les conditions préalables et sélectionnez *OK* pour continuer.
. Si c'est la première fois que vous vous êtes connecté et que vous n'avez pas installé le déploiement à l'aide de l'assistant disponible avec vCenter, fournissez les informations de configuration suivantes lorsque vous y êtes invité :
+
** Nouveau mot de passe pour le compte administrateur (obligatoire)
** AutoSupport (en option)
** Serveur vCenter avec identifiants de compte (facultatif)




.Quelles sont les prochaines étapes :
link:task_deploy_cluster.html["Déployer un cluster ONTAP Select"]

.Informations associées
* link:task_cli_signing_in.html["Découvrez comment vous connecter à Deploy à l'aide de SSH"]
* link:deploy-evaluation-ontap-select-ovf-template.html["Découvrez comment déployer une instance d'évaluation de 90 jours d'un cluster ONTAP Select"]

