---
sidebar: sidebar 
permalink: task_vpi_adm_network.html 
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, administer, administering, network, networking 
summary: Il existe plusieurs aspects du réseau que vous pouvez explorer et afficher. 
---
= Vérifiez la connectivité réseau
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Il existe plusieurs aspects du réseau que vous pouvez explorer et afficher.



== Vérifiez la connectivité réseau

Vous pouvez tester la connectivité réseau entre deux nœuds ONTAP Select ou plus sur le réseau de clusters interne. Vous devez généralement exécuter ce test avant le déploiement d'un cluster multinœud afin de détecter les problèmes susceptibles d'entraîner l'échec de l'opération. Vous pouvez également exécuter le test de connectivité après le déploiement et la mise en ligne d'un cluster.

.Description de la tâche
Chaque fois que vous démarrez le test, un nouveau processus est créé en arrière-plan et un identifiant d'exécution unique lui est attribué. Une seule séquence peut être active à la fois.

Le test est toujours exécuté en mode rapide qui effectue un test sans interruption de base. Un test PING est effectué, avec un test de la taille de MTU du réseau et du vSwitch.

.Étapes
. Cliquez sur *ONTAP Select Deploy* dans le volet *listes d'inventaire mondiales*.
. Cliquez sur l'onglet *Administration*.
. Développez l'option *Network* et cliquez sur *Connectivity Checker*.
. Cliquez sur *Exécuter nouveau* pour lancer le test.
. Vous pouvez également cliquer sur *Filtering* et créer un filtre pour limiter les détails de test affichés.




== Afficher l'état du service médiateur

Chaque cluster ONTAP Select à deux nœuds est surveillé par le service de médiateur, qui facilite la gestion de la capacité haute disponibilité partagée par les nœuds. Vous pouvez afficher l'état du service médiateur pour chacun des clusters à deux nœuds définis dans l'utilitaire d'administration Deploy.

.Description de la tâche
Vous pouvez afficher la configuration de chaque médiateur, notamment :

* État actuel
* Deux nœuds ONTAP Select
* Cible iSCSI où les informations de contrôle haute disponibilité sont stockées


.Étapes
. Cliquez sur *ONTAP Select Deploy* dans le volet *listes d'inventaire mondiales*.
. Cliquez sur l'onglet *Administration*.
. Développez l'option *Mediator* et cliquez sur *Status*.
. Vous pouvez également cliquer sur *Filtering* et créer un filtre pour personnaliser la vue des clusters à deux nœuds surveillés par le service médiateur.

