---
sidebar: sidebar 
permalink: task_cluster_expansion_contraction.html 
keywords: cluster, expand, expansion, contract, contraction, six, eight, node deployment workflow, workflow, deployment steps 
summary: 'À partir d" ONTAP Select 9.15.1, vous pouvez augmenter ou diminuer la taille d"un cluster existant.' 
---
= Étendre ou réduire un cluster ONTAP Select sur un hôte ESXi ou KVM
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Augmentez ou diminuez la taille d'un cluster ONTAP Select existant pour les hôtes hyperviseurs ESXi et KVM.  Pour les deux types d'hôtes, vous pouvez augmenter et diminuer la taille du cluster par incréments compris entre quatre et douze nœuds.

Les extensions et contractions de cluster suivantes ne sont pas prises en charge pour les hôtes ESXi et KVM :

* Extension des clusters à un ou deux nœuds à des clusters à six, huit, dix ou douze nœuds.
* Contractions de groupes de six, huit, dix ou douze nœuds à des groupes d'un ou deux nœuds.


[NOTE]
====
Pour modifier le nombre de nœuds dans un cluster à une taille qui n'est pas prise en charge par l'extension ou la contraction du cluster, vous devez effectuer les tâches suivantes :

. Déployez un nouveau cluster multi-nœuds en utilisant le link:task_cli_deploy_cluster.html["CLI"] ou le link:task_deploy_cluster.html["interface Web"] fourni avec l'utilitaire d'administration ONTAP Select Deploy.
. Le cas échéant, migrez les données vers le nouveau cluster en utilisant link:https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-disaster-recovery-concept.html["Réplication SnapMirror"^] .


====
Vous lancez les procédures d’extension et de contraction du cluster à partir d’ ONTAP Select Deploy à l’aide de l’interface CLI, de l’API ou de l’interface Web.



== Considérations relatives au matériel et au stockage

La fonctionnalité d’extension et de contraction de cluster est prise en charge sur les hôtes d’hyperviseur KVM et ESXi suivants.

[role="tabbed-block"]
====
.VMware ESXi
--
À partir d’ ONTAP Select 9.15.1, l’extension et la contraction des clusters sont prises en charge sur les hôtes hyperviseurs ESXi.

L'extension et la contraction des clusters sont prises en charge pour les versions d'hyperviseur ESXi suivantes :

* ESXi 9.0
* ESXi 8.0 U3
* ESXi 8.0 U2
* ESXi 8.0 U1
* ESXi 8.0GA


--
.KVM
--
À partir d' ONTAP Select 9.17.1, l'extension et la contraction des clusters sont prises en charge sur les hôtes hyperviseurs KVM.

L'extension et la contraction des clusters sont prises en charge pour les versions d'hyperviseur KVM suivantes :

* Red Hat Enterprise Linux (RHEL) 64-bit 10.1, 10.0, 9.7, 9.6, 9.5, 9.4, 9.3, 9.2, 9.1, 9.0, 8.8, 8.7 et 8.6
* Rocky Linux 10.1, 10.0, 9.7, 9.6, 9.5, 9.4, 9.3, 9.2, 9.1, 9.0, 8.9, 8.8, 8.7, et 8.6


--
====


== Développez le cluster

Utilisez la fonction d'extension de cluster pour augmenter la taille d'un cluster ONTAP Select existant.

Vous pouvez augmenter la taille d'un cluster existant sur un hôte ESXi ou KVM par incréments comme suit :

* De quatre nœuds à six, huit, dix ou douze nœuds
* De six nœuds à huit, dix ou douze nœuds
* De huit nœuds à dix ou douze nœuds
* De dix à douze nœuds


.Description de la tâche
En prévision de l'extension du cluster, de nouveaux hôtes ESXi et KVM sont ajoutés à l'inventaire et les détails des nouveaux nœuds sont attribués. Avant de lancer l'extension du cluster, une pré-vérification du réseau interne est effectuée.

.Avant de commencer
* Lors du déploiement d'un cluster multi-nœuds, vous devez vous familiariser avec le vérificateur de connectivité réseau. Vous pouvez l'exécuter à l'aide de l'outil link:task_adm_connectivity.html["interface Web"] ou le link:task_cli_connectivity.html["CLI"] .
* Vérifiez que vous disposez des informations de licence pour les nouveaux nœuds.


.Étapes
. Connectez-vous à l'interface utilisateur Web de l'utilitaire de déploiement à l'aide du compte administrateur.
. Sélectionnez l'onglet *Cluster* en haut de la page et sélectionnez le cluster souhaité dans la liste.
. Sur la page de détails du cluster, sélectionnez l'icône d'engrenage à droite de la page et sélectionnez *développer le cluster*.
. Accédez à la section *HA pair 4*.
. Choisissez les détails de configuration de paire haute disponibilité (HA) suivants pour la quatrième paire HA :
+
** Type d'instance
** Noms des nœuds
** Hôtes hyperviseurs associés
** Adresses IP des nœuds
** Licences
** Configuration de la mise en réseau
** Configuration du stockage (type RAID et pools de stockage)


. Sélectionnez *Save HA pair* pour enregistrer les détails de la configuration.
. Fournissez les informations d’identification ONTAP et sélectionnez *Développer le cluster*.
. Sélectionnez *Suivant* et exécutez le pré-contrôle du réseau en sélectionnant *Exécuter*.
+
Le pré-contrôle du réseau vérifie que le réseau interne sélectionné pour le trafic du cluster ONTAP fonctionne correctement.

. Sélectionnez *développer le cluster* pour lancer le processus d'extension du cluster, puis sélectionnez *OK* dans la boîte de dialogue.
+
L'extension du cluster peut prendre jusqu'à 45 minutes.

. Surveillez le processus d'extension de cluster en plusieurs étapes pour vérifier que le cluster a bien été étendu.
. Reportez-vous à l'onglet *Events* pour les mises à jour périodiques de la progression de l'opération. La page est automatiquement actualisée à intervalles réguliers.


.Une fois que vous avez terminé
Après avoir étendu le cluster, vous devriezlink:task_cli_clusters.html["Sauvegardez les données de configuration de déploiement ONTAP Select"] .



== Contrat du cluster

Utilisez la fonction de réduction de cluster pour diminuer la taille d'un cluster ONTAP Select existant.

Vous pouvez réduire la taille d'un cluster existant sur un hôte ESXi ou KVM par incréments comme suit :

* De douze nœuds à dix, huit, six ou quatre nœuds
* De dix nœuds à huit, six ou quatre nœuds
* De huit à six ou quatre nœuds
* De six à quatre nœuds


.Description de la tâche
La paire HA de nœuds souhaitée dans le cluster est sélectionnée pour préparer la contraction du cluster pendant la procédure.

.Étapes
. Connectez-vous à l'interface utilisateur Web de l'utilitaire de déploiement à l'aide du compte administrateur.
. Sélectionnez l'onglet *Cluster* en haut de la page et sélectionnez le cluster souhaité dans la liste.
. Sur la page de détails du cluster, sélectionnez l'icône en forme d'engrenage à droite de la page, puis sélectionnez *Contract Cluster*.
. Sélectionnez les détails de configuration de paire haute disponibilité pour toute paire haute disponibilité que vous souhaitez supprimer et fournissez les informations d'identification ONTAP, puis sélectionnez *Contract Cluster*.
+
L'engagement du cluster peut prendre jusqu'à 30 minutes.

. Surveillez le processus de contraction de cluster en plusieurs étapes pour vérifier que le cluster a bien été contracté.
. Reportez-vous à l'onglet *Events* pour les mises à jour périodiques de la progression de l'opération. La page est automatiquement actualisée à intervalles réguliers.

