---
sidebar: sidebar 
permalink: task_cli_deploy_image_add.html 
keywords: administer, administering, cli, deploy, ontap select image, add 
summary: 'Vous pouvez ajouter une image ONTAP Select à votre instance de l"utilitaire d"administration de déploiement. Une fois l"image installée, vous pouvez l"utiliser lors du déploiement d"un cluster ONTAP Select.' 
---
= Ajoutez une image ONTAP Select à déployer
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez ajouter une image ONTAP Select à votre instance de l'utilitaire d'administration de déploiement. Une fois l'image installée, vous pouvez l'utiliser lors du déploiement d'un cluster ONTAP Select.



== Avant de commencer

À un niveau élevé, le processus utilisé pour ajouter une image ONTAP Select à une instance de déploiement consiste en quatre étapes :

. Téléchargement de l'image d'installation
. Téléchargement de l'image d'installation sur la machine virtuelle de déploiement
. Ajout de l'image d'installation
. Affichage des images d'installation disponibles


Avant d'ajouter de nouvelles images ONTAP Select à déployer, vous devez d'abord supprimer les images inutiles.


NOTE: Vous ne devez ajouter qu'une image ONTAP Select avec une version antérieure à la version d'origine incluse avec votre instance de l'utilitaire de déploiement. L'ajout des dernières versions de ONTAP Select, disponibles auprès de NetApp, n'est pas pris en charge.



== Téléchargez l'image d'installation

Pour commencer à ajouter une image ONTAP Select à une instance de l'utilitaire de déploiement, vous devez télécharger l'image d'installation à partir du site de support NetApp. L'image d'installation de ONTAP Select est formatée sous forme de fichier compressé unique.

.Étapes
. Accédez au site de support NetApp à l'aide d'un navigateur Web et cliquez sur *Liens rapides de support*.
. Cliquez sur *Télécharger le logiciel* sous *Top Tasks* et connectez-vous au site.
. Cliquez sur *Rechercher votre produit*.
. Faites défiler vers le bas et cliquez sur *ONTAP Select*.
. Sous *autres logiciels disponibles sélectionnez le logiciel* cliquez sur *déployer mise à niveau, mise à niveau de nœud, installation d'image*.
. Sélectionnez la version souhaitée du progiciel de mise à niveau.
. Lisez le contrat de licence utilisateur final (CLUF) et cliquez sur *Accept & continue*.
. Sélectionnez et téléchargez le pack approprié en répondant à toutes les invites de votre environnement.




== Téléchargez l'image d'installation à déployer

Après avoir acquis l'image d'installation de ONTAP Select, vous devez charger le fichier sur la machine virtuelle de déploiement.

.Avant de commencer
Le fichier image d'installation doit être disponible sur votre poste de travail local. Vous devez également disposer du mot de passe pour le compte utilisateur administrateur de déploiement.

.Description de la tâche
Cette tâche décrit une méthode de téléchargement du fichier sur la machine virtuelle de déploiement. D'autres options peuvent être plus adaptées à votre environnement.

.Étape
. Dans un shell de commande sur votre poste de travail local, chargez le fichier image sur la machine virtuelle de déploiement.
+
Exemple

+
....
scp image_v_93_install_esx.tgz admin@10.234.81.101:/home/admin (provide password when prompted)
....
+
Exemple

+
....
sftp admin@10.234.81.101 (provide password when prompted)
put image_v_93_install_esx.tgz
exit
....


.Résultat
Le fichier d'installation du nœud est stocké dans le répertoire personnel de l'utilisateur admin.



== Ajoutez l'image d'installation

Vous pouvez ajouter l'image d'installation de ONTAP Select au répertoire déployer des images afin qu'elle soit disponible lors du déploiement d'un nouveau cluster.

.Avant de commencer
Vous devez savoir dans quel répertoire le fichier image d'installation a été placé sur la machine virtuelle de l'utilitaire de déploiement. Il est supposé que le fichier se trouve dans le répertoire personnel de l'administrateur.

.Étapes
. Connectez-vous à l'interface de ligne de commande de l'utilitaire de déploiement à l'aide de SSH avec le compte administrateur (admin).
. Démarrer la coque de Bash :
+
`shell bash`

. Placez le fichier image d'installation dans le répertoire d'images.
+
Exemple
`tar -xf image_v_93_install_esx.tgz -C /opt/netapp/images/`





== Affiche les images d'installation disponibles

Vous pouvez afficher les images ONTAP Select disponibles lors du déploiement d'un nouveau cluster.

.Étapes
. Accédez à la page Web de documentation en ligne à l'aide de la machine virtuelle de l'utilitaire de déploiement et connectez-vous à l'aide du compte administrateur (admin) :
+
`\http://<FQDN|IP_ADDRESS>/api/ui`

+
Utilisez le nom de domaine ou l'adresse IP de la machine virtuelle de déploiement.

. Accédez au bas de la page et cliquez sur *déployer*, puis sur *OBTENIR /images*.
. Cliquez sur *essayez !* pour afficher les images ONTAP Select disponibles.
. Vérifiez que l'image souhaitée est disponible.

